### PR TITLE
Fix #76 #886 #908 #911, many other fixes and optimizations

### LINKED ISSUE #76: Requests scheduling to massive farm of backend servers
Currently `TFW_SCHED_MAX_SERVERS` is defined as 64 backend server at maximum, which is not enough for virtualized environments (virtual hosting or clouds), so it should be extended at least to 64K and all scheduling algorithms also must be updated accordingly to process such number of backend servers.

We still do not expect too many servers per one site group among which client requests are scheduled, but we expect  a lot of independent sites.

**CRUCIAL NOTE:** it's quite atypical to have 64K servers in the same server group. Virtualized environment means many small small sites behind Tempesta FW, i.e. the sense of the issue is HTTP scheduler, which must schedule a request among thousands of server groups. In this case most of server groups can have only one server. Meantime there could be really powerful installations with hundreds upstream servers. Thus 2-tier schedulers (ration, hash etc.) still must have dynamic arrays for connections and servers, but probably we don't need to introduce special data structures able to efficiently handle thousands of servers in the same server group.

### PR DESCRIPTION
**Pull request by krizhanovsky**
Please read commits descriptions

### CODE REVIEW

File: tempesta_fw/http.c [hunk 1]
```diff
@@ -1092,163 +1104,155 @@ tfw_http_conn_snip_fwd_queue(TfwSrvConn *srv_conn, struct list_head *out_queue)
...
+ * Note: the re-scheduled request is put at the tail of a new server's
  * connection queue, and NOT according to their original timestamps.
- * That's the intended behaviour. These requests are unlucky already.
- * They were delayed by waiting in their original server connections,
- * and then by the time spent on multiple attempts to reconnect. Now
- * they have much greater chance to be evicted when it's their turn
- * to be forwarded. The main effort is put into servicing requests
- * that are on time. Unlucky requests are just given another chance
- * with minimal effort.
+ * That's the intended behaviour. Suche rescheduled requests are unlucky
```
Comment (aleksostapenko) [inline tempesta_fw/http.c]: `Suche` -> `Such`

File: tempesta_fw/http.c [hunk 2]
```diff
@@ -414,10 +414,10 @@ tfw_http_conn_msg_free(TfwHttpMsg *hm)
 static inline void
 tfw_http_conn_req_clean(TfwHttpReq *req)
 {
-	spin_lock(&((TfwCliConn *)req->conn)->seq_qlock);
+	spin_lock_bh(&((TfwCliConn *)req->conn)->seq_qlock);
```
Comment (aleksostapenko) [inline tempesta_fw/http.c]: It seems that there is not necessity to insert `*_bh` spin locks into code that is called from SoftIRQ context only (`tfw_http_conn_req_clean()` and `tfw_http_resp_fwd()`), as SoftIRQ  handlers are serialized on the same CPU and simple `spin_lock` without bottom halves disabling should be enough in these cases.

File: tempesta_fw/sock.c [hunk 3]
```diff
@@ -1136,12 +1136,12 @@ ss_sock_create(int family, int type, int protocol, struct sock **res)
 	struct sock *sk = NULL;
 	const struct net_proto_family *pf;
 
-	rcu_read_lock();
+	rcu_read_lock_bh();
```
Comment (aleksostapenko) [inline tempesta_fw/sock.c]: Don't quite understand this replacement: it seems there are no spinlocks here (with possibility of user/softirq deadlock) that it was necessary to disable softirq; besides, `synchronize_rcu()` is used kernel with `net_families` array - not `*_bh` flavor.

File: tempesta_fw/server.c [hunk 4]
```diff
@@ -59,9 +63,15 @@ static atomic64_t act_sg_n = ATOMIC64_INIT(0);
  * When a server connection is scheduled for connect it increments server's
  * reference count and decrements it after inteded disconnect.
  */
-static LIST_HEAD(sg_list);
-static LIST_HEAD(sg_list_reconfig);
-static DEFINE_RWLOCK(sg_lock);
+#define TFW_SG_HBITS	10
```
Comment (aleksostapenko) [inline tempesta_fw/server.c]: Maybe this parameter should be configurable (for cases when server groups count is much larger or much less than 1K).

**Comment by ikoveshnikov** [comment]
Still reviewing: there is some issue in reconfigurations code. Reconfiguration tests fail and crash Tempesta:
```
   40.543629] [tdb] Start Tempesta DB
[   40.554990] net_ratelimit: 1 callbacks suppressed
[   40.556483] [tempesta] Initializing Tempesta FW kernel module...
[   40.564618] [tempesta] Registering new scheduler: hash
[   40.570745] [tempesta] Registering new scheduler: http
[   40.581123] [tempesta] Registering new scheduler: ratio
[   40.626207] [tempesta] Prepearing for the configuration processing.
[   40.628830] [tempesta] Configuration processing is completed.
[   40.639633] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff94157c400000
[   40.762709] [tdb] Opened table /opt/tempesta/db/cache.tdb: size=268435456 rec_size=0 base=ffff94156c400000
[   40.765524] [tempesta] Open listen socket on: 0.0.0.0
[   40.780090] [tempesta] modules are started
[   50.519206] [tempesta] Live reconfiguration of Tempesta.
[   50.521350] [tempesta] Prepearing for the configuration processing.
[   50.523342] [tempesta] Configuration processing is completed.
[   50.525629] ------------[ cut here ]------------
[   50.527083] kernel BUG at /home/user/tempesta/tempesta/tempesta_fw/http.c:1330!
[   50.528735] invalid opcode: 0000 [#1] SMP
[   50.528735] Modules linked in: tfw_sched_ratio(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) tempesta_tls(O) crct10dif_pclmul binfmt_misc crc32_pclmul snd_hda_codec_generic iTCO_wdt iTCO_vendor_support ghash_clmulni_intel ppdev snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep snd_pcm evdev snd_timer snd lpc_ich serio_raw pcspkr soundcore mfd_core virtio_balloon sg virtio_console qxl parport_pc parport ttm drm_kms_helper button drm shpchp ip_tables x_tables autofs4 ext4 crc16 jbd2 crc32c_generic fscrypto ecb mbcache sr_mod cdrom virtio_blk virtio_net crc32c_intel ahci libahci aesni_intel i2c_i801 i2c_smbus aes_x86_64 glue_helper lrw gf128mul ablk_helper cryptd psmouse uhci_hcd ehci_pci ehci_hcd libata usbcore usb_common sym53c8xx scsi_transport_spi scsi_mod virtio_pci virtio_ring virtio [last unloaded: tempesta_tls]
[   50.534804] CPU: 0 PID: 1453 Comm: sysctl Tainted: G           O    4.9.0-tempesta-amd64 #1 Debian 4.9.35-tfw4-1
[   50.534804] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.11.0-20171110_100015-anatol 04/01/2014
[   50.534804] task: ffff94155b449d00 task.stack: ffffb0c1816c8000
[   50.534804] RIP: 0010:[<ffffffffc085bd23>]  [<ffffffffc085bd23>] tfw_http_req_destruct+0x53/0x60 [tempesta_fw]
[   50.534804] RSP: 0018:ffff94157fc03c30  EFLAGS: 00010206
[   50.534804] RAX: ffff9415597e63f0 RBX: ffff94155aeba020 RCX: 000000010010000a
[   50.534804] RDX: ffff94155aeba3f0 RSI: ffffd99fc1667c40 RDI: ffff94155aeba020
[   50.534804] RBP: ffff94157fc03c50 R08: ffff9415599f1200 R09: 000000010010000a
[   50.534804] R10: ffff9415599f1400 R11: 2ce33e6c02ce3300 R12: ffff9415599b5678
[   50.534804] R13: ffff94157fc03c50 R14: ffff9415599b572c R15: ffff94157fc03c50
[   50.534804] FS:  00007f4d1a61b880(0000) GS:ffff94157fc00000(0000) knlGS:0000000000000000
[   50.534804] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   50.534804] CR2: 00007f4d19d15d00 CR3: 000000005b8fb000 CR4: 00000000003406f0
[   50.534804] Stack:
[   50.534804]  ffff9415599b5678 ffffffffc085f579 ffff94155aeba020 ffffffffc085be92
[   50.534804]  ffff94157fc03c50 ffff94157fc03c50 0000000059645e70 212fd317b59b8a3f
[   50.534804]  0000000700000024 ffff9415599f0020 ffff94155aeba020 ffff94157fc1a540
[   50.534804] Call Trace:
[   50.534804]  <IRQ> [   50.534804]  [<ffffffffc085f579>] ? tfw_http_msg_free+0x89/0xa0 [tempesta_fw]
[   50.534804]  [<ffffffffc085be92>] ? tfw_http_resp_fwd+0x162/0x2c0 [tempesta_fw]
[   50.534804]  [<ffffffffc085c177>] ? tfw_http_send_resp+0x187/0x1a0 [tempesta_fw]
[   50.534804]  [<ffffffffc085cc2c>] ? tfw_http_conn_shrink_fwdq_resched+0x23c/0x2b0 [tempesta_fw]
[   50.534804]  [<ffffffffc085ceb4>] ? tfw_http_conn_release+0x214/0x240 [tempesta_fw]
[   50.534804]  [<ffffffffc0859334>] ? tfw_connection_release+0x24/0x50 [tempesta_fw]
[   50.534804]  [<ffffffffc087ed7e>] ? tfw_srv_conn_release+0xe/0x80 [tempesta_fw]
[   50.534804]  [<ffffffffc087bbcc>] ? ss_tx_action+0x38c/0x4b0 [tempesta_fw]
[   50.534804]  [<ffffffffb95048db>] ? net_tx_action+0x9b/0x1d0
[   50.534804]  [<ffffffffb9610d1a>] ? __do_softirq+0x10a/0x29a
[   50.534804]  [<ffffffffc087f090>] ? tfw_sock_srv_grace_shutdown_srv+0x110/0x110 [tempesta_fw]
[   50.534804]  [<ffffffffb960f16c>] ? do_softirq_own_stack+0x1c/0x30
[   50.534804]  <EOI> [   50.534804]  [<ffffffffb908056d>] ? do_softirq.part.18+0x3d/0x50
[   50.534804]  [<ffffffffb90805f8>] ? __local_bh_enable_ip+0x78/0x80
[   50.534804]  [<ffffffffc087ee73>] ? tfw_sock_srv_disconnect_srv+0x83/0xb0 [tempesta_fw]
[   50.534804]  [<ffffffffc087f07c>] ? tfw_sock_srv_grace_shutdown_srv+0xfc/0x110 [tempesta_fw]
[   50.534804]  [<ffffffffc087f0f7>] ? __tfw_cfgop_update_sg_srv_list+0x67/0x1a0 [tempesta_fw]
[   50.534804]  [<ffffffffc087f090>] ? tfw_sock_srv_grace_shutdown_srv+0x110/0x110 [tempesta_fw]
[   50.534804]  [<ffffffffc087f090>] ? tfw_sock_srv_grace_shutdown_srv+0x110/0x110 [tempesta_fw]
[   50.534804]  [<ffffffffc0879940>] ? __tfw_sg_for_each_srv+0x70/0xa0 [tempesta_fw]
[   50.534804]  [<ffffffffc087eac5>] ? tfw_sock_srv_start+0xf5/0x330 [tempesta_fw]
[   50.534804]  [<ffffffffc087784d>] ? tfw_ctlfn_state_io+0x36d/0x530 [tempesta_fw]
[   50.534804]  [<ffffffffb960b77e>] ? mutex_lock+0xe/0x30
[   50.534804]  [<ffffffffc0877524>] ? tfw_ctlfn_state_io+0x44/0x530 [tempesta_fw]
[   50.534804]  [<ffffffffb9282b43>] ? proc_sys_call_handler+0xe3/0x100
[   50.534804]  [<ffffffffb9208820>] ? vfs_write+0xb0/0x190
[   50.534804]  [<ffffffffb9209c12>] ? SyS_write+0x52/0xc0
[   50.534804]  [<ffffffffb960e1fb>] ? system_call_fast_compare_end+0xc/0x9b
[   50.534804] Code: 03 00 00 48 8d 97 e0 03 00 00 48 39 c2 75 1e 48 8b bf 58 03 00 00 48 85 ff 74 09 48 83 c4 08 e9 74 b0 01 00 48 83 c4 08 c3 0f 0b <0f> 0b 0f 0b 66 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 41 57 41 
[   50.534804] RIP  [<ffffffffc085bd23>] tfw_http_req_destruct+0x53/0x60 [tempesta_fw]
[   50.534804]  RSP <ffff94157fc03c30>
```
The crash happened on `reconf.test_stress_sched_hash.SchedHashCustomSg.test_hash_del_add_srvs`. In the same time i have no issues with `reconf` tests on current master

File: tempesta_fw/http.c (hunk 2 above)
Comment (aleksostapenko) [reply tempesta_fw/http.c]: Yes, but I didn't find any call from user context (e.g. for `tfw_http_conn_req_clean()`).
On the other hand it seems that using `*_bh` spin locks does not affect either the performance or the lock contention. So this is just a discussion note.

Comment (krizhanovsky) [reply tempesta_fw/http.c]: Example of process context calls: `tfw_cfgop_update_sg_srv_list()` -> `tfw_sock_srv_start_srv()` -> `tfw_sock_srv_connect_srv()` -> `tfw_sock_srv_connect_try_later()` -> `tfw_connection_repair()` -> `conn_repair = tfw_http_conn_repair()` -> `tfw_http_conn_shrink_fwdq()` -> `tfw_http_req_zap_error()` -> `tfw_http_error_resp_switch()` -> `tfw_http_send_resp()` -> `tfw_http_resp_build_error()` -> `tfw_http_conn_req_clean()`.

File: tempesta_fw/sock.c (hunk 3 above)
Comment (krizhanovsky) [reply tempesta_fw/sock.c]: Basically the reason is the same as for https://github.com/tempesta-tech/tempesta/pull/916#discussion_r171842284 : `ss_sock_create()` can be called from process contest on the system start as well as from softirq context on server reconnection attempt (timer context). Updated https://github.com/tempesta-tech/tempesta/issues/736#issuecomment-369945612

File: tempesta_fw/server.c (hunk 4 above)
Comment (krizhanovsky) [reply tempesta_fw/server.c]: We spend 4 pages for both of the hash tables, so reducing hash size won't give us big memory win. There is no need to move the hash size to configuration, since we're able to estimate the optimal hash size by the number of configured server groups. I have no idea whether it has sense to optimize the data structure further to handle 100K and more server groups, since profiling results has shown timers as the main bottleneck.

**Comment by krizhanovsky** [comment]
The crash https://github.com/tempesta-tech/tempesta/pull/916#issuecomment-368636758 is due to assertion `BUG_ON(!list_empty(&req->fwd_list))`. The root casue is that `tfw_http_conn_shrink_fwdq_resched()` calls `tfw_http_req_err()` with `srv_conn == NULL` since it passes the whole `srv_conn->fwd_queue` to `schq`, so `tfw_http_req_delist()` isn't called for a request. The assertion fail is expected and harmless in general, but still must be fixed.

File: tempesta_fw/http.c (hunk 2 above)
Comment (aleksostapenko) [reply tempesta_fw/http.c]: Yes, i was wrong here. Missed this path.
Thanks.
