### PR TITLE
Fix socket cpu migration

### LINKED ISSUE #2075: Socket cpu migration
Currently there are a lot of cases when we can observe socket CPU migration. This situation can leads to two problems: performance degradation upon capture socket lock and response reordering (which leads to violation of the HTTP1 RFC).

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
Socket cpu migration can lead to two problems:
performance degradation and response reordering,
which leads to broken HTTP1.
Previously we use RSS and RPS to prevent it, but
there were several problems in our scripts:
- we exclude loopback interfaces from setup, because
  we don't take into account response reordering
  problem.
- we don't take into account that some interfaces
  have some suffix lile @if14, and we should remove
  it from device name in our scripts.
- we don't try to setup combined RSS queues, only
  RX queues, but there are a lot of cases when network
  interface has only combined queues.
- we don't take into account overflow when we calculate
  1 << x, when x is greater or equal then 64.
- When we setup RPS we use cpu_mask, which is calculated
  as $(perl -le 'printf("%x", (1 << '$CPUS_N') - 1)').
  But in this case we use all cpus, not only one.
- we don't setup RPS for network interface if, RSS setup
  fails.
This patch fix all this problems.

Closes #2075

### CODE REVIEW

**Comment by EvgeniiMekhanik** [comment]
When we use all existing CPUs, when we set RPS it is ok. CPU will be changed only one time and only for loopback, becase for loopback we set skb_hash in tcp_make_synack and this skb will return to us! It is not a problem, because later CPU will be calulated correctly in netif_rx_skb_internal for all other skbs.

File: scripts/tfw_lib.sh [hunk 1]
```diff
@@ -92,19 +91,83 @@ irqbalance_ban_irqs()
 	systemctl restart irqbalance.service >/dev/null
 }
 
+# This function prepares cpu mask for RSS and RPS.
+# It takes into account that we can't calculate
+# value, which is greater when (1 << 63) and cam't
```
Comment (const-t) [inline scripts/tfw_lib.sh:96]: `cam't` typo

**Review by const-t — COMMENTED** [review]
`functionfor` typo

**Comment by EvgeniiMekhanik** [comment]
Do not review the second commit. I move it in separate PR.

**Review by const-t — APPROVED** [review]
LGTM, please don't forget to remove second commit.

File: scripts/tfw_lib.sh [hunk 2]
```diff
@@ -92,19 +91,83 @@ irqbalance_ban_irqs()
...
+	val=0
+	cond=0
+
+	echo `make_cpu_mask $delta $mask32 $val $cond`
+}
+
+make_cpu_rps_mask()
+{
+	delta=$1
+	# enable all CPUs, which is less the (1 << delta) - 1
```
Comment (krizhanovsky) [inline scripts/tfw_lib.sh:149]:
```suggestion
	# enable all CPUs, which is less than (1 << delta) - 1
```

**Review by krizhanovsky — APPROVED** [review]
LGTM

File: scripts/tfw_lib.sh (hunk 1 above)
Comment (EvgeniiMekhanik) [reply scripts/tfw_lib.sh:96]: Fixed

File: scripts/tempesta.sh [hunk 3]
```diff
@@ -46,12 +46,12 @@ tls_mod=tempesta_tls
 tdb_mod=tempesta_db
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply scripts/tempesta.sh:46]: Fixed
