### PR TITLE
Fix #925; improve WQ testing for #922

### LINKED ISSUE #925: Possible Oops on ^C during tests
```
.............
[  748.324979] [tdb] Start Tempesta DB
[  748.464820] [tempesta] Initializing Tempesta FW kernel module...
[  748.528567] [tempesta] Registering new scheduler: hash
[  748.585336] [tempesta] Registering new scheduler: http
[  750.967903] net_ratelimit: 1 callbacks suppressed
[  750.968199] [tempesta] Prepearing for the configuration processing.
[  750.973202] [tempesta] Configuration processing is completed.
[  751.036060] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff98ad7c000000
[  752.021850] [tdb] Opened table /opt/tempesta/db/cache.tdb: size=268435456 rec_size=0 base=ffff98ad6c000000
[  752.023164] [tempesta] Open listen socket on: 0.0.0.0
[  752.023646] [tempesta] modules are started
[  762.175820] [tempesta] Stopping all modules...
[  763.400124] [tdb] Close table 'cache0.tdb'
[  763.581113] [tdb] Close table 'filter0.tdb'
[  763.581524] [tempesta] modules are stopped
[  763.581941] [tempesta] New configuration is cleaned.
[  763.604416] [tempesta] Un-registering scheduler: hash
[  763.624705] [tempesta] Un-registering scheduler: http
[  763.652355] [tempesta] Un-registering scheduler: ratio
[  763.698901] [tempesta] exiting...
[  763.733672] [tdb] Shutdown Tempesta DB
[  764.597959] [tdb] Start Tempesta DB
[  764.732565] [tempesta] Initializing Tempesta FW kernel module...
[  764.792620] [tempesta] Registering new scheduler: hash
[  764.849204] [tempesta] Registering new scheduler: http
[  768.131984] net_ratelimit: 1 callbacks suppressed
[  768.133899] [tempesta] Prepearing for the configuration processing.
[  768.137053] [tempesta] Configuration processing is completed.
[  768.204097] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff98ad7c000000
[  768.220647] [tdb] ERROR: Cannot read 268435456 bytes to addr ffff98ad6c000000, ret = 2887680
[  768.221375] BUG: unable to handle kernel paging request at 00000000002c1000
[  768.221976] IP: [<ffffffffc04b4bbe>] tdb_htrie_init+0x1e/0x1d0 [tempesta_db]
[  768.222516] PGD 0 

[  768.223017] Oops: 0000 [#1] SMP DEBUG_PAGEALLOC
[  768.224062] Modules linked in: tfw_sched_ratio(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) tempesta_tls(O) fuse edac_mce_amd edac_core crct10dif_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 e1000 lrw ppdev psmouse gf128mul glue_helper parport_pc ablk_helper parport cryptd sr_mod pcspkr battery button cdrom sg i2c_piix4 ac ip_tables x_tables autofs4 ext4 crc16 jbd2 fscrypto mbcache serio_raw sd_mod [last unloaded: tempesta_tls]
[  768.224062] CPU: 0 PID: 7636 Comm: sysctl Tainted: G           O    4.9.35-kdump+ #17
[  768.224062] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[  768.224062] task: ffff98ad2e6222c0 task.stack: ffffbbf500dac000
[  768.224062] RIP: 0010:[<ffffffffc04b4bbe>]  [<ffffffffc04b4bbe>] tdb_htrie_init+0x1e/0x1d0 [tempesta_db]
[  768.224062] RSP: 0018:ffffbbf500dafc78  EFLAGS: 00010296
[  768.224062] RAX: ffff98ad597e8be0 RBX: ffff98ad53131f40 RCX: ffff98ad597e8be0
[  768.224062] RDX: 0000000000000000 RSI: 0000000010000000 RDI: 00000000002c1000
[  768.224062] RBP: ffffbbf500dafca8 R08: 0000000000000000 R09: 0000000000000001
[  768.224062] R10: 0000000000000000 R11: 00000000ad073f01 R12: 434947414d424454
[  768.224062] R13: 00000000002c1000 R14: 0000000000000000 R15: ffff98ad3e4896c0
[  768.224062] FS:  00007f136b378880(0000) GS:ffff98ad7f800000(0000) knlGS:0000000000000000
[  768.224062] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  768.224062] CR2: 00000000002c1000 CR3: 000000003117b000 CR4: 00000000000406f0
[  768.224062] Stack:
[  768.224062]  ffffbbf500dafca8 ffff98ad53131f40 0000000000000005 0000000010000000
[  768.224062]  0000000000000000 ffff98ad3e4896c0 ffffbbf500dafd08 ffffffffc04b5a82
[  768.224062]  0000000000000001 ffff98ad3e4896c0 ffff98ad53131f51 0000000000000000
[  768.224062] Call Trace:
[  768.224062]  [<ffffffffc04b5a82>] tdb_open+0xd2/0x250 [tempesta_db]
[  768.224062]  [<ffffffffc04c4b9a>] tfw_cache_start+0x8a/0x2b0 [tempesta_fw]
[  768.224062]  [<ffffffffc04e7598>] tfw_ctlfn_state_io+0x368/0x520 [tempesta_fw]
[  768.224062]  [<ffffffffc04e726f>] ? tfw_ctlfn_state_io+0x3f/0x520 [tempesta_fw]
[  768.224062]  [<ffffffffc04e7231>] ? tfw_ctlfn_state_io+0x1/0x520 [tempesta_fw]
[  768.224062]  [<ffffffffabe1dd75>] proc_sys_call_handler+0xe5/0x100
[  768.224062]  [<ffffffffabe1dd9f>] proc_sys_write+0xf/0x20
[  768.224062]  [<ffffffffabda6f12>] __vfs_write+0x32/0x160
[  768.224062]  [<ffffffffabda8240>] vfs_write+0xb0/0x190
[  768.224062]  [<ffffffffabda9663>] SyS_write+0x53/0xc0
[  768.224062]  [<ffffffffac1724e4>] entry_SYSCALL_64_fastpath+0x17/0x98
[  768.224062] Code: 1f 40 00 66 2e 0f 1f 84 00 00 00 00 00 55 48 89 e5 41 57 41 56 41 55 41 54 49 bc 54 44 42 4d 41 47 49 43 53 49 89 fd 48 83 ec 08 <4c> 39 27 0f 84 b2 00 00 00 48 b8 00 00 00 00 20 00 00 00 48 89 
[  768.224062] RIP  [<ffffffffc04b4bbe>] tdb_htrie_init+0x1e/0x1d0 [tempesta_db]
[  768.224062]  RSP <ffffbbf500dafc78>
[  768.224062] CR2: 00000000002c1000
[  768.262539] ---[ end trace 43090f391307de7a ]---
```

possible related with #922

### PR DESCRIPTION
**Pull request by krizhanovsky**

### CODE REVIEW

File: tempesta_db/core/htrie.c [hunk 1]
```diff
@@ -247,8 +247,13 @@ tdb_htrie_init_bucket(TdbBucket *b)
 	b->flags = 0;
 	rwlock_init(&b->lock);
 #ifdef CONFIG_LOCKDEP
+	/*
+	 * To lock buckets in a chain for the trie traversal.
+	 * Use subclass > SINGLE_DEPTH_NESTING to avoid collisions with
+	 * kernel and Tempesta FW locking subclasses.
+	 */
 	lockdep_init_map(&b->lock.dep_map, "TdbBucket->lock",
-			 &__lockdep_no_validate__, SINGLE_DEPTH_NESTING);
```
Comment (ikoveshnikov) [inline tempesta_db/core/htrie.c]: Please, update copyright for `htrie.c`, `sock_clnt.c`

Comment (krizhanovsky) [reply tempesta_db/core/htrie.c]: Oops, I thought I did this. Thanks!
