### PR TITLE
Fix x509 certificate parsing

### LINKED ISSUE #2156: New Let's Encrypt certificate with SHA384 parsing error
Let's Encrypt now goes with SHA384 instead of SHA256 signature and Tempesta can't load the certificate:
```
[   16.932088] [tempesta tls] Warning: PK - Elliptic curve with OID 1.3.132.0.34 is unsupported
[   16.933888] [tempesta fw] ERROR: tls_certificate: Invalid certificate specified (ffffffff)
[   16.935456] [tempesta fw] ERROR: configuration parsing error:
                 31: tls_certificate /etc/tempesta/fullchain.pem;
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The certificate uses `prime256r1`, just as previous, so probably we have a certificate parsing bug. 

```
# openssl x509 -text -in  /var/www/html/tfw-root.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            04:3d:55:5a:02:cb:e1:45:43:49:7a:f4:1b:c9:4f:5d:b2:f5
        Signature Algorithm: ecdsa-with-SHA384
        Issuer: C = US, O = Let's Encrypt, CN = E5
        Validity
            Not Before: Jun 29 17:42:24 2024 GMT
            Not After : Sep 27 17:42:23 2024 GMT
        Subject: CN = tempesta-tech.com
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:42:4c:5c:e5:d6:8c:5f:69:44:23:ee:2b:9f:05:
                    85:f3:f9:df:39:4a:65:ef:81:50:97:ea:5f:e5:1f:
                    f7:e0:3a:38:5e:4e:a0:a7:10:dd:cd:e5:57:a2:18:
                    40:96:0f:96:d6:4c:b1:6f:fc:2b:c2:9a:44:dd:b0:
                    4a:42:6a:be:77
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                54:50:94:62:88:D2:42:8D:89:12:B4:6D:D7:26:85:A0:47:B4:EF:7B
            X509v3 Authority Key Identifier: 
                9F:2B:5F:CF:3C:21:4F:9D:04:B7:ED:2B:2C:C4:C6:70:8B:D2:D7:0D
            Authority Information Access: 
                OCSP - URI:http://e5.o.lencr.org
                CA Issuers - URI:http://e5.i.lencr.org/
            X509v3 Subject Alternative Name: 
                DNS:tempesta-tech.com
            X509v3 Certificate Policies: 
                Policy: 2.23.140.1.2.1
            CT Precertificate SCTs: 
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 3F:17:4B:4F:D7:22:47:58:94:1D:65:1C:84:BE:0D:12:
                                ED:90:37:7F:1F:85:6A:EB:C1:BF:28:85:EC:F8:64:6E
                    Timestamp : Jun 29 18:42:24.691 2024 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:21:00:AE:EF:0C:5E:69:45:99:4F:35:03:54:
                                EE:39:CB:6D:2F:8F:11:54:EA:5E:EA:AC:8C:EE:DC:27:
                                C4:84:6F:37:DC:02:20:2B:0A:25:2D:B6:2C:A1:0A:96:
                                2D:63:B8:3B:F7:63:57:80:68:A5:24:77:BF:E0:B8:92:
                                EA:36:BA:75:9D:AE:A7
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 48:B0:E3:6B:DA:A6:47:34:0F:E5:6A:02:FA:9D:30:EB:
                                1C:52:01:CB:56:DD:2C:81:D9:BB:BF:AB:39:D8:84:73
                    Timestamp : Jun 29 18:42:26.694 2024 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:20:46:D3:35:79:35:A9:A3:8B:5A:79:39:06:
                                C7:F6:56:A1:3A:25:D6:1A:55:8B:3A:E7:C8:80:F1:31:
                                93:0D:BE:D6:02:21:00:C3:C0:3C:5D:91:73:D0:0D:09:
                                79:9C:57:D2:F2:25:9B:9A:7F:A1:0A:C5:3D:C6:53:52:
                                04:78:34:8F:85:CB:37
    Signature Algorithm: ecdsa-with-SHA384
    Signature Value:
        30:65:02:31:00:a2:71:8b:dc:3d:54:79:53:84:7d:8d:f8:2d:
        60:6d:af:be:74:ef:bb:71:b6:d6:fc:3f:4c:f3:7c:19:58:a4:
        ad:b4:f0:a1:02:a8:78:22:25:89:07:d8:47:04:46:80:73:02:
        30:44:bc:70:cd:9c:5d:e2:41:c3:49:da:cf:41:5f:d3:19:36:
        7e:2f:32:42:9d:92:91:e1:a4:37:b6:7c:87:07:c3:65:66:1b:
        f5:68:cc:cb:bf:8c:cc:fa:9d:7c:0c:dd:0b
-----BEGIN CERTIFICATE-----
MIIDgzCCAwmgAwIBAgISBD1VWgLL4UVDSXr0G8lPXbL1MAoGCCqGSM49BAMDMDIx
CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
NTAeFw0yNDA2MjkxNzQyMjRaFw0yNDA5MjcxNzQyMjNaMBwxGjAYBgNVBAMTEXRl
bXBlc3RhLXRlY2guY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQkxc5daM
X2lEI+4rnwWF8/nfOUpl74FQl+pf5R/34Do4Xk6gpxDdzeVXohhAlg+W1kyxb/wr
wppE3bBKQmq+d6OCAhMwggIPMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggr
BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUVFCUYojS
Qo2JErRt1yaFoEe073swHwYDVR0jBBgwFoAUnytfzzwhT50Et+0rLMTGcIvS1w0w
VQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vZTUuby5sZW5jci5v
cmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9lNS5pLmxlbmNyLm9yZy8wHAYDVR0RBBUw
E4IRdGVtcGVzdGEtdGVjaC5jb20wEwYDVR0gBAwwCjAIBgZngQwBAgEwggEEBgor
BgEEAdZ5AgQCBIH1BIHyAPAAdgA/F0tP1yJHWJQdZRyEvg0S7ZA3fx+FauvBvyiF
7PhkbgAAAZBlTj0zAAAEAwBHMEUCIQCu7wxeaUWZTzUDVO45y20vjxFU6l7qrIzu
3CfEhG833AIgKwolLbYsoQqWLWO4O/djV4BopSR3v+C4kuo2unWdrqcAdgBIsONr
2qZHNA/lagL6nTDrHFIBy1bdLIHZu7+rOdiEcwAAAZBlTkUGAAAEAwBHMEUCIEbT
NXk1qaOLWnk5Bsf2VqE6JdYaVYs658iA8TGTDb7WAiEAw8A8XZFz0A0JeZxX0vIl
m5p/oQrFPcZTUgR4NI+FyzcwCgYIKoZIzj0EAwMDaAAwZQIxAKJxi9w9VHlThH2N
+C1gba++dO+7cbbW/D9M83wZWKSttPChAqh4IiWJB9hHBEaAcwIwRLxwzZxd4kHD
SdrPQV/TGTZ+LzJCnZKR4aQ3tnyHB8NlZhv1aMzLv4zM+p18DN0L
-----END CERTIFICATE-----
```

### PR DESCRIPTION
**Pull request by krizhanovsky**
Fix #2156.

The PR is pretty big, but the most of it is improving the TLS code hygiene: use `const` pointers for x509 parsing functions and adjusting coding style. Please review individual patches.

### CODE REVIEW

File: tls/tls_ticket.c [hunk 1]
```diff
@@ -533,31 +534,22 @@ ttls_ticket_sess_load(TlsState *state, size_t len, unsigned long lifetime)
 		if (!sess->peer_cert)
 			return TTLS_ERR_ALLOC_FAILED;
 		/*
-		 * Same as in See ttls_parse_certificate(), we have to copy full
+		 * Same as in ttls_x509_crt_parse(), we have to copy full
 		 * certificate here, since some structures in TlsX509Crt may
 		 * address it.
 		 */
-		pg = alloc_pages(GFP_ATOMIC, get_order(state->cert_len));
+		sess->peer_cert->raw.order = get_order(state->cert_len + TTLS_CERT_LEN_LEN);
```
Comment (const-t) [inline tls/tls_ticket.c:541]: I must pay the attention. This branch of the code is completely disabled, above we have a `BUG()`.

File: tls/pkparse.c [hunk 2]
```diff
@@ -262,17 +262,14 @@ ttls_pk_parse_subpubkey(const unsigned char **p, const unsigned char *end,
...
 	}
 	else {
 		ret = TTLS_ERR_PK_UNKNOWN_PK_ALG;
 	}
 
-	if (ret == 0 && *p != end)
-		ret = TTLS_ERR_PK_INVALID_PUBKEY + TTLS_ERR_ASN1_LENGTH_MISMATCH;
-
-	return ret;
+	return 0;
```
Comment (EvgeniiMekhanik) [inline tls/pkparse.c:272]: We should return `ret` here, because it can be not null `ret = TTLS_ERR_PK_UNKNOWN_PK_ALG;` for example

File: tls/x509_crt.c [hunk 3]
```diff
@@ -673,7 +683,7 @@ x509_write_cert_len(unsigned char *buf, size_t n)
 int
```
Comment (EvgeniiMekhanik) [inline tls/x509_crt.c:683]: Now this function return 0 on success not parsed out length. Fix comment please

**Comment by EvgeniiMekhanik** [comment]
When I run test tls.test_tls_cert.ECDSA_SHA384_SECP256.test (your test from new branch in test suite) it was successful on current master branch

File: tls/x509_crt.c [hunk 4]
```diff
@@ -924,76 +924,58 @@ ttls_x509_crt_parse(TlsX509Crt *chain, unsigned char *buf, size_t buflen)
...
+		r = ttls_pem_read_buffer("-----BEGIN CERTIFICATE-----",
+					 "-----END CERTIFICATE-----",
+					 buf, &use_len);
+		if (r > 0) {
+			/* Was PEM encoded. */
+			pem_dec = buf;
+			buflen -= use_len;
+			buf += use_len;
+		}
+		else if (r != TTLS_ERR_PEM_NO_HEADER_FOOTER_PRESENT) {
```
Comment (EvgeniiMekhanik) [inline tls/x509_crt.c:954]: `r`can be `TTLS_ERR_PEM_FEATURE_UNAVAILABLE` and `TTLS_ERR_PEM_INVALID_DATA` or `TTLS_ERR_PEM_INVALID_DATA + ret`. why we continue parsing certificates here if error occurs?

File: tls/x509_crt.c [hunk 5]
```diff
@@ -924,76 +924,58 @@ ttls_x509_crt_parse(TlsX509Crt *chain, unsigned char *buf, size_t buflen)
...
-				if (!first_error)
-					first_error = r;
-				total_failed++;
-				continue;
-			}
-			else {
-				break;
-			}
+	if (buf_format != TTLS_X509_FORMAT_PEM)
+		return TTLS_ERR_X509_CERT_UNKNOWN_FORMAT;
```
Comment (const-t) [inline tls/x509_crt.c:931]: Seems the loop `for ( ; buflen > 1 && crt_len_len; crt_len_len -= TTLS_CERT_LEN_LEN)` is unreachable for DER. If we successfully parsed DER in `ttls_x509_crt_parse_der()` line 927, we just fall to current location, but in this place we will return `TTLS_ERR_X509_CERT_UNKNOWN_FORMAT`

File: tls/x509_crt.c (hunk 4 above)
Comment (EvgeniiMekhanik) [reply tls/x509_crt.c:954]: I check it is error here. If we create certificate like this
```
-----BEGIN CERTIFICATE-----
MIIBkTCCARgCAQEwCgYIKoZIzj0EAwMwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgM
ClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAe
Fw0yNDA3MDQxMTI0NDZaFw0yNTA3MDQxMTI0NDZaMEUxCzAJBgNVBAYTAkFVMRMw
EQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0
eSBMdGQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASdAgJZTIzvmeLYyWEPAt6D
xsALWO8iLk54JMA3UwNi72lAvTw6VVPiH6K5lESlPAoOayge4oYEp6v8s409J5Z/
MAoGCCqGSM49BAMDA2cAMGQCMGT+Gr+sibbbUI5TRhhMcg+UgSAPVizAjmxpWdtj
RVSsv+6Gh+LxvwqCoQW8vWJOPQIwK+08D7up/Ysguy5v8z+iTrfNhjUnqie0z1LQ
Ryep+3L/W0aw+ySuSI0paUxeNN5K
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Proc-Type: 4,ENCRYPTEDNwYq7pZxPSuAtKbGmi/0dEoHswCgYIKoZIzj0EAwMw
RTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGElu
dGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNDA3MDQxMTIzMzNaFw0yNDA4MDMx
MTIzMzNaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYD
VQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwdjAQBgcqhkjOPQIBBgUrgQQA
IgNiAASaXikki3uhfLWfzcIb6A02bAFasl9nyPrvSnggLThRi/JSVDnA11Gtvsfs
zwB9TQyXPwvp/yNd6HfxdsklAhLX5ekx1MiMd23LoMKegmdexUB/PW/SrA5sPeRX
CWk0MPSjUzBRMB0GA1UdDgQWBBS23OcvU3qYQiHsQUueylpPSBKwLjAfBgNVHSME
GDAWgBS23OcvU3qYQiHsQUueylpPSBKwLjAPBgNVHRMBAf8EBTADAQH/MAoGCCqG
SM49BAMDA2cAMGQCMA351Zabc8zAAlVhCjG1bEziJ92t80MfaoNePWBcpNycBoBd
EDgYN575SGMiJbe6ZwIwULtlC/7SedDyayBdX/UMBjkfKvyvx9tUdsfeUMWwhLX2
YTx3/Ma1IhdwBIvbIGBL
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBkTCCARgCAQEwCgYIKoZIzj0EAwMwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgM
ClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAe
Fw0yNDA3MDQxMTI0NDZaFw0yNTA3MDQxMTI0NDZaMEUxCzAJBgNVBAYTAkFVMRMw
EQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0
eSBMdGQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASdAgJZTIzvmeLYyWEPAt6D
xsALWO8iLk54JMA3UwNi72lAvTw6VVPiH6K5lESlPAoOayge4oYEp6v8s409J5Z/
MAoGCCqGSM49BAMDA2cAMGQCMGT+Gr+sibbbUI5TRhhMcg+UgSAPVizAjmxpWdtj
RVSsv+6Gh+LxvwqCoQW8vWJOPQIwK+08D7up/Ysguy5v8z+iTrfNhjUnqie0z1LQ
Ryep+3L/W0aw+ySuSI0paUxeNN5K
-----END CERTIFICATE-----
```
It is successfully parsed (but second certificate catch error in this place TTLS_ERR_PEM_FEATURE_UNAVAILABLE but `r` will be overwritten for third certificate .).
If we remove third certificate we return error, because it is a last cert in chain and r will be TTLS_ERR_PEM_FEATURE_UNAVAILABLE. 
If first certificate is not parsed but second parsed in fact we don't parse our certificate, parse CA  certificate and work as everything is ok!

Comment (EvgeniiMekhanik) [reply tls/x509_crt.c:954]: Just add `Proc-Type: 4,ENCRYPTED` in you certificate instead of first 22 bytes to simulate it

**Review by EvgeniiMekhanik — CHANGES_REQUESTED** [review]
Need some fixes

**Review by const-t — CHANGES_REQUESTED** [review]
Require little corrections

File: tls/tls_ticket.c [hunk 6]
```diff
@@ -519,14 +519,16 @@ ttls_ticket_sess_load(TlsState *state, size_t len, unsigned long lifetime)
...
-	if (!state->cert_len) {
+	if (likely(!state->cert_len)) {
 		state->sess.peer_cert = NULL;
 	}
 	else {
 		TlsSess *sess = &state->sess;
 		struct page *pg;
 		int r;
 
+		BUG(); /* TODO #830: client-side TLS tickets aren't tested. */
```
[the remark this answers is not in the document]
Comment (krizhanovsky) [reply tls/tls_ticket.c:531]: In which way `ttls_x509_crt_parse_der()` should be reworked? It only works with allocated outside `TlsX509Crt->raw.pages`: `ttls_x509_crt_parse()` uses `GFP_KERNEL` and `ttls_ticket_sess_load()` after the upcoming fix (commented by Evgeny) will ue `GFP_ATOMIC`. It seems this was a confusion - in some patch version I really did allocate memory in `ttls_x509_crt_parse_der()`. Also now we do not have `x509_crt_parse_der_core()`.

File: tls/x509_crt.c (hunk 4 above)
Comment (krizhanovsky) [reply tls/x509_crt.c:954]: This is mbed TLS inherited logic: if we observe any error on certificate parsing, but we see the certificate boundaries (header and footer), we just skip it and continue with the next certificate. I think we should terminate parsing if any of the certificates is invalid - a client won't validate such certificate chain either

File: tls/x509_crt.c (hunk 5 above)
Comment (krizhanovsky) [reply tls/x509_crt.c:931]: Yeah, there is a bug. But we don't need to execute the loop for `TTLS_X509_FORMAT_DER`. In this case we just run `ttls_x509_crt_parse_der()` once and return. But if the format is PEM, then we decode it and parse the encoded DER many times in the loop. Other formats aren't supported, so we return `TTLS_ERR_X509_CERT_UNKNOWN_FORMAT`

File: tls/x509_crt.c (hunk 4 above)
Comment (krizhanovsky) [reply tls/x509_crt.c:954]: Fixed, now I see
```
[  874.310593] [tempesta tls] Warning: Error 1400 on parsing certificate with id 1 in the chain
[  874.310595] [tempesta fw] ERROR: tls_certificate: Invalid certificate specified, err=1400
[  874.314550] [tempesta fw] ERROR: configuration parsing error:
[  874.314550]   12: tls_certificate /root/tempesta/etc/tfw-root-test.crt;
[  874.314550]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
in dmesg on loading the certificate from https://github.com/tempesta-tech/tempesta/pull/2157#discussion_r1665598468

File: tls/tls_ticket.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (const-t) [reply tls/tls_ticket.c:531]: Nevermind, now looks good.

**Review by const-t — APPROVED** [review]

**Review by EvgeniiMekhanik — APPROVED** [review]
