### PR TITLE
tls: close connection if handshake is not done

### LINKED ISSUE #1277: kmem_cache_destroy ttls_hs_cache: Slab cache still has objects
Just got following crash during debugging of #737 . I saw the bug only twice while I was running the same tests for a while, so it seems the bug is hard to reproduce. Tempesta state and configuration:
```
root@debian:~/tempesta# git log |head -1
commit 6bb569743aa5c16fd977bf38b54df260fb78a5de
root@debian:~/tempesta# cat etc/tempesta_fw.conf
listen 443 proto=https;

sched ratio;
server 127.0.0.1:8080;

vhost default {
	proxy_pass default;
}

cache 0;

tls_certificate /root/tempesta/etc/tfw-root.crt;
tls_certificate_key /root/tempesta/etc/tfw-root.key;
```

Crash dump:
```
[ 3891.696495] [tempesta fw]     tfw_mod_unregister: tls
[ 3891.700477] [tempesta fw]     tfw_mod_unregister: vhost
[ 3891.704036] [tempesta fw]     tfw_mod_unregister: apm
[ 3891.720830] [tdb] Shutdown Tempesta DB
[ 3891.736201] kmem_cache_destroy ttls_hs_cache: Slab cache still has objects
[ 3891.741008] CPU: 1 PID: 1103 Comm: rmmod Tainted: G           O    4.14.32-kdump+ #142
[ 3891.744438] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.12.0-2.fc30 04/01/2014
[ 3891.747282] Call Trace:
[ 3891.748304]  dump_stack+0x46/0x5a
[ 3891.749520]  kmem_cache_destroy+0x1c3/0x1d0
[ 3891.751109]  ttls_exit+0x1e/0x60 [tempesta_tls]
[ 3891.752549]  SyS_delete_module+0x19a/0x250
[ 3891.753837]  do_syscall_64+0x61/0x110
[ 3891.755021]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[ 3891.756433] RIP: 0033:0x7ff11006ffd7
[ 3891.757656] RSP: 002b:00007ffdc3516168 EFLAGS: 00000206 ORIG_RAX: 00000000000000b0
[ 3891.759205] RAX: ffffffffffffffda RBX: 00007ffdc35161b8 RCX: 00007ff11006ffd7
[ 3891.760561] RDX: 000000000000000a RSI: 0000000000000800 RDI: 00005608cb3e1258
[ 3891.761852] RBP: 00005608cb3e11f0 R08: 00007ffdc35150e1 R09: 000000000000000a
[ 3891.763136] R10: 0000000000000000 R11: 0000000000000206 R12: 00007ffdc3516380
[ 3891.764440] R13: 00007ffdc3517e28 R14: 0000000000000000 R15: 00005608cb3e11f0
[ 3904.012797] device lo left promiscuous mode
[ 3958.117415] BUG: unable to handle kernel paging request at ffffffffc0403520
[ 3958.120252] IP: 0xffffffffc0403520
[ 3958.121510] PGD 72c0c067 P4D 72c0c067 PUD 72c0e067 PMD 3fc51067 PTE 0
[ 3958.123300] Oops: 0010 [#1] SMP PTI
[ 3958.124541] Modules linked in: binfmt_misc bochs_drm ttm drm_kms_helper drm crct10dif_pclmul ppdev fb_sys_fops pcspkr parport_pc syscopyarea sysfillrect sysimgblt serio_raw button sg parport ip_tables x_tables ext4 crc16 mbcache jbd2 fscrypto sr_mod cdrom sd_mod ata_generic ata_piix libata psmouse scsi_mod e1000 i2c_piix4 [last unloaded: tempesta_lib]
[ 3958.131759] CPU: 1 PID: 0 Comm: swapper/1 Tainted: G           O    4.14.32-kdump+ #142
[ 3958.133670] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.12.0-2.fc30 04/01/2014
[ 3958.135406] task: ffff890173ff30c0 task.stack: ffff890174454000
[ 3958.136708] RIP: 0010:0xffffffffc0403520
[ 3958.137878] RSP: 0018:ffff89017fd03eb0 EFLAGS: 00010206
[ 3958.139231] RAX: 0000000000000000 RBX: 0000000000000001 RCX: ffff89017b14ca50
[ 3958.140616] RDX: ffff89017b14c788 RSI: ffffffffc0403520 RDI: ffff89017b14c788
[ 3958.142567] RBP: 0000000000000100 R08: ffff89017fd19e80 R09: ffff89017fd03ef0
[ 3958.144152] R10: ffff89017fd196b0 R11: ffffffffbd211ae8 R12: ffff89017b14ca50
[ 3958.145520] R13: ffffffffc0403520 R14: ffff89017b14c788 R15: 0000000000000000
[ 3958.146863] FS:  0000000000000000(0000) GS:ffff89017fd00000(0000) knlGS:0000000000000000
[ 3958.148329] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 3958.149860] CR2: ffffffffc0403520 CR3: 0000000072c0a005 CR4: 00000000003606e0
[ 3958.151316] Call Trace:
[ 3958.152153]  <IRQ>
[ 3958.152900]  ? call_timer_fn+0x2b/0x120
[ 3958.153937]  ? run_timer_softirq+0x1c5/0x3f0
[ 3958.154970]  ? tick_sched_do_timer+0x40/0x40
[ 3958.155995]  ? timerqueue_add+0x54/0x80
[ 3958.156977]  ? enqueue_hrtimer+0x33/0x80
[ 3958.158014]  ? __do_softirq+0x104/0x297
[ 3958.159139]  ? irq_exit+0xa3/0xb0
[ 3958.160348]  ? smp_apic_timer_interrupt+0x6b/0x120
[ 3958.162648]  ? apic_timer_interrupt+0x7a/0x80
[ 3958.164129]  </IRQ>
[ 3958.165354]  ? __sched_text_end+0x3/0x3
[ 3958.166792]  ? default_idle+0x12/0xf0
[ 3958.168178]  ? do_idle+0x156/0x1b0
[ 3958.169560]  ? cpu_startup_entry+0x6a/0x70
[ 3958.171116]  ? start_secondary+0x188/0x1b0
[ 3958.172668]  ? secondary_startup_64+0xa5/0xb0
[ 3958.174144] Code:  Bad RIP value.
[ 3958.175443] RIP: 0xffffffffc0403520 RSP: ffff89017fd03eb0
[ 3958.177075] CR2: ffffffffc0403520
[ 3958.178351] ---[ end trace a3f11b8a3db3bcb2 ]---
[ 3958.179887] Kernel panic - not syncing: Fatal exception in interrupt
[ 3958.181730] Kernel Offset: 0x3b600000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[ 3958.183872] Rebooting in 60 seconds..
```

### PR DESCRIPTION
**Pull request by ikoveshnikov**
`tfw_tls_conn_close()` is expected to close connection somehow. It either sends an alert via `ttls_close_notify()` which closes connection after data departure, or calls `ss_close()` explicitly if alert cannot be sent. However, `ttls_close_notify()` may return 0 if TLS handshake wasn't finished yet. In that case connection remains not closed, with keepalive timers armed. Unloading Tempesta from memory makes these timers to crash the kernel.

The patch ensures that connections are closed in all cases.

Fixes #1277.

### CODE REVIEW

File: tempesta_fw/tls.c [hunk 1]
```diff
@@ -588,14 +588,14 @@ tfw_tls_conn_close(TfwConn *c, bool sync)
...
+	 * transmission. Otherwise if we have to close the socket
 	 * and can not write to the socket, then there is no other way than
 	 * skip the alert and just close the socket.
 	 */
-	if (r && sync) {
+	if (r) {
 		TFW_WARN_ADDR("Close TCP socket w/o sending alert to the peer",
 			      &c->peer->addr, TFW_WITH_PORT);
-		r = ss_close(c->sk, SS_F_SYNC);
+		r = ss_close(c->sk, sync ? SS_F_SYNC : 0);
```
Comment (i-rinat) [inline tempesta_fw/tls.c]: I'm a bit worried about calling `ss_close()` without `SS_F_SYNC` flag. That means, sometimes `ss_close()` will return error and won't call sync-socket hooks. It's it safer to always call `ss_close()` with `SS_F_SYNC` flag instead?

Comment (i-rinat) [reply tempesta_fw/tls.c]: OK, I think I understand now. `tfw_connection_close` is called with sync=false from two places and both of them implement some kind of retrying. So even if `ss_close()` returns non-zero here, we will call it again, so eventually hooks will be called too.
