### PR TITLE
Fix invalid deinitialization of tls connection

### LINKED ISSUE #1982: kernel panic in `t_stress.test_wordpress.H2WordpressStress.test_get_large_images`
# Scope

Tempesta commit - [ff0f02145172b92794ef3cd086a12af737caa793](https://github.com/tempesta-tech/tempesta/tree/ff0f02145172b92794ef3cd086a12af737caa793)

config (all servoces on one VM):
```python3
[General]
duration = 10
concurrent_connections = 10
stress_threads = 2
stress_large_content_length = 65536
stress_requests_count = 100
stress_mtu = 1500
```

VM memory  - 8GB.

First kernel panic:

```python
[   86.186816] Start test: t_stress.test_wordpress.H2WordpressStress.test_get_large_images
[   86.463235] docker0: port 1(veth5a06f8c) entered blocking state
[   86.464063] docker0: port 1(veth5a06f8c) entered disabled state
[   86.465826] device veth5a06f8c entered promiscuous mode
[   86.467985] docker0: port 1(veth5a06f8c) entered blocking state
[   86.468693] docker0: port 1(veth5a06f8c) entered forwarding state
[   86.626481] eth0: renamed from veth16d30fd
[   86.646609] IPv6: ADDRCONF(NETDEV_CHANGE): veth5a06f8c: link becomes ready
[   86.742728] [tdb] Start Tempesta DB
[   86.774008] [tempesta fw] Initializing Tempesta FW kernel module...
[   86.842235] [tempesta fw] Warning: Vhost default doesn't have certificate with matching SAN/CN.
[   86.842235]     Maybe that's fine, but it's worth checking the
[   86.842235]     config - if there is no relations between the
[   86.842235]     names, then host name confusion attack is possible.
[   86.938198] [tempesta fw] Configuration processing is completed.
[   86.968340] [tdb] Opened table /opt/tempesta/db/filter0.tdb: size=16777216 rec_size=20 base=00000000f8eece80
[   86.976854] [tdb] Opened table /opt/tempesta/db/sessions0.tdb: size=16777216 rec_size=312 base=000000002b7c57f2
[   86.986163] [tdb] Opened table /opt/tempesta/db/client0.tdb: size=16777216 rec_size=624 base=00000000dda0b532
[   87.062160] [tempesta fw] Open listen socket on: 0.0.0.0:443
[   87.126153] [tempesta fw] Tempesta FW is ready
[   92.839461] curl: page allocation failure: order:2, mode:0xa20(GFP_ATOMIC), nodemask=(null),cpuset=user.slice,mems_allowed=0
[   92.840647] CPU: 4 PID: 8941 Comm: curl Tainted: G           OE     5.10.35.tfw-4c9ba16 #1
[   92.841525] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.15.0-1 04/01/2014
[   92.842518] Call Trace:
[   92.843100]  <IRQ>
[   92.843672]  dump_stack+0x74/0x92
[   92.844316]  warn_alloc.cold+0x7b/0xdf
[   92.844988]  __alloc_pages_slowpath.constprop.0+0xd2e/0xd60
[   92.845772]  __alloc_pages_nodemask+0x2cf/0x330
[   92.846483]  alloc_pages_current+0x87/0xe0
[   92.847201]  ss_skb_to_sgvec_with_new_pages+0x91/0x290 [tempesta_fw]
[   92.848031]  tfw_tls_encrypt+0x38e/0x8a0 [tempesta_fw]
[   92.848759]  ? memcpy_fast+0xe/0x10 [tempesta_lib]
[   92.849464]  ? tfw_strcpy+0x1ae/0x2b0 [tempesta_fw]
[   92.850184]  ? tfw_h2_insert_frame_header+0x19b/0x1c0 [tempesta_fw]
[   92.850970]  ? tso_fragment+0x149/0x200
[   92.851592]  ? tfw_sk_prepare_xmit+0x358/0x780 [tempesta_fw]
[   92.852331]  tfw_sk_write_xmit+0x6a/0xc0 [tempesta_fw]
[   92.853037]  tcp_tfw_sk_write_xmit+0x36/0x80
[   92.853697]  tcp_write_xmit+0x2a9/0x11b0
[   92.854331]  __tcp_push_pending_frames+0x37/0x100
[   92.854997]  tcp_rcv_established+0x26c/0x670
[   92.855635]  ? sk_filter_trim_cap+0xde/0x240
[   92.856269]  tcp_v4_do_rcv+0x140/0x200
[   92.856897]  tcp_v4_rcv+0xcfd/0xe10
[   92.857502]  ip_protocol_deliver_rcu+0x30/0x1b0
[   92.858166]  ip_local_deliver_finish+0x48/0x60
[   92.858797]  ip_local_deliver+0xfa/0x110
[   92.859442]  ? ip_protocol_deliver_rcu+0x1b0/0x1b0
[   92.860092]  ip_rcv_finish+0x87/0xa0
[   92.860666]  ip_rcv+0xcc/0xe0
[   92.861198]  ? ip_rcv_finish_core.isra.0+0x420/0x420
[   92.861886]  __netif_receive_skb_one_core+0x88/0xa0
[   92.862539]  __netif_receive_skb+0x18/0x60
[   92.863137]  process_backlog+0xa9/0x160
[   92.863721]  net_rx_action+0x13e/0x390
[   92.864383]  ? rcu_core+0xfa/0x500
[   92.864997]  __do_softirq+0xd9/0x291
[   92.865657]  asm_call_irq_on_stack+0xf/0x20
[   92.866301]  </IRQ>
[   92.866758]  do_softirq_own_stack+0x3d/0x50
[   92.867396]  do_softirq.part.0+0x46/0x50
[   92.867955]  __local_bh_enable_ip+0x50/0x60
[   92.868520]  ip_finish_output2+0x1ab/0x590
[   92.869085]  ? __cgroup_bpf_run_filter_skb+0x3c3/0x3d0
[   92.869721]  __ip_finish_output+0xd8/0x220
[   92.870330]  ip_finish_output+0x2d/0xb0
[   92.870858]  ip_output+0x7a/0x100
[   92.871341]  ? __ip_finish_output+0x220/0x220
[   92.871898]  ip_local_out+0x3d/0x50
[   92.872372]  __ip_queue_xmit+0x17a/0x470
[   92.872878]  ? _copy_to_iter+0xa0/0x460
[   92.873381]  ip_queue_xmit+0x15/0x20
[   92.873890]  __tcp_transmit_skb+0xa20/0xbe0
[   92.874408]  __tcp_send_ack.part.0+0xcb/0x1a0
[   92.874933]  tcp_send_ack+0x1c/0x20
[   92.875403]  tcp_cleanup_rbuf+0x7c/0x100
[   92.875898]  tcp_recvmsg+0x258/0xae0
[   92.876374]  ? _cond_resched+0x19/0x30
[   92.876852]  ? __release_sock+0x8d/0xc0
[   92.877363]  inet_recvmsg+0x5f/0x110
[   92.877858]  sock_recvmsg+0x69/0x80
[   92.878311]  sock_read_iter+0x8f/0xf0
[   92.878776]  new_sync_read+0x183/0x1a0
[   92.879256]  vfs_read+0xfe/0x190
[   92.879717]  ksys_read+0xb1/0xe0
[   92.880141]  __x64_sys_read+0x1a/0x20
[   92.880591]  do_syscall_64+0x38/0x90
[   92.881034]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   92.881570] RIP: 0033:0x7fbb366df992
[   92.882044] Code: c0 e9 b2 fe ff ff 50 48 8d 3d fa b2 0c 00 e8 c5 1d 02 00 0f 1f 44 00 00 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 0f 05 <48> 3d 00 f0 ff ff 77 56 c3 0f 1f 44 00 00 48 83 ec 28 48 89 54 24
[   92.883671] RSP: 002b:00007ffdd44d8d98 EFLAGS: 00000246 ORIG_RAX: 0000000000000000
[   92.884421] RAX: ffffffffffffffda RBX: 00000000000034f6 RCX: 00007fbb366df992
[   92.885140] RDX: 00000000000034f6 RSI: 0000562298c146d8 RDI: 0000000000000010
[   92.885875] RBP: 0000562298ccd1c0 R08: 0000000000000001 R09: 00007ffdd44d8f78
[   92.886577] R10: 0000000000000000 R11: 0000000000000246 R12: 0000562298c146d8
[   92.887280] R13: 00007fbb360b66c0 R14: 0000562298cce330 R15: 00007ffdd44d8f78
[   92.888025] Mem-Info:
[   92.888414] active_anon:347 inactive_anon:210490 isolated_anon:0
[   92.888414]  active_file:29412 inactive_file:24533 isolated_file:0
[   92.888414]  unevictable:0 dirty:70 writeback:0
[   92.888414]  slab_reclaimable:12694 slab_unreclaimable:16577
[   92.888414]  mapped:38967 shmem:5417 pagetables:3618 bounce:0
[   92.888414]  free:493927 free_pcp:720 free_cma:0
[   92.894751] Node 0 active_anon:1388kB inactive_anon:841960kB active_file:117820kB inactive_file:98132kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:156040kB dirty:796kB writeback:0kB shmem:21668kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB kernel_stack:7472kB all_unreclaimable? yes
[   92.899358] Node 0 DMA free:14876kB min:132kB low:164kB high:196kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[   92.904089] lowmem_reserve[]: 0 1917 7877 7877 7877
[   92.905228] Node 0 DMA32 free:629168kB min:53352kB low:57456kB high:61560kB reserved_highatomic:0KB active_anon:0kB inactive_anon:2172kB active_file:1192kB inactive_file:232kB unevictable:0kB writepending:0kB present:2080620kB managed:2015084kB mlocked:0kB pagetables:0kB bounce:0kB free_pcp:776kB local_pcp:776kB free_cma:0kB
[   92.910180] lowmem_reserve[]: 0 0 5960 5960 5960
[   92.911321] Node 0 Normal free:1331160kB min:165848kB low:178604kB high:191360kB reserved_highatomic:0KB active_anon:1388kB inactive_anon:839788kB active_file:116628kB inactive_file:98072kB unevictable:0kB writepending:1056kB present:6291456kB managed:6118840kB mlocked:0kB pagetables:14472kB bounce:0kB free_pcp:2112kB local_pcp:1292kB free_cma:0kB
[   92.916695] lowmem_reserve[]: 0 0 0 0 0
[   92.917867] Node 0 DMA: 1*4kB (U) 1*8kB (U) 1*16kB (U) 0*32kB 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 0*1024kB 1*2048kB (M) 3*4096kB (M) = 14876kB
[   92.920737] Node 0 DMA32: 156867*4kB (U) 234*8kB (U) 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 629340kB
[   92.923653] Node 0 Normal: 329418*4kB (UME) 1553*8kB (UME) 0*16kB 1*32kB (U) 0*64kB 0*128kB 0*256kB 0*512kB 1*1024kB (U) 0*2048kB 0*4096kB = 1331152kB
[   92.926766] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[   92.928510] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[   92.930268] 59495 total pagecache pages
[   92.931516] 0 pages in swap cache
[   92.932669] Swap cache stats: add 0, delete 0, find 0/0
[   92.933961] Free swap  = 2097148kB
[   92.934707] Total swap = 2097148kB
[   92.935377] 2097017 pages RAM
[   92.936015] 0 pages HighMem/MovableOnly
[   92.936716] 59559 pages reserved
[   92.937371] 0 pages cma reserved
[   92.938113] 0 pages hwpoisoned
[   92.938766] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[   92.940725] [tempesta fw] HTTP/2 connection is closed by client with error code: 1, ID of last processed stream: 0
[   92.960060] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[   92.962933] [tempesta fw] HTTP/2 connection is closed by client with error code: 1, ID of last processed stream: 0
[   92.993120] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[   92.996568] [tempesta fw] HTTP/2 connection is closed by client with error code: 1, ID of last processed stream: 0
[   93.050400] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[   93.052736] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[   93.054942] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[   93.056902] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[   93.530148] ------------[ cut here ]------------
[   93.530988] kernel BUG at mm/slub.c:304!
[   93.531680] invalid opcode: 0000 [#1] SMP NOPTI
[   93.532391] CPU: 1 PID: 8941 Comm: curl Tainted: G           OE     5.10.35.tfw-4c9ba16 #1
[   93.533409] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.15.0-1 04/01/2014
[   93.534584] RIP: 0010:kmem_cache_free+0x3fa/0x410
[   93.535422] Code: 83 28 01 0f 85 69 fe ff ff 49 8b 46 08 4c 89 f7 48 8b 40 08 e8 d7 50 b3 00 e9 54 fe ff ff 48 89 8f 80 00 00 00 e9 14 fe ff ff <0f> 0b 48 8b 05 ad 5d 34 01 41 be 01 00 00 00 e9 2b fc ff ff 66 90
[   93.537792] RSP: 0018:ffffb21c800e8b80 EFLAGS: 00010246
[   93.538655] RAX: ffff9cf54dd888a0 RBX: ffff9cf54dd888a0 RCX: ffff9cf54dd88cf0
[   93.539627] RDX: 000000000000000b RSI: 0000000000000000 RDI: ffff9cf667cc1b00
[   93.540597] RBP: ffffb21c800e8bb0 R08: 0000000000000000 R09: 0000000000000000
[   93.541621] R10: dead0000000000ff R11: 0000000000000000 R12: ffffe3ee80376200
[   93.542661] R13: ffffe3ee80376200 R14: 0000000000000000 R15: ffff9cf667cc1b00
[   93.543651] FS:  00007fbb360b6740(0000) GS:ffff9cf7b7c40000(0000) knlGS:0000000000000000
[   93.544701] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   93.545593] CR2: 00007ff53d650000 CR3: 00000001924ae003 CR4: 0000000000770ee0
[   93.546550] PKRU: 55555554
[   93.547173] Call Trace:
[   93.547765]  <IRQ>
[   93.548332]  ? tfw_cli_conn_free+0xb5/0xd0 [tempesta_fw]
[   93.549108]  tfw_cli_conn_free+0xb5/0xd0 [tempesta_fw]
[   93.549924]  tfw_sock_clnt_new+0x2a8/0x320 [tempesta_fw]
[   93.550776]  ss_tcp_state_change+0xed/0x250 [tempesta_fw]
[   93.551538]  tcp_rcv_state_process+0xb7d/0xf90
[   93.552214]  ? inet_csk_complete_hashdance+0x44/0xc0
[   93.552909]  ? tcp_check_req+0x189/0x550
[   93.553538]  tcp_child_process+0xa5/0x1a0
[   93.554207]  tcp_v4_rcv+0xa1e/0xe10
[   93.554804]  ip_protocol_deliver_rcu+0x30/0x1b0
[   93.555475]  ip_local_deliver_finish+0x48/0x60
[   93.556126]  ip_local_deliver+0xfa/0x110
[   93.556744]  ? ip_protocol_deliver_rcu+0x1b0/0x1b0
[   93.557485]  ip_rcv_finish+0x87/0xa0
[   93.558143]  ip_rcv+0xcc/0xe0
[   93.558755]  ? ip_rcv_finish_core.isra.0+0x420/0x420
[   93.559524]  __netif_receive_skb_one_core+0x88/0xa0
[   93.560223]  __netif_receive_skb+0x18/0x60
[   93.560854]  process_backlog+0xa9/0x160
[   93.561469]  net_rx_action+0x13e/0x390
[   93.562111]  __do_softirq+0xd9/0x291
[   93.562695]  asm_call_irq_on_stack+0xf/0x20
[   93.563346]  </IRQ>
[   93.563811]  do_softirq_own_stack+0x3d/0x50
[   93.564399]  do_softirq.part.0+0x46/0x50
[   93.565022]  __local_bh_enable_ip+0x50/0x60
[   93.565665]  ip_finish_output2+0x1ab/0x590
[   93.566283]  ? __cgroup_bpf_run_filter_skb+0x3c3/0x3d0
[   93.567005]  __ip_finish_output+0xd8/0x220
[   93.567642]  ip_finish_output+0x2d/0xb0
[   93.568227]  ip_output+0x7a/0x100
[   93.568766]  ? __ip_finish_output+0x220/0x220
[   93.569364]  ip_local_out+0x3d/0x50
[   93.569942]  __ip_queue_xmit+0x17a/0x470
[   93.570495]  ? tcp_get_metrics+0x232/0x2d0
[   93.571047]  ip_queue_xmit+0x15/0x20
[   93.571558]  __tcp_transmit_skb+0xa20/0xbe0
[   93.572179]  __tcp_send_ack.part.0+0xcb/0x1a0
[   93.572734]  tcp_send_ack+0x1c/0x20
[   93.573236]  tcp_rcv_state_process+0xd21/0xf90
[   93.573828]  tcp_v4_do_rcv+0xc4/0x200
[   93.574336]  __release_sock+0x7b/0xc0
[   93.574892]  release_sock+0x30/0xa0
[   93.575393]  inet_stream_connect+0x47/0x60
[   93.575974]  __sys_connect_file+0x5f/0x70
[   93.576493]  __sys_connect+0xa0/0xd0
[   93.576988]  ? do_fcntl+0x1c9/0x680
[   93.577479]  ? exit_to_user_mode_prepare+0x3d/0x170
[   93.578066]  __x64_sys_connect+0x1a/0x20
[   93.578580]  do_syscall_64+0x38/0x90
[   93.579086]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   93.579673] RIP: 0033:0x7fbb366f26a7
[   93.580162] Code: 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 b8 2a 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 51 c3 48 83 ec 18 89 54 24 0c 48 89 34 24 89
[   93.581923] RSP: 002b:00007ffdd44d8d98 EFLAGS: 00000246 ORIG_RAX: 000000000000002a
[   93.582691] RAX: ffffffffffffffda RBX: 0000000000000001 RCX: 00007fbb366f26a7
[   93.583556] RDX: 0000000000000010 RSI: 00007ffdd44d8f20 RDI: 000000000000003a
[   93.584366] RBP: 0000562298d313d0 R08: 000000000000005d R09: 000000000000005d
[   93.585133] R10: 00007ffdd4522000 R11: 0000000000000246 R12: 0000562298cdf140
[   93.585967] R13: 0000000000000000 R14: 000000000000003a R15: 0000000000000000
[   93.586739] Modules linked in: tempesta_fw(OE) tempesta_db(OE) tempesta_tls(OE) tempesta_lib(OE) tls tcp_diag inet_diag sha256_ssse3 sha512_ssse3 xt_nat xt_tcpudp veth xt_conntrack nft_chain_nat xt_MASQUERADE nf_nat nf_conntrack_netlink nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 xfrm_user xfrm_algo nft_counter xt_addrtype nft_compat nf_tables libcrc32c nfnetlink br_netfilter bridge stp llc overlay binfmt_misc snd_hda_codec_generic ledtrig_audio snd_hda_intel intel_rapl_msr snd_intel_dspcfg intel_rapl_common snd_hda_codec kvm_intel snd_hda_core snd_hwdep snd_pcm kvm snd_seq_midi snd_seq_midi_event input_leds crct10dif_pclmul ghash_clmulni_intel nls_iso8859_1 serio_raw snd_rawmidi aesni_intel snd_seq crypto_simd cryptd glue_helper snd_seq_device snd_timer joydev snd qxl drm_ttm_helper soundcore ttm drm_kms_helper cec fb_sys_fops syscopyarea sysfillrect sysimgblt mac_hid qemu_fw_cfg sch_fq_codel msr parport_pc ppdev lp efi_pstore ramoops parport reed_solomon drm ip_tables x_tables autofs4
[   93.586791]  hid_generic usbhid hid virtio_net net_failover failover i2c_i801 ahci crc32_pclmul i2c_smbus psmouse lpc_ich libahci virtio_rng virtio_blk [last unloaded: tempesta_lib]
[   93.597399] ---[ end trace 0c38fa2adc1507c1 ]---
[   93.598201] RIP: 0010:kmem_cache_free+0x3fa/0x410
[   93.600910] Code: 83 28 01 0f 85 69 fe ff ff 49 8b 46 08 4c 89 f7 48 8b 40 08 e8 d7 50 b3 00 e9 54 fe ff ff 48 89 8f 80 00 00 00 e9 14 fe ff ff <0f> 0b 48 8b 05 ad 5d 34 01 41 be 01 00 00 00 e9 2b fc ff ff 66 90
[   93.603787] RSP: 0018:ffffb21c800e8b80 EFLAGS: 00010246
[   93.604539] RAX: ffff9cf54dd888a0 RBX: ffff9cf54dd888a0 RCX: ffff9cf54dd88cf0
[   93.605415] RDX: 000000000000000b RSI: 0000000000000000 RDI: ffff9cf667cc1b00
[   93.606405] RBP: ffffb21c800e8bb0 R08: 0000000000000000 R09: 0000000000000000
[   93.607262] R10: dead0000000000ff R11: 0000000000000000 R12: ffffe3ee80376200
[   93.608110] R13: ffffe3ee80376200 R14: 0000000000000000 R15: ffff9cf667cc1b00
[   93.608969] FS:  00007fbb360b6740(0000) GS:ffff9cf7b7c40000(0000) knlGS:0000000000000000
[   93.610080] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   93.610847] CR2: 00007ff53d650000 CR3: 00000001924ae003 CR4: 0000000000770ee0
[   93.611723] PKRU: 55555554
[   93.612285] Kernel panic - not syncing: Fatal exception in interrupt
[   93.613226] Kernel Offset: 0x13800000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[   93.614384] Rebooting in 1 seconds..
[   94.607240] ACPI MEMORY or I/O RESET_REG.
```

and second:

```python3
[  542.428504] Start test: t_stress.test_wordpress.H2WordpressStress.test_get_large_images
[  542.985649] docker0: port 1(vethd023122) entered blocking state
[  542.986523] docker0: port 1(vethd023122) entered disabled state
[  542.987273] device vethd023122 entered promiscuous mode
[  542.988024] docker0: port 1(vethd023122) entered blocking state
[  542.988730] docker0: port 1(vethd023122) entered forwarding state
[  542.990684] docker0: port 1(vethd023122) entered disabled state
[  543.158538] eth0: renamed from veth33800b8
[  543.182590] IPv6: ADDRCONF(NETDEV_CHANGE): vethd023122: link becomes ready
[  543.183528] docker0: port 1(vethd023122) entered blocking state
[  543.184400] docker0: port 1(vethd023122) entered forwarding state
[  543.357550] [tdb] Start Tempesta DB
[  543.417697] [tempesta fw] Initializing Tempesta FW kernel module...
[  543.486191] [tempesta fw] Warning: Vhost default doesn't have certificate with matching SAN/CN.
[  543.486191]     Maybe that's fine, but it's worth checking the
[  543.486191]     config - if there is no relations between the
[  543.486191]     names, then host name confusion attack is possible.
[  543.578211] [tempesta fw] Configuration processing is completed.
[  543.607346] [tdb] Opened table /opt/tempesta/db/filter0.tdb: size=16777216 rec_size=20 base=000000004243b104
[  543.616554] [tdb] Opened table /opt/tempesta/db/sessions0.tdb: size=16777216 rec_size=312 base=000000007df44b97
[  543.624105] [tdb] Opened table /opt/tempesta/db/client0.tdb: size=16777216 rec_size=624 base=00000000ce6787ec
[  543.718545] [tempesta fw] Open listen socket on: 0.0.0.0:443
[  543.786225] [tempesta fw] Tempesta FW is ready
[  550.722813] curl: page allocation failure: order:2, mode:0xa20(GFP_ATOMIC), nodemask=(null),cpuset=user.slice,mems_allowed=0
[  550.724042] CPU: 2 PID: 14004 Comm: curl Tainted: G           OE     5.10.35.tfw-4c9ba16 #1
[  550.724912] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.15.0-1 04/01/2014
[  550.725762] Call Trace:
[  550.726322]  <IRQ>
[  550.726856]  dump_stack+0x74/0x92
[  550.727483]  warn_alloc.cold+0x7b/0xdf
[  550.728113]  __alloc_pages_slowpath.constprop.0+0xd2e/0xd60
[  550.728841]  __alloc_pages_nodemask+0x2cf/0x330
[  550.729506]  alloc_pages_current+0x87/0xe0
[  550.730155]  ss_skb_to_sgvec_with_new_pages+0x91/0x290 [tempesta_fw]
[  550.730994]  tfw_tls_encrypt+0x38e/0x8a0 [tempesta_fw]
[  550.731719]  ? memcpy_fast+0xe/0x10 [tempesta_lib]
[  550.732407]  ? tfw_strcpy+0x1ae/0x2b0 [tempesta_fw]
[  550.733098]  ? __alloc_pages_nodemask+0x193/0x330
[  550.733847]  ? tso_fragment+0x149/0x200
[  550.734534]  ? tfw_sk_prepare_xmit+0x358/0x780 [tempesta_fw]
[  550.735263]  tfw_sk_write_xmit+0x6a/0xc0 [tempesta_fw]
[  550.735990]  tcp_tfw_sk_write_xmit+0x36/0x80
[  550.736626]  tcp_write_xmit+0x2a9/0x11b0
[  550.737238]  __tcp_push_pending_frames+0x37/0x100
[  550.737897]  tcp_rcv_established+0x26c/0x670
[  550.738552]  ? sk_filter_trim_cap+0xde/0x240
[  550.739180]  tcp_v4_do_rcv+0x140/0x200
[  550.739812]  tcp_v4_rcv+0xcfd/0xe10
[  550.740443]  ip_protocol_deliver_rcu+0x30/0x1b0
[  550.741096]  ip_local_deliver_finish+0x48/0x60
[  550.741743]  ip_local_deliver+0xfa/0x110
[  550.742380]  ? ip_protocol_deliver_rcu+0x1b0/0x1b0
[  550.743041]  ip_rcv_finish+0x87/0xa0
[  550.743633]  ip_rcv+0xcc/0xe0
[  550.744187]  ? ip_rcv_finish_core.isra.0+0x420/0x420
[  550.744853]  __netif_receive_skb_one_core+0x88/0xa0
[  550.745499]  __netif_receive_skb+0x18/0x60
[  550.746116]  process_backlog+0xa9/0x160
[  550.746718]  net_rx_action+0x13e/0x390
[  550.747312]  ? try_to_wake_up+0x1dc/0x510
[  550.747957]  __do_softirq+0xd9/0x291
[  550.748515]  asm_call_irq_on_stack+0xf/0x20
[  550.749097]  </IRQ>
[  550.749552]  do_softirq_own_stack+0x3d/0x50
[  550.750130]  do_softirq.part.0+0x46/0x50
[  550.750717]  __local_bh_enable_ip+0x50/0x60
[  550.751297]  ip_finish_output2+0x1ab/0x590
[  550.751868]  ? __cgroup_bpf_run_filter_skb+0x3c3/0x3d0
[  550.752472]  __ip_finish_output+0xd8/0x220
[  550.753004]  ip_finish_output+0x2d/0xb0
[  550.753536]  ip_output+0x7a/0x100
[  550.754020]  ? __ip_finish_output+0x220/0x220
[  550.754569]  ip_local_out+0x3d/0x50
[  550.755033]  __ip_queue_xmit+0x17a/0x470
[  550.755549]  ? _copy_to_iter+0xa0/0x460
[  550.756032]  ip_queue_xmit+0x15/0x20
[  550.756499]  __tcp_transmit_skb+0xa20/0xbe0
[  550.757004]  __tcp_send_ack.part.0+0xcb/0x1a0
[  550.757516]  tcp_send_ack+0x1c/0x20
[  550.757975]  tcp_cleanup_rbuf+0x7c/0x100
[  550.758486]  tcp_recvmsg+0x258/0xae0
[  550.758946]  ? _cond_resched+0x19/0x30
[  550.759416]  ? __release_sock+0x8d/0xc0
[  550.759915]  inet_recvmsg+0x5f/0x110
[  550.760367]  sock_recvmsg+0x69/0x80
[  550.760822]  sock_read_iter+0x8f/0xf0
[  550.761280]  new_sync_read+0x183/0x1a0
[  550.761738]  vfs_read+0xfe/0x190
[  550.762158]  ksys_read+0xb1/0xe0
[  550.762605]  __x64_sys_read+0x1a/0x20
[  550.763048]  do_syscall_64+0x38/0x90
[  550.763511]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  550.764064] RIP: 0033:0x7f6da5be6992
[  550.764525] Code: c0 e9 b2 fe ff ff 50 48 8d 3d fa b2 0c 00 e8 c5 1d 02 00 0f 1f 44 00 00 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 0f 05 <48> 3d 00 f0 ff ff 77 56 c3 0f 1f 44 00 00 48 83 ec 28 48 89 54 24
[  550.766170] RSP: 002b:00007fff9fc08c38 EFLAGS: 00000246 ORIG_RAX: 0000000000000000
[  550.766912] RAX: ffffffffffffffda RBX: 00000000000024f6 RCX: 00007f6da5be6992
[  550.767644] RDX: 00000000000024f6 RSI: 000055dd78909218 RDI: 0000000000000010
[  550.768447] RBP: 000055dd787bc1c0 R08: 0000000000000001 R09: 00007fff9fc08e18
[  550.769374] R10: 0000000000000000 R11: 0000000000000246 R12: 000055dd78909218
[  550.770244] R13: 00007f6da55bd6c0 R14: 000055dd787bd330 R15: 00007fff9fc08e18
[  550.771042] Mem-Info:
[  550.771434] active_anon:357 inactive_anon:211228 isolated_anon:0
[  550.771434]  active_file:29256 inactive_file:27406 isolated_file:0
[  550.771434]  unevictable:0 dirty:55 writeback:0
[  550.771434]  slab_reclaimable:11882 slab_unreclaimable:17009
[  550.771434]  mapped:40107 shmem:5419 pagetables:3603 bounce:0
[  550.771434]  free:459849 free_pcp:555 free_cma:0
[  550.776225] Node 0 active_anon:1428kB inactive_anon:844912kB active_file:117024kB inactive_file:109624kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:160428kB dirty:736kB writeback:0kB shmem:21676kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB kernel_stack:7664kB all_unreclaimable? yes
[  550.780107] Node 0 DMA free:14876kB min:132kB low:164kB high:196kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[  550.783882] lowmem_reserve[]: 0 1917 7877 7877 7877
[  550.784674] Node 0 DMA32 free:569416kB min:16416kB low:20520kB high:24624kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:2080620kB managed:2015084kB mlocked:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[  550.788685] lowmem_reserve[]: 0 0 5960 5960 5960
[  550.789482] Node 0 Normal free:1255104kB min:165848kB low:178604kB high:191360kB reserved_highatomic:0KB active_anon:1428kB inactive_anon:844912kB active_file:117024kB inactive_file:109624kB unevictable:0kB writepending:988kB present:6291456kB managed:6118840kB mlocked:0kB pagetables:14412kB bounce:0kB free_pcp:2056kB local_pcp:1312kB free_cma:0kB
[  550.793817] lowmem_reserve[]: 0 0 0 0 0
[  550.794687] Node 0 DMA: 1*4kB (U) 1*8kB (U) 1*16kB (U) 0*32kB 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 0*1024kB 1*2048kB (M) 3*4096kB (M) = 14876kB
[  550.796774] Node 0 DMA32: 142372*4kB (U) 4*8kB (U) 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 569520kB
[  550.798870] Node 0 Normal: 312290*4kB (UME) 747*8kB (UME) 2*16kB (U) 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 1255168kB
[  550.800940] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[  550.802244] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[  550.803632] 62095 total pagecache pages
[  550.804436] 2 pages in swap cache
[  550.805205] Swap cache stats: add 2, delete 0, find 0/0
[  550.806131] Free swap  = 2097136kB
[  550.806975] Total swap = 2097148kB
[  550.807692] 2097017 pages RAM
[  550.808336] 0 pages HighMem/MovableOnly
[  550.809029] 59559 pages reserved
[  550.809672] 0 pages cma reserved
[  550.810376] 0 pages hwpoisoned
[  550.810987] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[  550.812695] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[  550.814968] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[  550.816199] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[  550.819108] [tempesta fw] HTTP/2 connection is closed by client with error code: 1, ID of last processed stream: 0
[  550.821035] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[  550.827619] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[  550.844771] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[  550.847125] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[  550.849449] [tempesta fw] Warning: tfw_tls_encrypt: cannot encrypt data (-12), only partial data was sent
[  551.549513] BUG: kernel NULL pointer dereference, address: 00000000000002e8
[  551.550614] #PF: supervisor write access in kernel mode
[  551.551527] #PF: error_code(0x0002) - not-present page
[  551.552436] PGD 126a08067 P4D 126a08067 PUD 192d30067 PMD 0 
[  551.553517] Oops: 0002 [#1] SMP NOPTI
[  551.554257] CPU: 2 PID: 12166 Comm: docker-proxy Tainted: G           OE     5.10.35.tfw-4c9ba16 #1
[  551.555346] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.15.0-1 04/01/2014
[  551.556412] RIP: 0010:tfw_h2_resp_adjust_fwd+0x526/0x720 [tempesta_fw]
[  551.557315] Code: 00 00 00 8b 8d d4 fe ff ff 80 48 10 01 66 83 48 12 08 89 48 14 48 8b 00 48 39 c3 75 ec 49 8b 45 38 be 08 00 00 00 48 8b 78 40 <48> 89 97 e8 02 00 00 48 81 c7 f8 02 00 00 4c 89 7f f8 e8 e3 3e d8
[  551.559568] RSP: 0018:ffffad8e4011c8b0 EFLAGS: 00010246
[  551.560423] RAX: ffff9821e037c020 RBX: ffff982190a9c000 RCX: 0000000000000007
[  551.561359] RDX: 0000000000000009 RSI: 0000000000000008 RDI: 0000000000000000
[  551.562289] RBP: ffffad8e4011c9f8 R08: ffffad8e4011c7e4 R09: ffff9821d2a4c010
[  551.563206] R10: 0000000000000000 R11: ffff9821d2a4c020 R12: ffff9821e037c020
[  551.564140] R13: ffff9821d2a4c020 R14: 0000000000000000 R15: 00000000009d59e2
[  551.565045] FS:  00007efd4d544640(0000) GS:ffff9822b7c80000(0000) knlGS:0000000000000000
[  551.566029] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  551.566832] CR2: 00000000000002e8 CR3: 0000000127bb6003 CR4: 0000000000770ee0
[  551.567735] PKRU: 55555554
[  551.568344] Call Trace:
[  551.568907]  <IRQ>
[  551.569442]  tfw_http_resp_cache_cb+0x33/0x2f0 [tempesta_fw]
[  551.570199]  ? tfw_h2_resp_adjust_fwd+0x720/0x720 [tempesta_fw]
[  551.570959]  tfw_cache_process+0x14a/0x2a0 [tempesta_fw]
[  551.571713]  ? tfw_gfsm_move+0x19c/0x220 [tempesta_fw]
[  551.572406]  tfw_http_resp_cache+0x101/0x1b0 [tempesta_fw]
[  551.573152]  tfw_http_msg_process_generic+0x5a0/0x6e0 [tempesta_fw]
[  551.574098]  ? __coalesce_frag+0x99/0x150 [tempesta_fw]
[  551.574877]  tfw_http_msg_process+0x3e/0x60 [tempesta_fw]
[  551.575667]  tfw_connection_recv+0x87/0x110 [tempesta_fw]
[  551.576422]  ? ss_skb_unroll+0xce/0x270 [tempesta_fw]
[  551.577140]  ss_tcp_process_data+0x1ec/0x3f0 [tempesta_fw]
[  551.577880]  ss_tcp_data_ready+0x44/0xe0 [tempesta_fw]
[  551.578598]  tcp_data_ready+0x2b/0xd0
[  551.579199]  tcp_rcv_established+0x5a7/0x670
[  551.579895]  tcp_v4_do_rcv+0x140/0x200
[  551.580537]  tcp_v4_rcv+0xcfd/0xe10
[  551.581153]  ip_protocol_deliver_rcu+0x30/0x1b0
[  551.581839]  ip_local_deliver_finish+0x48/0x60
[  551.582510]  ip_local_deliver+0xfa/0x110
[  551.583135]  ? ip_protocol_deliver_rcu+0x1b0/0x1b0
[  551.583838]  ip_rcv_finish+0x87/0xa0
[  551.584424]  ip_rcv+0xcc/0xe0
[  551.584973]  ? ip_rcv_finish_core.isra.0+0x420/0x420
[  551.585666]  __netif_receive_skb_one_core+0x88/0xa0
[  551.586372]  __netif_receive_skb+0x18/0x60
[  551.587012]  process_backlog+0xa9/0x160
[  551.587656]  net_rx_action+0x13e/0x390
[  551.588266]  ? ttwu_do_activate+0xb2/0x3e0
[  551.588901]  __do_softirq+0xd9/0x291
[  551.589495]  asm_call_irq_on_stack+0xf/0x20
[  551.590132]  </IRQ>
[  551.590616]  do_softirq_own_stack+0x3d/0x50
[  551.591242]  do_softirq.part.0+0x46/0x50
[  551.591847]  __local_bh_enable_ip+0x50/0x60
[  551.592453]  ip_finish_output2+0x1ab/0x590
[  551.593037]  ? __cgroup_bpf_run_filter_skb+0x3c3/0x3d0
[  551.593708]  __ip_finish_output+0xd8/0x220
[  551.594304]  ip_finish_output+0x2d/0xb0
[  551.594864]  ip_output+0x7a/0x100
[  551.595393]  ? __ip_finish_output+0x220/0x220
[  551.595984]  ip_local_out+0x3d/0x50
[  551.596512]  __ip_queue_xmit+0x17a/0x470
[  551.597076]  ? lock_timer_base+0x72/0xa0
[  551.597622]  ip_queue_xmit+0x15/0x20
[  551.598141]  __tcp_transmit_skb+0xa20/0xbe0
[  551.598697]  tcp_write_xmit+0x2cc/0x11b0
[  551.599237]  __tcp_push_pending_frames+0x37/0x100
[  551.599839]  tcp_push+0xfc/0x100
[  551.600344]  do_tcp_sendpages+0x5d2/0x640
[  551.600887]  tcp_sendpage_locked+0x43/0x60
[  551.601437]  tcp_sendpage+0x3c/0x60
[  551.601939]  inet_sendpage+0x56/0xa0
[  551.602447]  kernel_sendpage+0x57/0xc0
[  551.602962]  ? _raw_spin_unlock_bh+0x1e/0x20
[  551.603517]  sock_sendpage+0x24/0x30
[  551.604017]  pipe_to_sendpage+0x61/0xa0
[  551.604536]  __splice_from_pipe+0xa9/0x1c0
[  551.605069]  ? propagate_umount+0x4f0/0x4f0
[  551.605606]  ? propagate_umount+0x4f0/0x4f0
[  551.606141]  splice_from_pipe+0x5f/0x90
[  551.606645]  generic_splice_sendpage+0x15/0x20
[  551.607194]  do_splice+0x2fc/0x670
[  551.607799]  __do_splice+0xde/0x160
[  551.608311]  __x64_sys_splice+0x99/0x110
[  551.608883]  do_syscall_64+0x38/0x90
[  551.609373]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  551.609972] RIP: 0033:0x4840ea
[  551.610429] Code: e8 3b ee fd ff 48 8b 7c 24 10 48 8b 74 24 18 48 8b 54 24 20 4c 8b 54 24 28 4c 8b 44 24 30 4c 8b 4c 24 38 48 8b 44 24 08 0f 05 <48> 3d 01 f0 ff ff 76 20 48 c7 44 24 40 ff ff ff ff 48 c7 44 24 48
[  551.612262] RSP: 002b:000000c0000b7468 EFLAGS: 00000216 ORIG_RAX: 0000000000000113
[  551.613064] RAX: ffffffffffffffda RBX: 000000c00002b400 RCX: 00000000004840ea
[  551.613847] RDX: 0000000000000083 RSI: 0000000000000000 RDI: 000000000000009d
[  551.614662] RBP: 000000c0000b74d8 R08: 0000000000009b00 R09: 0000000000000002
[  551.615451] R10: 0000000000000000 R11: 0000000000000216 R12: 000000c0000b7568
[  551.616288] R13: 0000000000000000 R14: 000000c0001ef1e0 R15: ffffffffffffffff
[  551.617067] Modules linked in: tempesta_fw(OE) tempesta_db(OE) tempesta_tls(OE) tempesta_lib(OE) tls tcp_diag inet_diag sha256_ssse3 sha512_ssse3 xt_nat xt_tcpudp veth xt_conntrack nft_chain_nat xt_MASQUERADE nf_nat nf_conntrack_netlink nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 xfrm_user xfrm_algo nft_counter xt_addrtype nft_compat nf_tables libcrc32c nfnetlink br_netfilter bridge stp llc overlay snd_hda_codec_generic ledtrig_audio snd_hda_intel snd_intel_dspcfg snd_hda_codec binfmt_misc snd_hda_core snd_hwdep intel_rapl_msr intel_rapl_common snd_pcm kvm_intel snd_seq_midi snd_seq_midi_event snd_rawmidi kvm crct10dif_pclmul ghash_clmulni_intel aesni_intel crypto_simd cryptd glue_helper nls_iso8859_1 snd_seq joydev snd_seq_device snd_timer snd input_leds qxl serio_raw mac_hid drm_ttm_helper ttm drm_kms_helper soundcore cec fb_sys_fops syscopyarea sysfillrect sysimgblt qemu_fw_cfg sch_fq_codel msr parport_pc drm ppdev lp parport ramoops reed_solomon efi_pstore ip_tables x_tables autofs4
[  551.617117]  hid_generic usbhid hid ahci crc32_pclmul virtio_net net_failover virtio_rng psmouse lpc_ich i2c_i801 libahci i2c_smbus failover virtio_blk [last unloaded: tempesta_lib]
[  551.627777] CR2: 00000000000002e8
[  551.628417] ---[ end trace a4ac0fde385e9dd2 ]---
[  551.629159] RIP: 0010:tfw_h2_resp_adjust_fwd+0x526/0x720 [tempesta_fw]
[  551.630042] Code: 00 00 00 8b 8d d4 fe ff ff 80 48 10 01 66 83 48 12 08 89 48 14 48 8b 00 48 39 c3 75 ec 49 8b 45 38 be 08 00 00 00 48 8b 78 40 <48> 89 97 e8 02 00 00 48 81 c7 f8 02 00 00 4c 89 7f f8 e8 e3 3e d8
[  551.632193] RSP: 0018:ffffad8e4011c8b0 EFLAGS: 00010246
[  551.632989] RAX: ffff9821e037c020 RBX: ffff982190a9c000 RCX: 0000000000000007
[  551.633934] RDX: 0000000000000009 RSI: 0000000000000008 RDI: 0000000000000000
[  551.634870] RBP: ffffad8e4011c9f8 R08: ffffad8e4011c7e4 R09: ffff9821d2a4c010
[  551.635858] R10: 0000000000000000 R11: ffff9821d2a4c020 R12: ffff9821e037c020
[  551.636778] R13: ffff9821d2a4c020 R14: 0000000000000000 R15: 00000000009d59e2
[  551.637703] FS:  00007efd4d544640(0000) GS:ffff9822b7c80000(0000) knlGS:0000000000000000
[  551.638722] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  551.639584] CR2: 00000000000002e8 CR3: 0000000127bb6003 CR4: 0000000000770ee0
[  551.640526] PKRU: 55555554
[  551.641166] Kernel panic - not syncing: Fatal exception in interrupt
[  551.642212] Kernel Offset: 0x31c00000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[  551.643476] Rebooting in 1 seconds..
[  552.636364] ACPI MEMORY or I/O RESET_REG.
```

# Testing
`t_stress.test_wordpress.H2WordpressStress.test_get_large_images` with -R 5 and local config (all services on one VM)

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
Fix #1982 : We should only clear previosly inited tls context
but not release connection in case of error in
`tfw_tls_conn_init` function

### CODE REVIEW

**Review by krizhanovsky — CHANGES_REQUESTED** [review]
I didn't find any correctness issues, but it seems there are things to implement more efficiently.

File: fw/http.c [hunk 1]
```diff
@@ -4849,19 +4862,28 @@ int
...
+	spin_lock(&ctx->lock);
 
-	if(!resp->req->stream)
+	stream = req->stream;
+	if(!stream) {
+		spin_unlock(&ctx->lock);
 		return -EPIPE;
+	}
 
 	r = tfw_h2_append_predefined_body(resp, stream_id, body);
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/http.c]: Fixed

File: fw/http_frame.c [hunk 2]
```diff
@@ -804,6 +804,30 @@ tfw_h2_stream_id(TfwHttpReq *req)
 	return id;
 }
 
+int
+tfw_h2_stream_init_for_xmit(TfwHttpReq *req, unsigned long h_len,
```
Comment (krizhanovsky) [inline fw/http_frame.c:808]: This function must be in `http_stream.c`. Also I see `tfw_h2_stream_create()`, `tfw_h2_stream_clean()`, `__tfw_h2_stream_del_from_queue()` and other `tfw_h2_stream_`-prefixed functions - let's move them to `http_stream.c`, which not only responsible for streams, but also is much smaller than `http_frame.c`.

**Review by krizhanovsky — APPROVED** [review]
LGTM, but please do the cleanups. I think I already commented in some other pull request to move `tfw_h2_stream_`-prefixed function from `http_frame.c` to `http_stream.c`, but there are still many stream related functions in `http_frame.c` - please don't forget the movement.

File: fw/http_frame.c (hunk 2 above)
Comment (EvgeniiMekhanik) [reply fw/http_frame.c:808]: Yes, I think to do it in patch for 1196, but you right it's better to do it here
