### PR TITLE
Fix restarting without unloading modules

### LINKED ISSUE #893: [CFG] Repeated parsing of invalid configuration may cause dead loop
Happens on multiple starts or restarts when at least one server is defined in configuration and successfully processed.

E.g. Start or restart TempestaFW with configuration below will lead to dead loop on back end servers cleanup.
```
$ cat etc/tempesta_fw.conf 
sched ratio;
server 192.168.122.1:8080;

location prefix "/" {
jsnvkjsfnvkjf;
}
```

Multiple starts:
```
[  137.280176] [tdb] Start Tempesta DB
[  137.299532] [tempesta] Initializing Tempesta FW kernel module...
[  137.313294] [tempesta] Registering new scheduler: hash
[  137.319645] [tempesta] Registering new scheduler: http
[  137.328238] [tempesta] Registering new scheduler: ratio
[  137.332705] [tempesta] Prepearing for the configuration processing.
[  137.334386] [tempesta] ERROR: don't know how to handle: jsnvkjsfnvkjf
[  137.336079] [tempesta] ERROR: configuration parsing error:
[  137.336079]    5: jsnvkjsfnvkjf;
[  137.336079]       ^^^^^^^^^^^^^^
[  142.527026] [tempesta] Prepearing for the configuration processing.
[  142.528117] [tempesta] ERROR: location: Duplicate entry: 'location prefix /'
[  142.529515] [tempesta] ERROR: configuration parsing error:
[  142.529515]    4: location prefix "/" {
[  142.529515]       ^^^^^^^^^^^^^^^^^^^^^
[  146.876336] [tempesta] Prepearing for the configuration processing.
[  146.877553] [tempesta] ERROR: location: Duplicate entry: 'location prefix /'
[  146.879882] [tempesta] ERROR: configuration parsing error:
[  146.879882]    4: location prefix "/" {
[  146.879882]       ^^^^^^^^^^^^^^^^^^^^^
[  151.944005] [tempesta] Warning: pending for server callbacks to complete for 5s
[  156.948045] [tempesta] Warning: pending for server callbacks to complete for 5s
[  161.952042] [tempesta] Warning: pending for server callbacks to complete for 5s
[  166.956048] [tempesta] Warning: pending for server callbacks to complete for 5s
[  171.960006] [tempesta] Warning: pending for server callbacks to complete for 5s
[  176.964006] [tempesta] Warning: pending for server callbacks to complete for 5s
[  181.968008] [tempesta] Warning: pending for server callbacks to complete for 5s
```
This will last forever and consume 100% cpu. Also note `ERROR: location: Duplicate entry: 'location prefix /'` error, which means that `TfwCfgSpec` is not cleaned properly on error.

Multiple restarts:
```
[  578.804265] [tempesta] Warning: Trying to stop an inactive system
[  578.810565] [tempesta] Un-registering scheduler: hash
[  578.845681] [tempesta] Un-registering scheduler: http
[  578.878273] [tempesta] Un-registering scheduler: ratio
[  578.928958] [tempesta] exiting...
[  578.973749] [tdb] Shutdown Tempesta DB
[  579.099686] [tdb] Start Tempesta DB
[  579.109474] [tempesta] Initializing Tempesta FW kernel module...
[  579.119015] [tempesta] Registering new scheduler: hash
[  579.125464] [tempesta] Registering new scheduler: http
[  579.135050] [tempesta] Registering new scheduler: ratio
[  579.141925] [tempesta] Prepearing for the configuration processing.
[  579.143604] [tempesta] ERROR: configuration parsing error:
[  579.143604]    5: jsnvkjsfnvkjf;
[  579.143604]       ^^^^^^^^^^^^^^
[  580.126966] [tdb] Shutdown Tempesta DB
[  580.245417] [tdb] Start Tempesta DB
[  580.278134] [tempesta] ERROR: configuration parsing error:
[  580.278134]    5: jsnvkjsfnvkjf;
[  580.278134]       ^^^^^^^^^^^^^^
[  585.344024] [tempesta] Warning: pending for server callbacks to complete for 5s
[  590.348043] [tempesta] Warning: pending for server callbacks to complete for 5s
```

### PR DESCRIPTION
**Pull request by ikoveshnikov**
fix #893 (point 3)

### CODE REVIEW

File: tempesta_fw/tls.c [hunk 1]
```diff
@@ -439,8 +433,7 @@ tfw_tls_stop(void)
 {
```
Comment (aleksostapenko) [inline tempesta_fw/tls.c]: This is an empty callback now - maybe it is not needed at all.
