### PR TITLE
Denis shkiria 2314 tfw logger missing logs fix

### LINKED ISSUE #2314: tfw_logger: missing logs during the first second of application startup
**Describe the issue**
No logs are present in the ClickHouse database during the first second of application startup, although logs do appear in dmesg.

**Expected Behavior**
Logs are present in both dmesg and the ClickHouse access_log table.

**To Reproduce**
Start Tempesta FW, wait for it to begin responding, and then send a request as soon as possible. I reproduced this with a simple test.
```python
import time
from datetime import datetime

from test_suite import tester
from helpers.error import ProcessBadExitStatusException
import clickhouse_connect

__author__ = "Tempesta Technologies, Inc."
__copyright__ = "Copyright (C) 2018-2025 Tempesta Technologies, Inc."
__license__ = "GPL2"


class TestClickhouseLogsBaseTest(tester.TempestaTest):
    backends = [
        {
            "id": "deproxy",
            "type": "deproxy",
            "port": "8000",
            "response": "static",
            "response_content": "HTTP/1.1 200 OK\r\n" "Content-Length: 0\r\n\r\n",
        },
    ]

    tempesta = dict(
        config="""
            listen 80;
            server ${server_ip}:8000;

            access_log dmesg mmap mmap_host=localhost mmap_log=/tmp/access.log;
        """
    )
    clients = [
        {
            "id": "deproxy",
            "type": "deproxy",
            "addr": "${tempesta_ip}",
            "port": "80",
        }
    ]

    def setUp(self):
        super(TestClickhouseLogsBaseTest, self).setUp()

        self.clickhouse_client = clickhouse_connect.get_client()

        res = self.clickhouse_client.command('exists table access_log')

        if res:
            self.clickhouse_client.command('delete from access_log where true')

        try:
            print('removing access log')
            tempesta = self.get_tempesta()
            res = tempesta.node.run_cmd('rm /tmp/access.log')
            assert res == (b'', b'')

        except ProcessBadExitStatusException as e:
            print(e)

    def test_missing_log(self):
        self.start_all_servers()
        self.start_tempesta()
        self.deproxy_manager.start()
        self.start_all_clients()
        self.assertTrue(self.wait_all_connections())

        client = self.get_client('deproxy')
        client.start()

        client.send_request(
            request=client.create_request(method="GET", headers=[]),
            expected_status_code='200',
            timeout=10,
        )

        request_in_dmesg = self.oops.find("GET / HTTP/1.1")
        assert request_in_dmesg is True

        tempesta = self.get_tempesta()
        stdout, _ = tempesta.node.run_cmd('cat /tmp/access.log')
        assert stdout.endswith(b'Daemon started\n')

        res = self.clickhouse_client.query('select * from access_log')
        assert len(res.result_rows) == 0

        time.sleep(5)
        res = self.clickhouse_client.query('select * from access_log')
        assert len(res.result_rows) == 0

```

**Configuration file**
```
            listen 80;
            server ${server_ip}:8000;

            access_log dmesg mmap mmap_host=localhost mmap_log=/tmp/access.log;
```

**Version or commit hash**
80598c97099132d383426ae45dd45f8bf1bd675d

**Stacktrace or debug log**
Here is the dmesg output for the accepted request
```
2025-01-06T20:59:52.876152+0100 symstu-TM1613 kernel: [tdb] Start Tempesta DB
2025-01-06T20:59:52.892091+0100 symstu-TM1613 kernel: [tempesta fw] Initializing Tempesta FW kernel module...
2025-01-06T20:59:53.024120+0100 symstu-TM1613 kernel: [tempesta fw] Configuration processing is completed.
2025-01-06T20:59:53.048161+0100 symstu-TM1613 kernel: [tdb] Opened table /opt/tempesta/db/filter0.tdb: size=16777216 rec_size=20 base=00000000a234d73a
2025-01-06T20:59:53.148158+0100 symstu-TM1613 kernel: [tdb] Opened table /opt/tempesta/db/cache0.tdb: size=268435456 rec_size=0 base=00000000a2343f3f
2025-01-06T20:59:53.156157+0100 symstu-TM1613 kernel: [tdb] Opened table /opt/tempesta/db/sessions0.tdb: size=16777216 rec_size=312 base=000000002fd3ede7
2025-01-06T20:59:53.164205+0100 symstu-TM1613 kernel: [tdb] Opened table /opt/tempesta/db/client0.tdb: size=16777216 rec_size=624 base=00000000108cdf2b
2025-01-06T20:59:53.196180+0100 symstu-TM1613 kernel: [tempesta fw] Open listen socket on: 0.0.0.0
2025-01-06T20:59:53.212126+0100 symstu-TM1613 kernel: [tempesta fw] Tempesta FW is ready
2025-01-06T20:59:53.232107+0100 symstu-TM1613 kernel: [tempesta fw] 127.0.0.2 "default" "GET / HTTP/1.1" 200 0 "-" "-"
```

and here is the access.log for the tfw_logger
```
[2025-01-06 20:59:53.212] [access_logger] [info] Starting daemon...
[2025-01-06 20:59:53.213] [access_logger] [info] Daemon started
[2025-01-06 20:59:58.280] [access_logger] [info] Stopping daemon...
[2025-01-06 20:59:58.289] [access_logger] [info] Daemon stopped
```

As you can see, the request was registered at 2025-01-06 20:59:53.232107, while the logger daemon finished startup at 2025-01-06 20:59:53.213. This indicates that the daemon was already running when the request was registered. To address this, you can add a time.sleep() call for at least 1 second before the test client sends the request, which should prevent this bug from occurring.

### PR DESCRIPTION
**Pull request by DenisShkiria**
Fixes #2314 and #2437, massive architecture reworking.

### CODE REVIEW

File: logger/clickhouse.cc [hunk 1]
```diff
@@ -41,8 +41,8 @@ constexpr std::string_view table_creation_query_template =
 	"ENGINE = MergeTree() ORDER BY timestamp";
 
 TfwClickhouse::TfwClickhouse(const ClickHouseConfig &config,
-			     clickhouse::Block block)
-	: block_(std::move(block)),
+			     clickhouse::Block *block)
```
Comment (consuelo2210) [inline logger/clickhouse.cc]: Why not but ref? :)

File: logger/tfw_logger.cc [hunk 2]
```diff
@@ -305,6 +305,7 @@ try {
 	}
 	catch (const Exception &e) {
 		log_error(e.what(), true, false);
+		block.Clear();
```
Comment (consuelo2210) [inline logger/tfw_logger.cc]: don't we need to clear it in any exception? It would be good at least to leave a comment: why we are doing clear and when, and when we are trying to flush after stop

File: logger/tfw_logger.cc [hunk 3]
```diff
@@ -317,6 +318,21 @@ try {
...
+	block.RefreshRowCount();
+	while (block.GetRowCount() > 0)
+	try {
+		spdlog::debug("Worker {} flushing remaining events...", ncpu);
+		TfwClickhouse clickhouse(config.clickhouse, &block);
+		clickhouse.commit(/*force=*/true);
+	}
+	catch (const std::exception &e) {
+		log_error(e.what(), true, false);
+		std::this_thread::sleep_for(timeout);
```
Comment (consuelo2210) [inline logger/tfw_logger.cc]: but we are stopping, why do we need to sleep and change timeout?

File: logger/clickhouse.cc (hunk 1 above)
Comment (DenisShkiria) [reply logger/clickhouse.cc]: The both options looks questionable here, so I choose the pointer to because for some reason the following function returns pointer:
```
	clickhouse::Block *get_block() noexcept;
```
and because the form with `&` looks a bit clearer in the following line:
```
TfwClickhouse clickhouse(ch_cfg, &block);
```
But basically the both options are about equal here.

File: logger/tfw_logger.cc (hunk 2 above)
Comment (DenisShkiria) [reply logger/tfw_logger.cc]: The current logic considers exceptions of the type Exception unrecoverable. The while(1) loop stops when an exception arises, and the thread finishes. In this case, we do not try to flush the contents of the buffer because it can contain corrupted data. For example, the internal rows of the block may have different sizes. When the exception means something else, the block should already be cleared.

> don't we need to clear it in any exception?

No. The current implementation uses exceptions to reestablish the connection to ClickHouse when the ClickHouse-cpp library cannot insert the block into the database. If, for some reason, the block cannot be sent to the DB, an exception is raised, and the connection to the DB is reestablished. However, the block should not be cleared in this case, otherwise part of its data could be lost.

I agree that adding a comment with these details here is worth it. In my opinion, rewriting code to simplify it is better than writing long comments. However, comments are better than nothing.

File: logger/tfw_logger.cc (hunk 3 above)
Comment (DenisShkiria) [reply logger/tfw_logger.cc]: No, if we're here, it means ClickHouse-cpp lib encountered an issue and threw an exception. We should reestablish the connection and try again.

**Comment by DenisShkiria** [comment]
> the destructor is more propriate way for block cleaning.

Unfortunately, as far as I understand, incorporating flush logic into the destructor is more labor-intensive. When the ClickHouse C++ library sends data to the database, it throws an exception in case of an error. The [recommended](https://github.com/ClickHouse/clickhouse-cpp/issues/184) way to handle the exception is to reset the connection to the DB. To send data to the DB, you should write the code similar to the following:
```
while (true) {
  if (stop_requested())
    break;
    
  try {
    log(inserting...)
    connection->insert(block);
    log (success!)
    break;
  }
  catch (e) {
    log(failed to insert)
  }
  reconnect(connection)
}
```
It is possible to write something similar in the `~TfwClickhouse()`, but we would need to modify `TfwClickhouse()`. I decided that moving the flush logic into a separate cycle would be a less intrusive change.

File: logger/tfw_logger.cc (hunk 3 above)
Comment (consuelo2210) [reply logger/tfw_logger.cc]: But in this case we just increasing timeout after each failed try. Let's imagine that there is some issue with CH and we can't reconnect to it. So does the program just hang on stop? It doesn't sound right. And I can't see another condition of breaking this circle

File: logger/clickhouse.cc (hunk 1 above)
Comment (consuelo2210) [reply logger/clickhouse.cc]: I think it is better to move in the direction when in case of object presence we have a ref. Especially that we create that block with make_block. But this is really minor for this particular review. I am going to close this discussion

File: logger/tfw_logger.cc (hunk 3 above)
Comment (DenisShkiria) [reply logger/tfw_logger.cc]: Sorry, when I wrote the first comment, I thought we were discussing the previous while(1) {...} cycle. Yes, the suggested logic ignores the stop flag when the block is not empty and tries to send data to ClickHouse until the end. If the connection to ClickHouse has been lost and cannot be reestablished and the block is not empty, then this cycle will continue indefinitely. This also means that the program cannot stop gracefully. My logic is that if the user does not want to wait for a graceful shutdown, which can take an unpredictable amount of time, he or she should send a SIGKILL.

File: logger/mmap_buffer.cc [hunk 4]
```diff
@@ -113,12 +113,14 @@ TfwMmapBufferReader::read()
 	head = __atomic_load_n(&buf_->head, __ATOMIC_ACQUIRE);
 	tail = buf_->tail;
 
-	if (head - tail == 0) [[unlikely]]
-		return -EAGAIN;
+	assert(head >= tail);
+	const int size = static_cast<int>(head - tail);
 
-	callback_(buf_->data + (tail & buf_->mask), head - tail, private_data_);
+	callback_(buf_->data + (tail & buf_->mask), size, private_data_);
```
Comment (krizhanovsky) [inline logger/mmap_buffer.cc]: I think it'd be better to not to call `callback()` each time the thread wakes up. Also this fix will break with #2442, when we move from polling to event-driven operation.

Essentially, for now we should emulate call Clickhouse only if a time elapses. I'm thinking about State pattern for `TfwClickhouse`, which will keep track whether we have bach buffer clear or do we need to flush something. This State-like object can replace `callback()`.

The problem isn't so crucial, but there is some overhead and we also do some senseless printing in `dbg_hexdump()` - just might be annoying.

File: logger/clickhouse.cc (hunk 1 above)
Comment (krizhanovsky) [reply logger/clickhouse.cc]: Yeah, I think it's also better to prefer reference to pointer as in general it provides more type safety. I'd prefer to adjust the current code to return references.

BTW we have Memory safety guidelines https://tempesta-tech.com/knowledge-base/Memory-safety-guideline/ , which are just a some additions to the [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) - our code must follow the principles. This particular case means that a reviewer overlooked the issue

File: logger/tfw_logger.cc [hunk 5]
```diff
@@ -212,12 +212,16 @@ read_access_log_event(const char *data, int size, TfwClickhouse *clickhouse)
...
+		size -= len_size;                                              \
 		if (len > size) [[unlikely]]                                   \
 			goto error;                                            \
 		(*block)[ind]->As<clickhouse::ColumnString>()->Append(         \
-		    std::string(p + 2, len));                                  \
-		len += 2;                                                      \
+		    std::string(p, len));                                      \
 		p += len;                                                      \
 		size -= len;                                                   \
 	} else                                                                 \
```
Comment (krizhanovsky) [inline logger/tfw_logger.cc]: The change is good, but I'd also replace the macro with a template function

File: fw/http.h [hunk 6]
```diff
@@ -414,7 +416,6 @@ struct tfw_http_req_t {
 	struct list_head	fwd_list;
 	struct list_head	nip_list;
 	unsigned long		jtxtstamp;
-	unsigned long		jrxtstamp;
```
Comment (const-t) [inline fw/http.h:417]: Please remove description from the doc of `tfw_http_req_t`.

**Review by const-t — APPROVED** [review]
LGTM

File: logger/tfw_logger.cc [hunk 7]
```diff
@@ -173,102 +170,116 @@ make_block()
...
+	read_int<TFW_MMAP_LOG_ADDR, ch::ColumnIPv6, in6_addr>(block, event, p, size);
+	read_int<TFW_MMAP_LOG_METHOD, ch::ColumnUInt8, unsigned char>(
+							block, event, p, size);
+	read_int<TFW_MMAP_LOG_VERSION, ch::ColumnUInt8, unsigned char>(
+							block, event, p, size);
+	read_int<TFW_MMAP_LOG_STATUS, ch::ColumnUInt16, uint16_t>(
+							block, event, p, size);
+	read_int<TFW_MMAP_LOG_RESP_CONT_LEN, ch::ColumnUInt32, uint32_t>(
+							block, event, p, size);
+	read_int<TFW_MMAP_LOG_RESP_TIME, clickhouse::ColumnUInt32, uint32_t>(
```
Comment (consuelo2210) [inline logger/tfw_logger.cc]: clickhouse ->cn

File: logger/tfw_logger.cc [hunk 8]
```diff
@@ -173,102 +170,116 @@ make_block()
...
+							block, event, p, size);
```
Comment (consuelo2210) [inline logger/tfw_logger.cc]: clickhouse -> cn

File: logger/tfw_logger.cc [hunk 9]
```diff
@@ -173,102 +170,116 @@ make_block()
 	return block;
 }
 
-int
-read_access_log_event(const char *data, int size, TfwClickhouse *clickhouse)
+template <auto method, typename ColType, typename ValType>
+void
+read_int(ch::Block &block, const auto *event, const char *&p, size_t &size)
```
Comment (consuelo2210) [inline logger/tfw_logger.cc]: const char *& -> is barely used, I would suggest to use string_view&

Comment (consuelo2210) [reply logger/tfw_logger.cc]: I'd also prefer to have wrapper around this string and around Block. I asked chatgpt to split for this 2 criterias, and I haven't verify the code inside. But the proposal looks similar to me idea:
```cpp
   struct BlockWriter {
    ch::Block& block;

    BlockWriter(ch::Block& blk) : block(blk) {}

    template <typename ColType, typename ValType>
    void write_int(size_t index, ValType val) {
        block[index]->As<ColType>()->Append(val);
    }

    void write_string(size_t index, std::string_view sv) {
        block[index]->As<ch::ColumnString>()->Append(std::string(sv));
    }

    void write_empty_string(size_t index) {
        block[index]->As<ch::ColumnString>()->Append(std::string(""));
    }
};

struct LineReader {
    std::string_view buf;  // buffer to read

    LineReader(const char* data, size_t size) : buf(data, size) {}

    template <typename ValType>
    ValType read_int() {
        if (sizeof(ValType) > buf.size())
            throw std::runtime_error("Buffer too small for integer");

        const ValType* val_ptr = reinterpret_cast<const ValType*>(buf.data());
        buf.remove_prefix(sizeof(ValType));
        return *val_ptr;
    }

    std::string_view read_u16_string() {
        constexpr size_t len_size = sizeof(uint16_t);

        if (len_size > buf.size())
            throw std::runtime_error("Buffer too small for string length");

        const uint16_t len = *reinterpret_cast<const uint16_t*>(buf.data());
        buf.remove_prefix(len_size);

        if (len > buf.size())
            throw std::runtime_error("Buffer too small for string content");

        std::string_view sv(buf.data(), len);
        buf.remove_prefix(len);
        return sv;
    }

    bool empty() const { return buf.empty(); }
};

//TODO: rename to consume_int
template <auto method, typename ColType, typename ValType>
void read_int(const auto* event, LineReader& reader, BlockWriter& writer) {
    constexpr int ind = method + 1;

    if (TFW_MMAP_LOG_FIELD_IS_SET(event, method)) {
        ValType val = reader.read_int<ValType>();
        writer.write_int<ColType>(ind, val);
    } else {
        writer.write_int<ColType>(ind, 0);
    }
}

//TODO: rename to consume_str
template <auto method>
void read_str(const auto* event, LineReader& reader, BlockWriter& writer) {
    constexpr int ind = method + 1;

    if (TFW_MMAP_LOG_FIELD_IS_SET(event, method)) {
        std::string_view sv = reader.read_u16_string();
        writer.write_string(ind, sv);
    } else {
        writer.write_empty_string(ind);
    }
}
```

Comment (consuelo2210) [reply logger/tfw_logger.cc]: The main difference will be in error handling. goto in this case is not a good idea

File: logger/clickhouse.cc [hunk 10]
```diff
@@ -1,6 +1,11 @@
 /**
  *		Tempesta FW
  *
+ * Clickhouse interfaces using the C++ client library.
+ * For code sameples and the source code reference:
```
Comment (consuelo2210) [inline logger/clickhouse.cc]:
```suggestion
 * For code samples and the source code reference:
```

File: logger/mmap_buffer.hh [hunk 11]
```diff
@@ -53,22 +56,23 @@
  */
 class TfwMmapBufferReader {
 public:
-	using Callback = std::function<void(std::span<const char> data)>;
+	using ProcessEvents = std::function<Error<size_t> (std::span<const char>)>;
```
Comment (consuelo2210) [inline logger/mmap_buffer.hh]: ProcessEvents -> EventBufferProcessor ? or EventProcessor ?  ProcessEventsFn ?ProcessEvents looks like we have a vector inside

File: logger/tfw_logger.cc [hunk 12]
```diff
@@ -531,7 +531,16 @@ try {
...
 	logger->flush_on(spdlog::level::info);
-} catch (const spdlog::spdlog_ex &ex) {
+
+	// Set custom log pattern to include thread ID
+	// %Y-%m-%d %H:%M:%S.%e - Date and time with milliseconds
+	// %n - Logger name
+	// %l - Log level
+	// %t - Thread ID
+	// %v - Log message
+	logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%n] [%l] [%t] %v");
```
Comment (consuelo2210) [inline logger/tfw_logger.cc:581]: with this change I asked Denis to fix line 516:

if (!opts.foreground) {
		spdlog::debug("Daemonizing...");
		
We haven't initialized spdlog yet here, so it will be better so write in std::cout here

File: logger/clickhouse.cc [hunk 13]
```diff
@@ -17,35 +22,94 @@
...
+{
+	block_ = ch::Block();
+
+	auto col = std::make_shared<ch::ColumnDateTime64>(3);
+	block_.AppendColumn("timestamp", col);
+
+	for (int i = TFW_MMAP_LOG_ADDR; i < TFW_MMAP_LOG_MAX; ++i) {
+		const TfwField *field = &tfw_fields[i];
+		auto col = tfw_column_factory(field->code);
+		block_.AppendColumn(field->name, col);
```
Comment (consuelo2210) [inline logger/clickhouse.cc:90]: Why do we AppendColumn with timestamp first? Could we do it after specific enum values? It could save us from idx+1 code

File: logger/mmap_buffer.hh [hunk 14]
```diff
@@ -53,22 +56,23 @@
...
+	[[nodiscard]] bool run(std::atomic<bool> &stop_flag) noexcept;
 	unsigned int get_cpu_id() const noexcept;
 
 private:
 	TfwMmapBuffer	*buf_;
 	size_t		size_;
-	bool		is_running_;
-	Callback	callback_;
+	ProcessEvents	proc_ev_;
+	TfwClickhouse	&db_;
```
Comment (consuelo2210) [inline logger/mmap_buffer.hh:74]: The TfwClichHouse with a callback looks a bit strange here. Since we already have db_ as a member, we lose the abstraction of why the callback was created. Previously, we were explicitly doing something with the data; now, there are hints that the data is being inserted into the database, but the actual insertion is hidden inside the callback’s black box. It seems we could safely remove proc_ev_ at this point.

**Review by consuelo2210 — CHANGES_REQUESTED** [review]
I love the way you use idle time to flush the database.

I left some comments during the review, but the main issue for me is that we still have a lot of code that needs to be separated. All reading functions (read_int, read_access_event and so on) should be moved outside of tfw_logger.cc.

I believe that this function:
```cpp
bool TfwMmapBufferReader::run(std::atomic<bool> &stop_flag) noexcept
```
should become a free function:
```cpp
bool run(std::atomic<bool> &stop_flag) noexcept
```


and call consume_event and flush from all EventProcessors (if we have several). I propose the following interface:

```cpp
class IEventProcessor {
public:
    void consume_event();
    void make_background_work(); // Will be called during idle, e.g., commit to ClickHouse
};
```

Every EventProcessor should implement the reading functions (read_int, read_str, consume_event) and, I think, hold a direct reference to TfwClickhouse and write to it during consumption. If we later introduce another writer, we can consider unifying them under a common interface, but for now, we don’t need that.

We can add the following methods to TfwClickhouse and get rid of get_block method (because the class can work only around this one block).

```cpp
template <typename ColType, typename ValType>
void write_int(size_t index, ValType val) {
    block_[index]->As<ColType>()->Append(val);
}

void write_string(size_t index, std::string_view sv) {
    block_[index]->As<ch::ColumnString>()->Append(std::string(sv));
}

void write_empty_string(size_t index) {
    block_[index]->As<ch::ColumnString>()->Append(std::string(""));
}
```
I used template, because it is more close to your code, but we can define IndexType for every index.
template <typename IndexType>
void write_int(IndexType index, IndexType::val_type val){
    block_[IndexType::index_constant]->As<IndexType::col_type>()->Append(val);
}

I think we should get rid of the callback. Previously, it created an abstraction and hid all details of processing. But now, since we have db as a member, that abstraction is broken and only adds unnecessary complexity.

I also rewrite read_int, read_str during another comment to separate reading and writing inside consume_* operation.

So, for me, for now, it is more about separating.

File: logger/error.hh [hunk 15]
```diff
@@ -22,15 +27,78 @@
...
 
 #include <boost/system/system_error.hpp>
 #include <boost/system/error_code.hpp>
 
+/*
+ * ------------------------------------------------------------------------
+ *	std::expected API for the data path
+ * ------------------------------------------------------------------------
+ */
+enum class Err : int {
```
Comment (consuelo2210) [inline logger/error.hh:47]: I proposed another solution here
https://github.com/tempesta-tech/escudo/issues/176. Have a look, please

File: logger/clickhouse.cc (hunk 13 above)
Comment (krizhanovsky) [reply logger/clickhouse.cc:90]: Yeah, probably it does make sense from technical point of view, but I'd be confused to see timestamp somwhere else than in the first column from `select * from access_log`. And probably there is no hurt with `+ 1`, so I close the comment as resolved, but feel free to reopen if you believe this is important.

File: logger/tfw_logger.cc (hunk 9 above)
Comment (krizhanovsky) [reply logger/tfw_logger.cc]: @consuelo2210 yes, `std::string_view` is definitely better than `const char *&`. But I didn't get about `LineReader` and `BlockWriter` - what's the point? They are new logical entities and int he proposed approach there are more code, which doesn't look easier to read than the functions? What we get from the 2 new structures?

@ttaym at the moment the logic under discussion is in the generic logging daemon file `tfw_logger.cc` and with the xFW event logging it must be moved to a Tempesta FW specific plugin, so yes, it should be moved to some new class and file. I'm not sure about proposed two separate reading and writing classes, but at least one new class is required.

So far I'm adding a TODO comment in the code.

File: logger/mmap_buffer.hh (hunk 14 above)
Comment (krizhanovsky) [reply logger/mmap_buffer.hh:74]: Yes, agree. Probably, there should be
1. a class aggregating the existing `process_events()`, `read_access_log_event()`, `read_str()` and `read_int()`. The motivation is https://github.com/tempesta-tech/tempesta/issues/2399 - the same ring buffer will be used for other events with another logic.
2. The new class must proxy data from the ring buffers to Clickhouse. Interfaces in TBD, but it should have only one entry point, not 2, like we have now for `db_` and the callback

File: logger/error.hh (hunk 15 above)
Comment (krizhanovsky) [reply logger/error.hh:47]: OK, I commented https://github.com/tempesta-tech/escudo/issues/176 : let's leave this for that task. The task in the next milestone and there is no reason to do it in this PR.

**Review by consuelo2210 — APPROVED** [review]

File: logger/tfw_logger.cc (hunk 9 above)
Comment (consuelo2210) [reply logger/tfw_logger.cc]: I'm not sure I was clear earlier. I realized that while we want to separate reading and writing responsibilities, they're currently mixed together in these functions. For example, if we add more events that require integer reading, we’ll end up duplicating code.

In my final review comment, I suggested moving the reader-related functions into the EventProducer class and the writer-related functions into the CH class. I believe this will improve code readability and maintainability.

File: logger/tfw_logger.cc [hunk 16]
```diff
@@ -114,6 +114,24 @@ dbg_hexdump([[maybe_unused]] std::span<const char> data)
...
+ * specific plugin, most likely to a new class(es)
+ * There will be similar functions (class API) for the security events logging.
+ *
+ * The classes should inherit the same interface, e.g.
+ *
+ *	class IEventProcessor {
+ *	public:
+ *		Error<bool> consume_event();
+ *		void make_background_work();
+ *		[[nodiscard]] bool flush(bool force = false) noexcept;
```
Comment (consuelo2210) [inline logger/tfw_logger.cc:130]: void make_background_work();
 or 
[[nodiscard]] bool flush(bool force = false) noexcept;
 
 not both, right?

File: logger/mmap_buffer.cc [hunk 17]
```diff
@@ -86,6 +86,12 @@ TfwMmapBufferReader::read() noexcept
 	if (!res)
 		return error(Err::DB_SRV_FATAL);
 
+	// TODO #2399, #182 (escudo xFW): this should be replaced with
+	// IEventProcessor->flush(), but ideally if we can move it to the
+	// free run() function in tfw_logger. Basically, we flush() events
+	// after a ring buffer read, so probably it's just fine to firstly
+	// call all event processors to read events from the associated RBs
```
Comment (consuelo2210) [inline logger/mmap_buffer.cc:93]: I love this. They really can collect ch::Block inside during reading and have a method

::flush(Clickhouse &db)
{
//std::unique_ptr<Block> block_;
db->commit(block_.release());
}

File: logger/tfw_logger.cc (hunk 16 above)
Comment (krizhanovsky) [reply logger/tfw_logger.cc:130]: I think we need the both: one when the main loop is idle and another one for when we read something and mush flush the data
