### PR TITLE
Fix accesing connection after Tempesta unload

### LINKED ISSUE #2010: Kernel BUG on `test_rmark_wo_or_incorrect_cookie` test
[ 4374.819118] Start test: sessions.test_redir_mark.RedirectMarkVhost.test_rmark_wo_or_incorrect_cookie
[ 4374.899660] [tdb] Start Tempesta DB
[ 4375.027461] [tdb] Opened table /opt/tempesta/db/filter0.tdb: size=16777216 rec_size=20 base=0000000039ac6985
[ 4375.111034] [tdb] Opened table /opt/tempesta/db/cache0.tdb: size=268435456 rec_size=0 base=00000000c63cacad
[ 4375.116927] [tdb] Opened table /opt/tempesta/db/sessions0.tdb: size=16777216 rec_size=312 base=000000005bc2d217
[ 4375.122710] [tdb] Opened table /opt/tempesta/db/client0.tdb: size=16777216 rec_size=624 base=00000000ca811064
[ 4375.176408] [tempesta fw] Tempesta FW is ready
[ 4376.637734] End test:   sessions.test_redir_mark.RedirectMarkVhost.test_rmark_wo_or_incorrect_cookie
[ 4403.508264] Start test: sessions.test_redir_mark.RedirectMark.test_good_rmark_value
[ 4403.536724] net_ratelimit: 56 callbacks suppressed
[ 4403.536725] [tempesta fw] Live reconfiguration of Tempesta.
[ 4403.615174] [tempesta fw] Configuration processing is completed.
[ 4403.695202] [tempesta fw] Tempesta FW is ready
[ 4409.810498] [tempesta fw] Warning: pending active connections for 5s (connections count 0x20, queues count 0)
[ 4409.811123] [tempesta fw] Warning:   cpu 0(3), backlog size 0, active connections mask 0x4000000000, cntwork queue size 0, close backlog is empty
[ 4409.811859] [tempesta fw] Warning:   cpu 1(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4409.812550] [tempesta fw] Warning:   cpu 2(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4409.813271] [tempesta fw] Warning:   cpu 3(3), backlog size 0, active connections mask 0xffffffe000000000, cntwork queue size 0, close backlog is empty
[ 4409.814034] [tempesta fw] Warning:   cpu 4(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4409.814744] [tempesta fw] Warning:   cpu 5(3), backlog size 0, active connections mask 0x100000000, cntwork queue size 0, close backlog is empty
[ 4409.815504] [tempesta fw] Warning:   cpu 6(3), backlog size 0, active connections mask 0xffffffff00000000, cntwork queue size 0, close backlog is empty
[ 4409.816267] [tempesta fw] Warning:   cpu 7(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4414.858249] [tempesta fw] Warning: pending active connections for 5s (connections count 0x20, queues count 0)
[ 4414.858853] [tempesta fw] Warning:   cpu 0(3), backlog size 0, active connections mask 0x4000000000, cntwork queue size 0, close backlog is empty
[ 4414.859590] [tempesta fw] Warning:   cpu 1(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4414.860302] [tempesta fw] Warning:   cpu 2(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4414.861019] [tempesta fw] Warning:   cpu 3(3), backlog size 0, active connections mask 0xffffffe000000000, cntwork queue size 0, close backlog is empty
[ 4414.861782] [tempesta fw] Warning:   cpu 4(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4414.862493] [tempesta fw] Warning:   cpu 5(3), backlog size 0, active connections mask 0x100000000, cntwork queue size 0, close backlog is empty
[ 4414.863625] [tempesta fw] Warning:   cpu 6(3), backlog size 0, active connections mask 0xffffffff00000000, cntwork queue size 0, close backlog is empty
[ 4414.864394] [tempesta fw] Warning:   cpu 7(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4419.865999] [tempesta fw] Warning: pending active connections for 5s (connections count 0x20, queues count 0)
[ 4419.866662] [tempesta fw] Warning:   cpu 0(3), backlog size 0, active connections mask 0x4000000000, cntwork queue size 0, close backlog is empty
[ 4419.867397] [tempesta fw] Warning:   cpu 1(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4419.868140] [tempesta fw] Warning:   cpu 2(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4419.868829] [tempesta fw] Warning:   cpu 3(3), backlog size 0, active connections mask 0xffffffe000000000, cntwork queue size 0, close backlog is empty
[ 4419.869590] [tempesta fw] Warning:   cpu 4(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4419.870327] [tempesta fw] Warning:   cpu 5(3), backlog size 0, active connections mask 0x100000000, cntwork queue size 0, close backlog is empty
[ 4419.871143] [tempesta fw] Warning:   cpu 6(3), backlog size 0, active connections mask 0xffffffff00000000, cntwork queue size 0, close backlog is empty
[ 4419.871915] [tempesta fw] Warning:   cpu 7(3), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 4419.872654] ------------[ cut here ]------------
[ 4419.872937] WARNING: CPU: 3 PID: 7440 at /home/evgeny/workdir/tempesta/fw/main.c:172 tfw_mods_stop+0xa4/0xc0 [tempesta_fw]
[ 4419.873590] Modules linked in: tempesta_fw(OE) tempesta_db(OE) tempesta_tls(OE) tempesta_lib(OE) tls sha256_ssse3 sha512_ssse3 xt_conntrack nft_chain_nat xt_MASQUERADE nf_nat nf_conntrack_netlink nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 xfrm_user xfrm_algo nft_counter xt_addrtype nft_compat nf_tables nfnetlink br_netfilter bridge stp llc overlay binfmt_misc nls_iso8859_1 virtio_gpu virtio_dma_buf drm_kms_helper cec kvm_intel rc_core fb_sys_fops syscopyarea kvm sysfillrect sysimgblt crct10dif_pclmul ghash_clmulni_intel aesni_intel joydev crypto_simd input_leds cryptd serio_raw mac_hid glue_helper qemu_fw_cfg sch_fq_codel msr drm parport_pc ppdev lp pstore_blk parport pstore_zone ramoops efi_pstore reed_solomon ip_tables x_tables autofs4 btrfs blake2b_generic xor raid6_pq libcrc32c psmouse e1000 crc32_pclmul floppy i2c_piix4 pata_acpi [last unloaded: tempesta_lib]
[ 4419.877915] CPU: 3 PID: 7440 Comm: sysctl Tainted: G           OE     5.10.35+ #270
[ 4419.878355] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014
[ 4419.878839] RIP: 0010:tfw_mods_stop+0xa4/0xc0 [tempesta_fw]
[ 4419.879158] Code: 8b 05 20 00 07 02 85 c0 75 24 e8 b7 53 9f de 85 c0 0f 85 97 14 02 00 5b 41 5c 5d c3 e8 35 7f 00 00 e8 a0 58 00 00 84 c0 75 c3 <0f> 0b eb bf 0f 0b 48 c7 c7 b0 29 f9 c0 e8 47 b5 bf de 66 2e 0f 1f
[ 4419.880244] RSP: 0018:ffffbc8f4154bcf8 EFLAGS: 00010246

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
During applying new configuration, we delete old
server groups, servers and their connections.
We should immediately close and drop connection
in this case, because we may not receive FIN from
the peer and connection hung. Moreover we don't
need to be shure that backend receive FIN from
our side and closed gracefully because we stop
work with such server and don't expect any
response from it.

Closes #2010

### CODE REVIEW

File: fw/connection.h [hunk 1]
```diff
@@ -404,6 +404,8 @@ tfw_connection_put(TfwConn *conn)
 		return;
 
 	rc = atomic_dec_return(&conn->refcnt);
+	BUG_ON(rc < 0 && rc != TFW_CONN_DEATHCNT);
```
Comment (keshonok) [inline fw/connection.h:407]: `TFW_CONN_DEATHCNT` is definitely greater than zero. What exactly is this `BUG_ON()` for?

Comment (EvgeniiMekhanik) [reply fw/connection.h]: #define TFW_CONN_DEATHCNT	(INT_MIN / 2) is less than zero, but BUG_ON should be BUG_ON(rc < TFW_CONN_DEATHCNT)

Comment (keshonok) [reply fw/connection.h]: Ah, indeed. Thanks!

**Comment by const-t** [comment]
I'm not sure about this fix. In this patch we trying to close connection as fast as possible, but it can be unreliable. 

1. `tfw_sock_srv_disconnect` calls from `tfw_sock_srv_grace_shutdown_cb()` which is a timer, it implies call of this function can be delayed depending on the `grace_shutdown_time` directive. Is it safe? 

2. As I see in pinned issue, Tempesta crashes on `BUG_ON(tfw_ss_users);` in `tfw_mods_stop()` that looks strange, if it caused by connection "hanging" can we ensure that it can't be triggered by another hung connection, that not fixed in current PR or by case described above? Maybe would be better to improve processing of hung connection during Tempesta stopping?

Can you describe problem in details, exactly why hung connection leads to crash in this place?

**Comment by const-t** [comment]
This not related to current fix but, I can't understand. Why `tfw_sock_srv_grace_stop()` calls `tfw_server_stop_sched()`, but in case when `tfw_cfg_grace_time` is zero `tfw_server_stop_sched()` not will be called.

**Comment by EvgeniiMekhanik** [comment]
> I'm not sure about this fix. In this patch we trying to close connection as fast as possible, but it can be unreliable.
> 
>     1. `tfw_sock_srv_disconnect` calls from `tfw_sock_srv_grace_shutdown_cb()` which is a timer, it implies call of this function can be delayed depending on the `grace_shutdown_time` directive. Is it safe?
> 
>     2. As I see in pinned issue, Tempesta crashes on `BUG_ON(tfw_ss_users);` in `tfw_mods_stop()` that looks strange, if it caused by connection "hanging" can we ensure that it can't be triggered by another hung connection, that not fixed in current PR or by case described above? Maybe would be better to improve processing of hung connection during Tempesta stopping?
> 
> 
> Can you describe problem in details, exactly why hung connection leads to crash in this place?
> 
> As I understood problem in `tfw_sock_srv_grace_stop` we close connection in `tfw_sock_srv_disconnect_srv(srv);` but it hangs and after it we call `tfw_server_destroy() -> tfw_sock_srv_del_conns()` that frees connections. Am I right?

First of all I should describe the problem:
When we reload configuration we delete all servers groups and all servers from all lists. We call `tfw_sock_srv_disconnect_srv` for each server and close appropriate connections with `tfw_connection_close`. But if sk_stream_closing(sk) returns true we don't drop the connection and wait for FIN from peer. If FIN doesn't come connection hung (since connection gets recounter of server and server gets refcounter of server group all this structures stay in memory. During tempesta unload we iterate over all servers and abort pending connections, but as I describe below such reconfigured servers are not in any list! So they will stay in memory after tempesta unload! Previously (before my first patch, where I rework socket closing there was no such problem, because we immediately drop connection after ss_close!). This patch fix this problem, now we abort and immediately close all connections during tempesta recofiguration.

Answers:
1. There is no problem with `grace_shutdown_time` because when we unload tempesta we iterate over all servers in `tfw_gs_servers` list and abort all it's connections.
2. As I understand logic if `grace_shutdown_time`  is null we should immediately close and drop connection.

**Review by krizhanovsky — APPROVED** [review]
LGTM. Just please comment the server connection abort code - why do we need to abort a connection with `DEL` flag instead of normal closing
