### PR TITLE
Fix #691

### LINKED ISSUE #691: Memory leaks in Tempesta
The setup:
* Tempesta's current master at 56b0ecb;
* Tempesta kernel 4.8.15  at [5b3aa7f](https://github.com/tempesta-tech/linux-4.8.15-tfw/commit/5b3aa7fe30ce46bb8f112a9544548da926cb3714);
* Both Tempesta and Nginx run on the same physical test server with 12 CPU cores and 64Gb RAM;
* Simplest Tempesta configuration:
```
server 127.0.0.1:8080
```

The configuration means that Tempesta bypasses cache on all requests. All requests are forwarded to the back-end server without exceptions.

The test is a simple `wrk -t 8 -c 1024 -d 600s http://192.168.0.1`. It runs on another physical machine with 8 CPU cores and 32Gb RAM. It is connected with the test server via 10G interface.

After each run of the above test the main server with Tempesta loses several gigabytes of RAM. Eventually all RAM on the main test server is exhausted and OOM is triggered, which effectively makes the test server unusable.

_Please note that the issue doesn't appear to present itself in a setup where Tempesta and Nginx run in the same VM, and the test is run on the host machine against Tempesta in the VM._

This is the final state of RAM on the test machine at the time of OOM. It also shows an approximate time it took to exhaust all memory.
```
top - 10:32:16 up 49 min,  1 user,  load average: 2.64, 2.11, 1.40
Tasks: 198 total,   1 running, 197 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  1.2 sy,  0.0 ni, 97.8 id,  0.4 wa,  0.0 hi,  0.6 si,  0.0 st
KiB Mem:  65326760 total, 64993280 used,   333480 free,      520 buffers
KiB Swap:  7998460 total,  2595384 used,  5403076 free.     1456 cached Mem
```

This shows the OOM triggered:
```
[  283.701873] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff88103e000000
[  283.910192] [tdb] Opened table /opt/tempesta/db/cache.tdb: size=268435456 rec_size=0 base=ffff88102e000000
[  283.919917] [tempesta] Open listen socket on: 0.0.0.0
[  283.925812] [tempesta] modules are started
[ 2949.269612] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.270234] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.270417] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.270623] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.270630] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.270834] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.270969] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.271014] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.271098] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.271151] [sync_sockets] Warning: Unable to copy an egress SKB.
[ 2949.291179] TCP: request_sock_TCP: Possible SYN flooding on port 80. Dropping request.  Check SNMP counters.
[ 2950.262468] systemd invoked oom-killer: gfp_mask=0x24201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), order=0, oom_score_adj=0
[ 2950.273099] systemd cpuset=/ mems_allowed=0
[ 2950.277342] CPU: 10 PID: 1 Comm: systemd Tainted: G           O    4.8.15-debug-ab+ #6
[ 2950.285268] Hardware name: Supermicro Super Server/X10SRH-CF, BIOS 2.0 12/17/2015
[ 2950.292757]  0000000000000286 00000000c03e5379 ffff8810182b3a20 ffffffff813167c5
[ 2950.300219]  ffff8810182b3bf8 ffff881013ad8000 ffff8810182b3a98 ffffffff81213905
[ 2950.307691]  ffffffff81c54a20 ffff8810182b3a48 ffffffff810c4bdd ffff8810182b3a68
[ 2950.315154] Call Trace:
[ 2950.317607]  [<ffffffff813167c5>] dump_stack+0x68/0x93
[ 2950.322754]  [<ffffffff81213905>] dump_header+0x5c/0x22e
[ 2950.328077]  [<ffffffff810c4bdd>] ? trace_hardirqs_on+0xd/0x10
[ 2950.333918]  [<ffffffff81185112>] oom_kill_process+0x212/0x3e0
[ 2950.339759]  [<ffffffff810782f7>] ? has_capability_noaudit+0x17/0x20
[ 2950.346122]  [<ffffffff81185854>] out_of_memory+0x524/0x540
[ 2950.351701]  [<ffffffff8118551e>] ? out_of_memory+0x1ee/0x540
[ 2950.357458]  [<ffffffff8118b5a8>] __alloc_pages_nodemask+0xf28/0xf60
[ 2950.363821]  [<ffffffff811e2ce1>] alloc_pages_current+0xa1/0x1d0
[ 2950.370203]  [<ffffffff8117f1e9>] __page_cache_alloc+0x129/0x150
[ 2950.376590]  [<ffffffff811803ec>] ? pagecache_get_page+0x2c/0x250
[ 2950.383070]  [<ffffffff81182c6d>] filemap_fault+0x32d/0x600
[ 2950.389030]  [<ffffffff81182da3>] ? filemap_fault+0x463/0x600
[ 2950.395168]  [<ffffffffa0156ba6>] ext4_filemap_fault+0x36/0x50 [ext4]
[ 2950.402004]  [<ffffffff811bb657>] __do_fault+0x87/0x160
[ 2950.407615]  [<ffffffff811bfc73>] handle_mm_fault+0x1003/0x1430
[ 2950.413925]  [<ffffffff811becc5>] ? handle_mm_fault+0x55/0x1430
[ 2950.420239]  [<ffffffff8105615a>] __do_page_fault+0x1fa/0x4e0
[ 2950.426371]  [<ffffffff8105644c>] do_page_fault+0xc/0x10
[ 2950.432068]  [<ffffffff815fbc32>] page_fault+0x22/0x30
[ 2950.437603] Mem-Info:
[ 2950.440738] active_anon:0 inactive_anon:23 isolated_anon:0
[ 2950.440738]  active_file:90 inactive_file:0 isolated_file:0
[ 2950.440738]  unevictable:0 dirty:1 writeback:32 unstable:0
[ 2950.440738]  slab_reclaimable:3954 slab_unreclaimable:17272
[ 2950.440738]  mapped:0 shmem:5 pagetables:2310 bounce:0
[ 2950.440738]  free:80251 free_pcp:184 free_cma:0
[ 2950.476886] Node 0 active_anon:0kB inactive_anon:76kB active_file:148kB inactive_file:56kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:0kB dirty:4kB writeback:128kB shmem:0kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 20kB writeback_tmp:0kB unstable:0kB pages_scanned:2259 all_unreclaimable? yes
[ 2950.508068] Node 0 DMA free:15880kB min:16kB low:28kB high:40kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15972kB managed:15888kB mlocked:0kB slab_reclaimable:0kB slab_unreclaimable:8kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[ 2950.541536] lowmem_reserve[]: 0 1296 63755 63755
[ 2950.547643] Node 0 DMA32 free:250700kB min:1372kB low:2696kB high:4020kB active_anon:40kB inactive_anon:104kB active_file:156kB inactive_file:152kB unevictable:0kB writepending:0kB present:1965536kB managed:1352772kB mlocked:0kB slab_reclaimable:32kB slab_unreclaimable:552kB kernel_stack:48kB pagetables:288kB bounce:0kB free_pcp:240kB local_pcp:0kB free_cma:0kB
[ 2950.584171] lowmem_reserve[]: 0 0 62459 62459
[ 2950.590230] Node 0 Normal free:53856kB min:66192kB low:130148kB high:194104kB active_anon:0kB inactive_anon:0kB active_file:116kB inactive_file:100kB unevictable:0kB writepending:0kB present:65011712kB managed:63958100kB mlocked:0kB slab_reclaimable:15784kB slab_unreclaimable:69008kB kernel_stack:4176kB pagetables:8952kB bounce:0kB free_pcp:528kB local_pcp:120kB free_cma:0kB
[ 2950.628359] lowmem_reserve[]: 0 0 0 0
[ 2950.633771] Node 0 DMA: 0*4kB 1*8kB (U) 0*16kB 0*32kB 2*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15880kB
[ 2950.650356] Node 0 DMA32: 87*4kB (UM) 74*8kB (UM) 60*16kB (UM) 33*32kB (UME) 27*64kB (UME) 14*128kB (ME) 4*256kB (ME) 3*512kB (UME) 8*1024kB (UME) 6*2048kB (UME) 54*4096kB (M) = 250700kB
[ 2950.670416] Node 0 Normal: 489*4kB (ME) 298*8kB (UME) 241*16kB (MEH) 558*32kB (UME) 149*64kB (UME) 50*128kB (UME) 22*256kB (UME) 8*512kB (UM) 2*1024kB (M) 0*2048kB 0*4096kB = 53764kB
[ 2950.689703] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[ 2950.699738] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[ 2950.699740] 166 total pagecache pages
[ 2950.699741] 34 pages in swap cache
[ 2950.699743] Swap cache stats: add 842961, delete 842927, find 174110/294022
[ 2950.699744] Free swap  = 5402536kB
[ 2950.699745] Total swap = 7998460kB
[ 2950.699961] 16748305 pages RAM
[ 2950.699962] 0 pages HighMem/MovableOnly
[ 2950.699963] 416615 pages reserved
[ 2950.699963] 0 pages hwpoisoned
[ 2950.699976] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[ 2950.700022] [  279]     0   279     8233        0      20       3       77             0 systemd-journal
[ 2950.700028] [  281]     0   281     9992        1      21       3      137         -1000 systemd-udevd
[ 2950.700064] [  686]     0   686     6883        0      18       3       78             0 cron
[ 2950.700086] [  692]     0   692    13795        0      32       3      178         -1000 sshd
[ 2950.700089] [  704]     0   704     4953        0      16       3       77             0 systemd-logind
[ 2950.700093] [  771]   107   771    10527        0      25       3       97          -900 dbus-daemon
[ 2950.700108] [  777]   104   777     8346        0      21       3      169             0 ntpd
[ 2950.700113] [  781]     0   781    64663        0      27       4      271             0 rsyslogd
[ 2950.700130] [  795]     0   795     1054        0       8       3       36             0 acpid
[ 2950.700133] [  823]     0   823    22795        0      42       3      306             0 nginx
[ 2950.700137] [  825]    33   825   102298        0     199       4    79814             0 nginx
[ 2950.700152] [  828]    33   828   102298        0     199       4    79806             0 nginx
[ 2950.700173] [  829]    33   829   108056        0     210       4    85579             0 nginx
[ 2950.700176] [  832]    33   832   102298        0     199       4    79808             0 nginx
[ 2950.700195] [  834]    33   834   102298        0     199       4    79816             0 nginx
[ 2950.700216] [  835]    33   835   102298        0     199       4    79823             0 nginx
[ 2950.700219] [  837]    33   837   102298        0     199       4    79822             0 nginx
[ 2950.700222] [  839]    33   839   102298        0     199       4    79820             0 nginx
[ 2950.700237] [  881]     0   881     3630        0      11       3       38             0 agetty
[ 2950.700241] [  882]     0   882     9039        0      22       3      156             0 master
[ 2950.700244] [  883]   106   883     9555        0      24       3      137             0 pickup
[ 2950.700259] [  884]   106   884     9567        0      23       3      138             0 qmgr
[ 2950.700262] [  885]     0   885     3574        0      11       3       35             0 agetty
[ 2950.700266] [  891]     0   891    19424        0      44       3      316             0 apache2
[ 2950.700281] [  894]    33   894    91716        0      73       3      390             0 apache2
[ 2950.700287] [  922]    33   922    91716        0      73       3      391             0 apache2
[ 2950.700303] [  957]     0   957    20681        0      44       3      240             0 sshd
[ 2950.700325] [  959]     0   959     6060        1      18       3      707             0 bash
[ 2950.700329] [ 3500]   106  3500    10611        0      25       3      170             0 tlsmgr
[ 2950.700332] [ 3544]     0  3544     6489        0      17       3      173             0 top
[ 2950.700348] [ 3768]   106  3768    11212        0      28       3      221             0 smtpd
```

### PR DESCRIPTION
**Pull request by krizhanovsky**
Fix #691: free() skbs in ss_tx_action() is a connection is dead;
Fix memory corruption in __copy_ip_header(): don't write IP header after reserved, and only allocated, skb room;
Use native Linux skb_entail();
Add assertions to debug #692;
Don't use virt_to_head_page() if we're unsure that the page is heading.

### CODE REVIEW

File: tempesta_fw/sock.c [hunk 1]
```diff
@@ -1355,6 +1338,9 @@ ss_tx_action(void)
 		}
 dead_sock:
 		sock_put(sk); /* paired with push() calls */
+		while ((skb = ss_skb_dequeue(&sw.skb_list)))
+			kfree_skb(skb);
```
Comment (ikoveshnikov) [inline tempesta_fw/sock.c]: Good catch! Now i see why the memory leak appeared for me in situations with heavy failovering.

File: tempesta_fw/ss_skb.c [hunk 2]
```diff
@@ -1010,7 +1016,7 @@ ss_skb_queue_coalesce_tail(SsSkbList *skb_list, const struct sk_buff *skb)
 	if (headlen) {
 		BUG_ON(!skb->head_frag);
 		head_frag.size = headlen;
-		head_frag.page.p = virt_to_head_page(skb->head);
+		head_frag.page.p = virt_to_page(skb->head);
```
Comment (keshonok) [inline tempesta_fw/ss_skb.c]: I don't think there's a difference, but nevertheless, what is the reason for the change? These are definitely SKBs that are allocated by Tempesta to hold data from the original SKB. That means these SKBs are allocated by Tempesta's SKB allocator in the kernel, where SKB structure itself and the head are page fragments, and they are addressed exactly this way: https://github.com/tempesta-tech/linux-4.9.35-tfw/blob/master/net/core/skbuff.c#L489.

Is there a case where `skb->head` is not a head page? Perhaps, a better comment/explanation is in order?

File: tempesta_fw/ss_skb.c [hunk 3]
```diff
@@ -1036,12 +1042,18 @@ __copy_ip_header(struct sk_buff *to, const struct sk_buff *from)
...
 	const struct ipv6hdr *ip6 = ipv6_hdr(from);
 
+	/*
+	 * Place IP header just after link layer headers,
+	 * see definitions of MAX_TCP_HEADER and MAX_IP_HDR_LEN.
+	 * Note that only new skbs allocated by ss_skb_alloc() are used here,
+	 * so all of them have reserved MAX_TCP_HEADER areas.
+	 */
+	BUG_ON(skb_headroom(to) < MAX_TCP_HEADER);
+	skb_set_network_header(to, -128);
```
Comment (keshonok) [inline tempesta_fw/ss_skb.c]: Perhaps, there's another way of doing this other than doing a subtraction of *_magic_* number. Like, `MAX_TCP_HEADER - MAX_HEADER`?

File: tempesta_fw/ss_skb.c [hunk 4]
```diff
@@ -1036,12 +1042,18 @@ __copy_ip_header(struct sk_buff *to, const struct sk_buff *from)
...
 	if (ip6->version == 6)
-		memcpy(to->data, ip6, sizeof(*ip6));
+		memcpy(skb_network_header(to), ip6, sizeof(*ip6));
 	else
-		memcpy(to->data, ip4, sizeof(*ip4));
-
-	skb_reset_network_header(to);
+		memcpy(skb_network_header(to), ip4, sizeof(*ip4));
```
Comment (keshonok) [inline tempesta_fw/ss_skb.c]: This is an interesting case, and an excellent catch! The IP header data is used in a number of places in Tempesta, and thus it could have been a complete trash!

File: tempesta_fw/sock.c (hunk 1 above)
Comment (keshonok) [reply tempesta_fw/sock.c]: Indeed. Thanks for catching this! I feel much better now.

File: linux-4.9.35.patch [hunk 5]
```diff
@@ -980,21 +982,26 @@ index fe008f1..d5b7bcf 100644
...
++	 */
++	gfp_mask |= __GFP_NOWARN | __GFP_NORETRY | (po ? __GFP_COMP : 0);
 +	pg = alloc_pages_node(node, gfp_mask, po);
 +	if (!pg)
 +		return NULL;
 +	ptr = (char *)page_address(pg);
 +	/*
-+	 * Don't try to split compound page.
++	 * Don't try to split compound page. Also don't try to reuse pages
++	 * from reserved memory areas making them putted and freed quicker.
```
Comment (keshonok) [inline linux-4.9.35.patch]: `putted` -> `put`. Also, perhaps: `making them to be put or freed quicker`.

File: tempesta_fw/ss_skb.c (hunk 2 above)
Comment (krizhanovsky) [reply tempesta_fw/ss_skb.c]: @keshonok thank you for the notes. Strictly speaking `skb->head` can be a tail page, so here we'd get wrong page. However, since we set offset, we set correct offset from the head page and everything works fine. However, the code is misleading and bit-bit slower - just has no sense to keep the bad code.
