### PR TITLE
remove request from seq_list when errors occur

### LINKED ISSUE #1099: Kernel oops on pipelined requests
`tempesta_fw.conf`:
```
listen 80;
server 192.168.122.1:80;
```
Backend server: Apache 2.4.37, outside Tempesta VM.

When sending pipelined requests with
```
while true; do echo -en "GET /dump.php HTTP/1.1\r\nHost: loc\r\nCookie: __tfw=0000000100532f544adae29e04f752b3b1aff1cb57073da8375a0fa1\r\nConnection: keep-alive\r\n\r\n"; done | nc tempesta-vm.lan 80
```
a kernel oops was observed:
```
[   73.116516] [tempesta] Warning: request dropped: forwarding error, status 500: 192.168.122.1
[   73.211447] [tempesta] Warning: request dropped: processing error, status 502: 192.168.122.1
[   73.215167] [tempesta] Warning: request dropped: processing error, status 502: 192.168.122.1
[   73.218914] [tempesta] Warning: request dropped: processing error, status 502: 192.168.122.1
[   73.222709] [tempesta] Warning: request dropped: processing error, status 502: 192.168.122.1
[   73.226514] [tempesta] Warning: request dropped: processing error, status 502: 192.168.122.1
[   73.230668] [tempesta] Warning: request dropped: processing error, status 502: 192.168.122.1
[   73.234960] [tempesta] Warning: request dropped: processing error, status 502: 192.168.122.1
[   73.238952] [tempesta] Warning: request dropped: processing error, status 502: 192.168.122.1
[   73.243059] [tempesta] Warning: request dropped: processing error, status 502: 192.168.122.1
[   73.574413] ------------[ cut here ]------------
[   73.576723] WARNING: CPU: 2 PID: 19 at /root/tempesta/tempesta_fw/http.c:1638 tfw_http_req_destruct+0x69/0x80 [tempesta_fw]
[   73.581525] Modules linked in: tempesta_fw(O) tempesta_db(O) tempesta_tls(O) tempesta_lib(O) 9p fscache 9pnet virtio_balloon virtio_console virtio_net virtio_pci virtio_ring virtio
[   73.588295] CPU: 2 PID: 19 Comm: ksoftirqd/2 Tainted: G           O    4.14.32+ #1
[   73.591867] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.11.1-1 04/01/2014
[   73.595832] task: ffffa1bb9ab74740 task.stack: ffffa76dc06d8000
[   73.598912] RIP: 0010:tfw_http_req_destruct+0x69/0x80 [tempesta_fw]
[   73.601942] RSP: 0018:ffffa76dc06db800 EFLAGS: 00010287
[   73.604328] RAX: ffffa1bb378d7020 RBX: ffffa1bb378d3020 RCX: 0000000000000000
[   73.607019] RDX: 0000000000000000 RSI: 0000000000023bc0 RDI: ffffa1bb378d3020
[   73.609681] RBP: ffffa1bb378d3020 R08: ffffa1bb2faa6600 R09: 000000010010000f
[   73.612352] R10: ffffa76dc06db7c8 R11: ffffa1bbbfffa501 R12: ffffa76dc06db820
[   73.615167] R13: ffffa1bb378d7020 R14: ffffa1bb95a280b4 R15: ffffa1bb378d3020
[   73.617950] FS:  0000000000000000(0000) GS:ffffa1bbbfd00000(0000) knlGS:0000000000000000
[   73.621703] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   73.624174] CR2: 00007f40cfcf15d8 CR3: 00000000a880a005 CR4: 00000000003606e0
[   73.627061] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   73.629931] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   73.632770] Call Trace:
[   73.634335]  tfw_http_msg_free+0x8a/0xb0 [tempesta_fw]
[   73.636608]  tfw_http_resp_fwd+0x1eb/0x2a0 [tempesta_fw]
[   73.638928]  ? tfw_http_req_cache_cb+0x310/0x310 [tempesta_fw]
[   73.641425]  tfw_cache_do_action+0x320/0xd50 [tempesta_fw]
[   73.643791]  ? __try_str.isra.7+0x56/0xa0 [tempesta_fw]
[   73.646081]  ? __parse_connection+0x2a6/0x3f0 [tempesta_fw]
[   73.648387]  ? __str_grow_tree+0x71/0xf0 [tempesta_fw]
[   73.650568]  ? tfw_hash_str+0xc9/0x120 [tempesta_fw]
[   73.652732]  ? tfw_http_req_cache_cb+0x310/0x310 [tempesta_fw]
[   73.655323]  tfw_cache_process+0xa7/0x280 [tempesta_fw]
[   73.657784]  ? tfw_gfsm_move+0x12d/0x160 [tempesta_fw]
[   73.660321]  ? recalibrate_cpu_khz+0x10/0x10
[   73.662449]  tfw_http_resp_cache+0xae/0x150 [tempesta_fw]
[   73.664912]  tfw_http_msg_process+0x8af/0xa70 [tempesta_fw]
[   73.667407]  ? ip_output+0x59/0xc0
[   73.669278]  ? ip_output+0x59/0xc0
[   73.671153]  ? ip_fragment.constprop.54+0x70/0x70
[   73.673385]  __gfsm_fsm_exec+0x51/0x90 [tempesta_fw]
[   73.675699]  tfw_connection_recv+0x39/0x40 [tempesta_fw]
[   73.678100]  ? tfw_connection_send+0x20/0x20 [tempesta_fw]
[   73.680565]  ss_tcp_process_data+0x1c0/0x410 [tempesta_fw]
[   73.683027]  ss_tcp_data_ready+0x3e/0x80 [tempesta_fw]
[   73.685411]  tcp_data_queue+0x4ca/0xc20
[   73.687446]  tcp_rcv_established+0x250/0x540
[   73.689732]  tcp_v4_do_rcv+0x124/0x1c0
[   73.691776]  tcp_v4_rcv+0x8c1/0x9b0
[   73.693677]  ip_local_deliver_finish+0x6b/0x190
[   73.695874]  ip_local_deliver+0x56/0xc0
[   73.697875]  ? ip_rcv_finish+0x340/0x340
[   73.699910]  ip_rcv+0x24f/0x370
[   73.701702]  ? inet_del_offload+0x30/0x30
[   73.703756]  __netif_receive_skb_core+0x318/0xb00
[   73.705996]  ? process_backlog+0x92/0x120
[   73.708043]  process_backlog+0x92/0x120
[   73.710033]  net_rx_action+0x23d/0x380
[   73.712028]  __do_softirq+0x104/0x297
[   73.713989]  run_ksoftirqd+0x14/0x30
[   73.715953]  smpboot_thread_fn+0x109/0x160
[   73.718033]  kthread+0xfa/0x130
[   73.719989]  ? sort_range+0x20/0x20
[   73.721999]  ? kthread_create_on_node+0x40/0x40
[   73.724208]  ret_from_fork+0x35/0x40
[   73.726134] Code: 48 c7 c0 ff ff ff ff f0 48 0f c1 47 38 48 83 f8 01 74 20 48 8b bb 58 03 00 00 48 85 ff 74 06 5b e9 0d e2 01 00 5b c3 0f 0b eb c9 <0f> 0b eb 9f 0f 0b eb ae e8 7a 0c 03 00 eb d9 0f 1f 84 00 00 00 
[   73.733909] ---[ end trace 09f2be7d01a5ae49 ]---
```

On the backend server, script `dump.php` prints request details. Amongst them, `X-Forwarded-For` header field has suspicious values. They vary from one response to another, and contain unexpected data. Here are some of them:
```
headers
Array
(
    [Host] => loc
    [Cookie] => __tfw=0000000100532f544adae29e04f752b3b1aff1cb57073da8375a0fa1
    [Connection] => keep-alive
    [Via] => 1.1 tempesta_fw (Tempesta FW 0.6.0)
    [X-Forwarded-For] => 65.131.228.1
)
```
```
headers
Array
(
    [Host] => loc
    [Cookie] => __tfw=0000000100532f544adae29e04f752b3b1aff1cb57073da8375a0fa1
    [Connection] => keep-alive
    [Via] => 1.1 tempesta_fw (Tempesta FW 0.6.0)
    [X-Forwarded-For] => 15.31.64.0
)
```
```
headers
Array
(
    [Host] => loc
    [Cookie] => __tfw=0000000100532f544adae29e04f752b3b1aff1cb57073da8375a0fa1
    [Connection] => keep-alive
    [Via] => 1.1 tempesta_fw (Tempesta FW 0.6.0)
    [X-Forwarded-For] => 0.0.0.0
)
```

Expected behavior: no oops'es; consistent `X-Forwarded-For`.

### PR DESCRIPTION
**Pull request by i-rinat**
Adds missing error handling. If a request cannot be forwarded, it's dropped. In that case we need to remove it from the connection's queue.

(fixes #1099)

### CODE REVIEW

File: tempesta_fw/http.c [hunk 1]
```diff
@@ -2347,6 +2349,9 @@ tfw_http_resp_fwd(TfwHttpResp *resp)
 			TFW_DBG2("%s: Forwarding error: conn=[%p] resp=[%p]\n",
 				 __func__, cli_conn, req->resp);
 			BUG_ON(!req->resp);
+			spin_lock_bh(&cli_conn->seq_qlock);
+			list_del_init(&req->msg.seq_list);
+			spin_unlock_bh(&cli_conn->seq_qlock);
 			tfw_http_resp_pair_free(req);
```
Comment (krizhanovsky) [inline tempesta_fw/http.c]: Do we need the loop if we deleted all the requests in the patch above? Maybe it makes sense to write 2 lines instead of 4?
```C
tfw_http_conn_msg_free(req->pair);
tfw_http_conn_req_clean(req);
```

File: tempesta_fw/http.c [hunk 2]
```diff
@@ -2241,6 +2241,8 @@ __tfw_http_resp_fwd(TfwCliConn *cli_conn, struct list_head *ret_queue)
 		BUG_ON(!req->resp);
 		tfw_http_resp_init_ss_flags(req->resp, req);
 		if (tfw_cli_conn_send(cli_conn, (TfwMsg *)req->resp)) {
+			list_del_init(&req->msg.seq_list);
+			tfw_http_resp_pair_free(req);
```
[the remark this answers is not in the document]
Comment (ikoveshnikov) [reply tempesta_fw/http.c]: Correct, `tfw_http_resp_fwd()` takes care on unforwarded responses, and all the responses are destroyed there. The new line `list_del_init(&req->msg.seq_list);` was missed there thought, so #1099 happen. This exact lines are not required here since we still do the same later during error handling at the end of `tfw_http_resp_fwd()` .

File: tempesta_fw/http.c [hunk 3]
```diff
@@ -2347,6 +2349,9 @@ tfw_http_resp_fwd(TfwHttpResp *resp)
 			TFW_DBG2("%s: Forwarding error: conn=[%p] resp=[%p]\n",
 				 __func__, cli_conn, req->resp);
 			BUG_ON(!req->resp);
+			spin_lock_bh(&cli_conn->seq_qlock);
+			list_del_init(&req->msg.seq_list);
+			spin_unlock_bh(&cli_conn->seq_qlock);
```
Comment (ikoveshnikov) [inline tempesta_fw/http.c]: The list passed to `__tfw_http_resp_fwd()` is not `cli_conn->seq_queue`. The `ret_queue` is cut from `cli_conn->seq_queue`: https://github.com/tempesta-tech/tempesta/blob/774869c747ebf726135b0c210050482c880d20e6/tempesta_fw/http.c#L2305
So the `req` is not a member of `cli_conn->seq_queue`, and the spinlock is not required here.

Comment (i-rinat) [reply tempesta_fw/http.c]: Indeed. Removed.

File: tempesta_fw/http.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (i-rinat) [reply tempesta_fw/http.c]: > why do we need to free requests and responses here? Don't we need to adjust or completely remove the loop at the end of tfw_http_resp_fwd()?

It's possible to move all the lines from the loop to `__tfw_http_resp_fwd()`, but there will be no simplification other than moving all reclamation code together. Now two sites are apart from each another. That's slightly confusing. However, that much is fine.

**Comment by i-rinat** [comment]
Updated patch according to the comments. Now it's just single `list_del_init(&req->msg.seq_list);`.
