### PR TITLE
Fix long work test on big server

### LINKED ISSUE #2222: Tempesta unittests crash
# Scope

HEAD 6a11731196b15818d47881e726d220151d01fd67

Server: bare metal, SUT, Linux sut 5.10.35.tfw-1d07dc5 #1 SMP Thu Jun 27 15:40:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

- Reboot the machine
- run `make clean`
- run `make -j`
- run `make test`

Unit Tests are working endlessly (as by hand, as with our CI). If they are interrupted, Tempesta will not be started until a machine is rebooted. 

When Tempesta cannot start after the failed unittests [log_tempesta_cannot_start.txt](https://github.com/user-attachments/files/16731864/log_tempesta_cannot_start.txt)

Dmesg logs for the failed unittests 
[dmesg-Aug-23-2024.txt](https://github.com/user-attachments/files/16731872/dmesg-Aug-23-2024.txt)

# Testing

Unittests

# Documentation

If Tempesta FW behavior or configuration is changed, then please update the [Wiki](https://github.com/tempesta-tech/tempesta/wiki). Don't forget about our [documentation guidelines](https://github.com/tempesta-tech/tempesta/wiki/Development-Guidelines#documentation).

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
There is no crash in unittests described in #2222
- everything is ok, but test works too long (about 30 minutes), because of a lot of cpu in system. Fix test
- now if count of cpu is greater then 32 count of workers == count of cpu not count of cpu * 10.

Closes #2222

### CODE REVIEW

**Review by krizhanovsky — APPROVED** [review]
LGTM

File: fw/t/unit/test_wq.c [hunk 1]
```diff
@@ -297,9 +297,18 @@ TEST(wq, one_prod_one_con)
...
+	 * time (about 30 minutes if num_online_cpus == 112 for
+	 * example).
+	 */
+	size_t n = num_online_cpus() < 32
+		? JOB_N * num_online_cpus()
+		: num_online_cpus();
+	tfw_test_wq_test(n, 1);
 }
 
+
```
Comment (const-t) [inline fw/t/unit/test_wq.c:311]: Extra line break

**Review by const-t — APPROVED** [review]
LGTM. Seems single consumer can't pop items for the reasonable time in case a lot of cpus.
