### PR TITLE
fix remaining active socket in state SYN-SENT

### LINKED ISSUE #751: Using server behind firewall cause kernel crash after shutdown
Issue happens when TempestaFW is configured to use server behind firewall. This does not happen when TempestaFW is configured to used offline server.

Configuration: 2 hosts: one for TempestaFW, one - for backend server ().

TempestaFW host: ip address is `192.168.122.12`, configuration is below.
```
server 192.168.122.185:8000;
```

Backend server host: ip address is `192.168.122.185`, http server is configured for port `8000`, but netfilter is configured to block port `8000` as below.
```
sudo iptables -A INPUT -p tcp --destination-port 8000 -j DROP
```

Steps to reproduce:
* Start TempestaFW;
* Wait for some time, around ~30 secs;
* Stop TempestaFW;
* Wait around 120 seconds;
* Crash happen.

Kernel log:
```
[ 1947.907213] [tempesta] Stopping all modules...
[ 1948.037319] [tdb] Close table 'cache0.tdb'
[ 1948.051579] [tdb] Close table 'filter0.tdb'
[ 1953.054592] [sync_sockets] Warning: pending active connections for 5s (connections count 0x2000000000)
[ 1953.059089] [tempesta] Un-registering scheduler: hash
[ 1953.097776] [tempesta] Un-registering scheduler: http
[ 1953.136307] [tempesta] Un-registering scheduler: ratio
[ 1953.169948] [tempesta] exiting...
[ 1953.232147] [tdb] Shutdown Tempesta DB
[ 2045.090382] BUG: unable to handle kernel paging request at ffffffffc086e3f0
[ 2045.095600] IP: [<ffffffffc086e3f0>] 0xffffffffc086e3f0
[ 2045.099337] PGD 5aa09067 PUD 5aa0b067 PMD 3653a067 PTE 0
[ 2045.101703] Oops: 0010 [#1] SMP
[ 2045.102597] Modules linked in: crct10dif_pclmul(E) crc32_pclmul(E) snd_hda_codec_generic(E) iTCO_wdt(E) iTCO_vendor_support(E) ghash_clmulni_intel(E) ppdev(E) snd_hda_intel(E) snd_hda_codec(E) snd_hda_core(E) snd_hwdep(E) evdev(E) snd_pcm(E) pcspkr(E) serio_raw(E) snd_timer(E) snd(E) soundcore(E) lpc_ich(E) qxl(E) mfd_core(E) sg(E) virtio_balloon(E) virtio_console(E) ttm(E) drm_kms_helper(E) parport_pc(E) parport(E) drm(E) shpchp(E) acpi_cpufreq(E) tpm_tis(E) tpm_tis_core(E) tpm(E) button(E) ip_tables(E) x_tables(E) autofs4(E) ext4(E) crc16(E) jbd2(E) crc32c_generic(E) fscrypto(E) ecb(E) mbcache(E) sr_mod(E) cdrom(E) crc32c_intel(E) virtio_blk(E) ahci(E) libahci(E) virtio_net(E) aesni_intel(E) aes_x86_64(E) glue_helper(E) lrw(E) gf128mul(E) ablk_helper(E) cryptd(E) psmouse(E) i2c_i801(E) i2c_smbus(E) libata(E) ehci_pci(E) uhci_hcd(E) ehci_hcd(E) usbcore(E) usb_common(E) sym53c8xx(E) scsi_transport_spi(E) scsi_mod(E) virtio_pci(E) virtio_ring(E) virtio(E) [last unloaded: tempesta_tls]
[ 2045.123664] CPU: 1 PID: 0 Comm: swapper/1 Tainted: G           OE   4.8.0-tempesta-amd64 #1 Debian 4.8.15-tfw2-1
[ 2045.125623] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.10.2-20170228_101828-anatol 04/01/2014
[ 2045.128226] task: ffffa1809c8d0e80 task.stack: ffffa1809c8e0000
[ 2045.129023] RIP: 0010:[<ffffffffc086e3f0>]  [<ffffffffc086e3f0>] 0xffffffffc086e3f0
[ 2045.130456] RSP: 0018:ffffa180bfd03e38  EFLAGS: 00010246
[ 2045.131427] RAX: ffffffffc086e3f0 RBX: ffffa1809c027080 RCX: 0000000000000000
[ 2045.132714] RDX: 0000000180400028 RSI: ffffa1809c027268 RDI: ffffa1809c027080
[ 2045.134016] RBP: ffffa1809c027108 R08: ffffa18099735d40 R09: 0000000180400027
[ 2045.135320] R10: ffffa18099735b00 R11: 0000000000000000 R12: 0000000000000100
[ 2045.136607] R13: ffffffffbe153050 R14: ffffa1809c027080 R15: 0000000000000000
[ 2045.137650] FS:  0000000000000000(0000) GS:ffffa180bfd00000(0000) knlGS:0000000000000000
[ 2045.139121] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 2045.139891] CR2: ffffffffc086e3f0 CR3: 0000000058ae8000 CR4: 00000000003406e0
[ 2045.141200] Stack:
[ 2045.141579]  ffffffffbe15201d ffffa1809c027080 ffffffffbe152f06 ffffa1809c027080
[ 2045.142983]  ffffa1809c027108 ffffffffbe1530b0 0000000000000001 ffffa1809c027458
[ 2045.144381]  ffffffffbdce51d0 0000000000000001 ffffa1809c027458 ffffa180bfd0fdc0
[ 2045.146005] Call Trace:
[ 2045.146554]  <IRQ> 
[ 2045.146994]  [<ffffffffbe15201d>] ? tcp_write_err+0x2d/0x50
[ 2045.148072]  [<ffffffffbe152f06>] ? tcp_write_timer_handler+0x86/0x1d0
[ 2045.149489]  [<ffffffffbe1530b0>] ? tcp_write_timer+0x60/0x70
[ 2045.150775]  [<ffffffffbdce51d0>] ? call_timer_fn+0x30/0x110
[ 2045.152318]  [<ffffffffbdce573a>] ? run_timer_softirq+0x20a/0x4a0
[ 2045.153671]  [<ffffffffbdcf5fe0>] ? tick_sched_handle.isra.12+0x50/0x50
[ 2045.155096]  [<ffffffffbdcf5fb0>] ? tick_sched_handle.isra.12+0x20/0x50
[ 2045.156595]  [<ffffffffbdcf6018>] ? tick_sched_timer+0x38/0x70
[ 2045.157870]  [<ffffffffbe1f8223>] ? __do_softirq+0x113/0x2a6
[ 2045.159233]  [<ffffffffbdc7f7eb>] ? irq_exit+0x9b/0xa0
[ 2045.160630]  [<ffffffffbe1f802e>] ? smp_apic_timer_interrupt+0x3e/0x50
[ 2045.162346]  [<ffffffffbe1f7342>] ? apic_timer_interrupt+0x82/0x90
[ 2045.163868]  <EOI> 
[ 2045.164344]  [<ffffffffbdc59012>] ? native_safe_halt+0x2/0x10
[ 2045.165794]  [<ffffffffbdc2f6ea>] ? default_idle+0x1a/0xd0
[ 2045.167133]  [<ffffffffbdcbb7a8>] ? cpu_startup_entry+0x2e8/0x340
[ 2045.168618]  [<ffffffffbdc47f2d>] ? start_secondary+0x14d/0x190
[ 2045.170066] Code:  Bad RIP value.
[ 2045.170875] RIP  [<ffffffffc086e3f0>] 0xffffffffc086e3f0
[ 2045.172068]  RSP <ffffa180bfd03e38>
[ 2045.172850] CR2: ffffffffc086e3f0
```

### PR DESCRIPTION
**Pull request by ikoveshnikov**
fix #751

### CODE REVIEW

File: tempesta_fw/sock.c [hunk 1]
```diff
@@ -1212,13 +1212,26 @@ ss_tx_action(void)
 			__sk_close_locked(sk); /* paired with bh_lock_sock() */
 			break;
 		case SS_CLOSE:
-			if (!ss_sock_live(sk)) {
+			switch (sk->sk_state) {
+			case TCP_ESTABLISHED:
+				__sk_close_locked(sk); /* paired with bh_lock_sock() */
```
Comment (krizhanovsky) [inline tempesta_fw/sock.c]: too long line

File: tempesta_fw/sock_srv.c [hunk 2]
```diff
@@ -181,6 +181,8 @@ tfw_sock_srv_connect_try(TfwSrvConn *srv_conn)
 		return r == SS_SHUTDOWN ? 0 : r;
 	}
 
+	/* Link Tempesta with the socket. */
+	tfw_connection_link_to_sk((TfwConn *)srv_conn, sk);
```
Comment (keshonok) [inline tempesta_fw/sock_srv.c]: Also, it's important here that when Tempesta is stopped, `ss_close_sync(conn->sk, true);` always pushes the request for a close to the work queue, so the closing in never synchronous. That's because Tempesta is stopped while in user context, and the condition `!in_softirq()` makes `__ss_close()` do just that. That way the case of `TCP_SYN_SENT` needs to be handled only in `ss_tx_action()`.

Perhaps, a note in the description of `tfw_sock_srv_disconnect()` would help to understand the intricacies of the behaviour better.

File: tempesta_fw/sock_srv.c [hunk 3]
```diff
@@ -416,13 +417,13 @@ tfw_sock_srv_disconnect(TfwConn *conn)
...
-		if (conn->sk)
-			ret = ss_close_sync(conn->sk, true);
+	if (atomic_read(&conn->refcnt) == TFW_CONN_DEATHCNT)
 		tfw_connection_release(conn);
-	}
-	else {
-		ret = ss_close_sync(conn->sk, true);
+	if (sk) {
+		sock_hold(sk);
+		tfw_connection_unlink_to_sk(conn);
```
Comment (krizhanovsky) [inline tempesta_fw/sock_srv.c]: Again, I'm not sure about correctness of the change. We had many crashes when various contexts resolve already dead `conn->sk`, so now we call `tfw_connection_unlink_to_sk()` on connection destructor only, when `tfw_connection_put()` ensures that there are no more users of the connection. Just removing the link could lead to inconsistencies.

File: tempesta_fw/t/functional/flacky_net/test_sockets.py [hunk 4]
```diff
@@ -0,0 +1,147 @@
+"""All sockets must be closed after Tempesta shutdown"""
```
Comment (ikoveshnikov) [inline tempesta_fw/t/functional/flacky_net/test_sockets.py]: Style guide in Python is not so flexible like in C. Python community forces every developer to use the  official code style described in PEP-8 document https://www.python.org/dev/peps/pep-0008 . Indentation in Python matters a lot since it is used instead old good operator brackets, so the community decided to have the only right variant: 4 spaces, tabs and mixing tabs with spaces are not allowed. Even more the wrong indentation is equal to syntax error in Python 3. `pylint`, the Python linter tool, threats any indentation different from 4 spaces as warnings.

I agree with you, that the whole project must use the same code style. But we can literately do nothing here.

Comment (krizhanovsky) [inline tempesta_fw/t/functional/flacky_net/test_sockets.py]: Well, I don't care about Guido's point of view on how a beauty code must looks like. I just verified that tabs work find for Python3:

```python
$ cat tail_recursion.py 
#!/usr/bin/python3

def tail_factorial(total, n):
	if not n:
		return total
	return tail_factorial(total * n, n - 1)

def tail_factorial2(total, n):
	if not n:
		return total
	return (lambda : tail_factorial2(total * n, n - 1))

def tail_rec(total, n):
	g = tail_factorial2(total, n)
	while hasattr(g, '__call__'):
		total = total * tail_factorial

print(tail_factorial(1, 10))
$ ./tail_recursion.py 
3628800
```

The code used tabs 8 characters in width. It seems Pylint allows to specify what should it use for identation https://stackoverflow.com/questions/25303726/how-to-fix-pylint-wrong-hanging-indentation-and-pep8-e121

**Comment by ikoveshnikov** [comment]
Changes since last review:
* rework of server connection lifetime. All resources attached to server connections will be released once linked socket is closed
* add vim modeline to python files to set correct indentation rules.

File: tempesta_fw/sock_srv.c [hunk 5]
```diff
@@ -174,19 +184,15 @@ tfw_sock_srv_connect_try(TfwSrvConn *srv_conn)
 			TFW_ERR("Unable to initiate a connect to server: %d\n",
 				r);
 		ss_close_sync(sk, false);
+		/* Drop failed connection. */
+		srv_conn->proto.hooks->connection_drop(sk);
```
Comment (keshonok) [inline tempesta_fw/sock_srv.c]: It appears that this is not very clean. For instance, where's a call to `tfw_connection_unlink_from_sk()`? Also, calling `connection_drop()` is not needed when a connection is not live -- see `tfw_sock_srv_connect_failover()`. Also, doing it this way unnecessarily increments the stats count of disconnects.

File: tempesta_fw/t/functional/flacky_net/test_sockets.py [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+        self.check_after_start(True)
+
+        self.filter.drop_on_pors(self.filter_ports)
+        self.force_reconnects()
+        self.check_after_start(False)
+        self.check_after_stop()
+
+    def test_unreachable(self):
+        """Server does not exist and cannot be reached."""
+        self.check_before_start()
```
Comment (krizhanovsky) [inline tempesta_fw/t/functional/flacky_net/test_sockets.py]: The comment is still not addressed.
