### PR TITLE
Fix race in rsa implementation.

### LINKED ISSUE #1779: ttls_rsa_private(ctx, sig, sig_try) returns -17280
# Motivation

While testing with `wrk`, the following TLS warning can be observed in dmesg:
```
[33818.725176] [tempesta fw] Tempesta FW is ready                                                                                                              
[33818.739796] ------------[ cut here ]------------                                                                                                            
[33818.739801] ttls_rsa_private(ctx, sig, sig_try) returns -17280                                                                                              
[33818.739828] WARNING: CPU: 3 PID: 0 at /root/host/tempesta/tls/rsa.c:1192 ttls_rsa_pkcs1_sign+0x109/0x130 [tempesta_tls]                                     
[33818.739831] Modules linked in: tempesta_fw(OE) tempesta_db(OE) tempesta_tls(OE) tempesta_lib(OE) sha256_ssse3 sha512_ssse3 xt_CHECKSUM xt_MASQUERADE xt_conntrack ipt_REJECT nf_reject_ipv4 ip6table_mangle ip6table_nat ip6table_filter ip6_tables iptable_mangle iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 iptable_filter bpfilter bridge stp llc qrtr ns sunrpc vfat fat kvm_intel kvm iTCO_wdt intel_pmc_bxt iTCO_vendor_support irqbypass i2c_i801 input_leds pcspkr lpc_ich i2c_smbus virtiofs virtio_balloon fuse zram ip_tables crct10dif_pclmul crc32_pclmul crc32c_intel virtio_net ghash_clmulni_intel serio_raw net_failover
 virtio_scsi qemu_fw_cfg virtio_blk virtio_console failover ipmi_devintf ipmi_msghandler [last unloaded: tempesta_lib]                                         
[33818.739862] CPU: 3 PID: 0 Comm: swapper/3 Tainted: G        W  OE     5.10.35perf+ #1                                                                       
[33818.739863] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 0.0.0 02/06/2015                                                                       
[33818.739867] RIP: 0010:ttls_rsa_pkcs1_sign+0x109/0x130 [tempesta_tls]                                                                                        
[33818.739869] Code: 4c 89 f7 e8 c9 c3 ca c0 44 89 e8 5b 5d 41 5c 41 5d 41 5e c3 41 bd 00 bd ff ff eb e4 89 c6 48 c7 c7 68 0a 65 c0 e8 15 ff 55 c1 <0f> 0b eb d2 44 89 ee 48 c7 c7 98 0a 65 c0 e8 02 ff 55 c1 0f 0b eb
[33818.739871] RSP: 0018:ffffc90000130930 EFLAGS: 00010286                                                                                                     
[33818.739872] RAX: 0000000000000032 RBX: ffff888126702300 RCX: 0000000000000027                                                                               
[33818.739873] RDX: ffff8881f5f98a88 RSI: 0000000000000001 RDI: ffff8881f5f98a80                                                                               
[33818.739874] RBP: ffff88812715a008 R08: 0000000000000000 R09: ffffc90000130760                                                                               
[33818.739875] R10: ffffc90000130758 R11: ffffffff82d45008 R12: ffff888126d6209d                                                                               
[33818.739876] R13: 00000000ffffbc80 R14: ffff888126702200 R15: ffff88819442a650                                                                               
[33818.739877] FS:  0000000000000000(0000) GS:ffff8881f5f80000(0000) knlGS:0000000000000000                                                                    
[33818.739878] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033                                                                                               
[33818.739879] CR2: 00007efed998b680 CR3: 0000000196800005 CR4: 0000000000770ee0                                                                               
[33818.739882] PKRU: 55555554                                                                                                                                  
[33818.739883] Call Trace:                                                                                                                                     
[33818.739886]  <IRQ>                                                                                                                                          
[33818.739890]  ttls_handshake_server_step+0x1458/0x1dd0 [tempesta_tls]                                                                                        
[33818.739896]  ttls_recv+0x30b/0x770 [tempesta_tls]                                                                                                           
[33818.739908]  ss_skb_process+0xe5/0x120 [tempesta_fw]                                                                                                        
[33818.739911]  ? ttls_handle_alert+0x30/0x30 [tempesta_tls]                                                                                                   
[33818.739918]  tfw_tls_connection_recv+0x94/0x360 [tempesta_fw]                                                                                               
[33818.739925]  ss_tcp_process_data+0x1d9/0x3c0 [tempesta_fw]                                                                                                  
[33818.739931]  ss_tcp_data_ready+0x3f/0xa0 [tempesta_fw]                                                                                                      
[33818.739934]  tcp_data_queue+0x8ab/0xd20                                                                                                                     
[33818.739936]  tcp_rcv_established+0x21c/0x630                                                                                                                
[33818.739938]  tcp_v4_do_rcv+0x131/0x1f0                                                                                                                      
[33818.739939]  tcp_v4_rcv+0xbef/0xd40                                                                                                                         
[33818.739941]  ? nf_hook_slow+0x3f/0xb0                                                                                                                       
[33818.739943]  ip_protocol_deliver_rcu+0x2b/0x1b0                                                                                                             
[33818.739945]  ip_local_deliver_finish+0x44/0x50                                                                                                              
[33818.739947]  __netif_receive_skb_one_core+0x67/0x70                                                                                                         
[33818.739949]  process_backlog+0x98/0x170                                                                                                                     
[33818.739950]  net_rx_action+0x135/0x3b0                                                                                                                      
[33818.739953]  __do_softirq+0xd5/0x297                                                                                                                        
[33818.739955]  asm_call_irq_on_stack+0xf/0x20                                                                                                                 
[33818.739956]  </IRQ>                                                                                                                                         
[33818.739958]  do_softirq_own_stack+0x37/0x40                                                                                                                 
[33818.739961]  irq_exit_rcu+0xc2/0x100                                                                                                                        
[33818.739963]  common_interrupt+0x74/0x130                                                                                                                    
[33818.739964]  asm_common_interrupt+0x1e/0x40                                                                                                                 
[33818.739966] RIP: 0010:native_safe_halt+0xe/0x10                                                                                                             
[33818.739967] Code: c0 7b 01 00 f0 80 4a 02 20 48 8b 12 83 e2 08 75 c3 e9 7a ff ff ff cc cc cc cc cc cc e9 07 00 00 00 0f 00 2d 46 46 60 00 fb f4 <c3> 90 e9 07 00 00 00 0f 00 2d 36 46 60 00 f4 c3 cc cc 0f 1f 44 00
[33818.739969] RSP: 0018:ffffc900000a3ef8 EFLAGS: 00000212                                                                                                     
[33818.739970] RAX: ffffffff81c05c40 RBX: 0000000000000003 RCX: ffff8881f5faad00
[33818.739971] RDX: 0000000000000003 RSI: ffffc900000a3eb8 RDI: 00001ec23efd1866
[33818.739972] RBP: ffff8881202f0000 R08: 0000000000000001 R09: ffff88812a230a00
[33818.739973] R10: 0000000000000150 R11: 0000000000000000 R12: 0000000000000000
[33818.739974] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
[33818.739976]  ? __cpuidle_text_start+0x8/0x8                                                                                                                 
[33818.739979]  default_idle+0xa/0x10                                                                                                                          
[33818.739980]  default_idle_call+0x38/0xc0                                                                                                                    
[33818.739982]  do_idle+0x1e0/0x270                                                                                                                            
[33818.739984]  cpu_startup_entry+0x19/0x20                                                                                                                    
[33818.739985]  secondary_startup_64_no_verify+0xc2/0xcb                                                                                                       
[33818.739987] ---[ end trace f8810af94f2206d7 ]---                                                                                                            
[33818.739990] [tempesta tls] Warning: [::ffff:192.168.122.1] cannot sign the digest, -17280
[33828.827927] [tdb] Close table 'client0.tdb'                                                                                                                 
[33828.834355] [tdb] Close table 'sessions0.tdb'                                                                                                               
[33828.930246] [tdb] Close table 'cache0.tdb'                                                                                                                  
[33828.948326] [tdb] Close table 'filter0.tdb'                                                          
```

This warning is quite rare. It occurred only once during a 30-minute test.

# Scope

The issue can only be reproduced when Tempesta is being constantly reloaded under load. 

# Testing

Tempesta config:
```
listen 443 proto=https;

cache 1;
cache_fulfill * *;

srv_group ngx_local {
        server 127.0.0.1:8000 conns_n=4;
}

vhost f35tfw.local {
        tls_certificate /root/certs/tempesta/RSA/tfw-root.crt;
        tls_certificate_key /root/certs/tempesta/RSA/tfw-root.key;

        #resp_hdr_set Strict-Transport-Security "max-age=31536000; includeSubDomains";

        proxy_pass ngx_local;
}

http_chain {
        -> f35tfw.local;
}
```

Reload Tempesta every 10 seconds:
`while :; do ./scripts/tempesta.sh --restart; sleep 10; done`

Client:
`wrk -d 3600 -c 1000 -t 2 -H 'connection: close' https://f35tfw.local`

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
We should initialize `ctx->RP` and `ctx->RQ`
when we initialize rsa context not during key
signition, because key signition can be called
on different CPUs for one ctx, which lead to race.

Closes #1779, #1892

### CODE REVIEW

File: tls/bignum.c [hunk 1]
```diff
@@ -1446,3 +1442,15 @@ ttls_mpi_inv_mod(TlsMpi *X, const TlsMpi *A, const TlsMpi *N)
 
 	ttls_mpi_pool_cleanup_ctx((unsigned long)TA, false);
 }
+
+/**
+ * Calculate X = X^2 mod N.
+ */
+void
+ttls_mpi_sq_mod(TlsMpi *X, const TlsMpi *N)
```
Comment (krizhanovsky) [inline tls/bignum.c:1450]: The function name and comment are misleading. According to Handbook of Applied Cryptography 14.85 algorithm (I strongly recommend to download the book along with BigNun Math by Denis - these books are very useful for the TLS crypt development) this is ` A = 1; A = A ^ 2`. However, I can't explain why do we make the left shift - probably because we slide in opposite direction....

Anyway this is not a generic big integer squaring, but a pure initialization of a helping constant for the exponentiation computation.

Also it'd be good to place the helping computation function somewhere on the top of the file.

File: tls/rsa.c [hunk 2]
```diff
@@ -492,6 +501,13 @@ rsa_check_context(const TlsRSACtx *ctx, int is_priv)
 		return(TTLS_ERR_RSA_BAD_INPUT_DATA);
 	}
 
+	if (is_priv &&
+		(ttls_mpi_cmp_int(&ctx->RP, 0) <= 0 ||
+		 ttls_mpi_cmp_int(&ctx->RQ, 0) <= 0))
+	{
+		return(TTLS_ERR_RSA_BAD_INPUT_DATA);
```
Comment (krizhanovsky) [inline tls/rsa.c:508]:
```suggestion
		return TTLS_ERR_RSA_BAD_INPUT_DATA;
```
We write new code in Tempesta style, not mbed TLS's one

File: tls/bignum.c [hunk 3]
```diff
@@ -1228,12 +1228,8 @@ ttls_mpi_exp_mod(TlsMpi *X, const TlsMpi *A, const TlsMpi *E, const TlsMpi *N,
...
 	 */
 	BUG_ON(!RR);
-	if (unlikely(ttls_mpi_empty(RR))) {
-		ttls_mpi_alloc(RR, N->used * 2 + 2);
-		ttls_mpi_lset(RR, 1);
-		ttls_mpi_shift_l(RR, RR, N->used * 2 * BIL);
-		ttls_mpi_mod_mpi(RR, RR, N);
-	}
+	if (unlikely(ttls_mpi_empty(RR)))
+		ttls_mpi_sq_mod(RR, N);
```
Comment (krizhanovsky) [inline tls/bignum.c:1232]: This function is called via generic PK interface and we also call the function for DHM handshakes, so don't we have the same issue with DHM? Probably DHM fix is also required and we can just replace the initialization code with `BUG_ON(ttls_mpi_empty(RR))`.

**Review by krizhanovsky — COMMENTED** [review]
At the moment I only have a question about how do we handle the RR precomputation for DHM - probably we should test and fix DHM as well.

**Review by const-t — COMMENTED** [review]
Fix looks good. But I can't understand how DHM works? Seems DHM has same race.

File: tls/bignum.c (hunk 1 above)
Comment (EvgeniiMekhanik) [reply tls/bignum.c:1450]: Fixed

File: tls/rsa.c (hunk 2 above)
Comment (EvgeniiMekhanik) [reply tls/rsa.c:508]: ok fixed

File: tls/bignum.c (hunk 3 above)
Comment (EvgeniiMekhanik) [reply tls/bignum.c]: In out implementation DHM is only used for keys with `id-ecDH` oid, but openssl, boringSSl doesn't support this key types.

Comment (EvgeniiMekhanik) [reply tls/bignum.c]: Fixed in second commit, no race was here, because dhm context is always new for new connection, but fix other errors

**Review by krizhanovsky — APPROVED** [review]
LGTM

**Review by const-t — APPROVED** [review]
LGTM
