### PR TITLE
Fix incorrect vhost reference counting

### LINKED ISSUE #1928: Kernel bug on WrkTestsMultipleVhosts
# Motivation

Nor we had kernel panic on run test WrkTestsMultipleVhosts multiple times. I had ran test for 5 times in average to reproduce

Dmesg attached below

# Scope

```
 Jul  3 13:07:33 192.168.50.117 [  410.243888] BUG: unable to handle page fault for address: ffffffffffffffff
 Jul  3 13:07:33 192.168.50.117 [  410.244325] #PF: supervisor read access in kernel mode
 Jul  3 13:07:33 192.168.50.117 [  410.244712] #PF: error_code(0x0000) - not-present page
 Jul  3 13:07:33 192.168.50.117 [  410.245135] PGD 6a40e067 P4D 6a40e067 PUD 6a410067 PMD 0
 Jul  3 13:07:33 192.168.50.117 [  410.245515] Oops: 0000 [#1] SMP NOPTI
 Jul  3 13:07:33 192.168.50.117 [  410.245895] CPU: 1 PID: 7632 Comm: sysctl Tainted: G           OE     5.10.35.tfw-4c9ba16 #1
 Jul  3 13:07:33 192.168.50.117 [  410.246290] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.15.0-0-g2dd4b9b3f840-prebuilt.qemu.org 04/01/2014
 Jul  3 13:07:33 192.168.50.117 [  410.247069] RIP: 0010:tfw_cfgop_vhosts_list_free.part.0+0x48/0x170 [tempesta_fw]
 Jul  3 13:07:33 192.168.50.117 [  410.247475] Code: 10 53 48 c7 c3 ff ff ff ff 48 83 ec 08 4d 8b 3c 24 4d 85 ff 75 11 eb 61 e8 c5 23 7f e4 e8 b0 b4 d8 e3 4d 85 ff 74 52 4c 89 ff <4d> 8b 3f 48 8b 47 08 48 85 c0 74 1b 4c 89 38 4d 85 ff 74 04 49 89
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RSP: 0018:ffffb9a542827c68 EFLAGS: 00010286
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RAX: 0000000000000000 RBX: ffffffffffffffff RCX: 000000000000000f
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RDX: 0000000000000001 RSI: 0000000000000001 RDI: ffffffffffffffff
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RBP: ffffb9a542827c98 R08: 0000000000000000 R09: 0000000000000001
 Jul  3 13:07:33 192.168.50.117 [  410.247853] R10: ffff980e6f139060 R11: 0000000000000001 R12: ffff980e6c638050
 Jul  3 13:07:33 192.168.50.117 [  410.247853] R13: ffff980e6c638000 R14: ffff980e6c63a010 R15: ffffffffffffffff
 Jul  3 13:07:33 192.168.50.117 [  410.247853] FS:  00007f03d448f580(0000) GS:ffff980f77d00000(0000) knlGS:0000000000000000
 Jul  3 13:07:33 192.168.50.117 [  410.247853] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
 Jul  3 13:07:33 192.168.50.117 [  410.247853] CR2: ffffffffffffffff CR3: 000000012ae06001 CR4: 0000000000770ee0
 Jul  3 13:07:33 192.168.50.117 [  410.247853] PKRU: 55555554
 Jul  3 13:07:33 192.168.50.117 [  410.247853] Call Trace:
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  __tfw_cfgop_vhosts_cleanup+0x3f/0x50 [tempesta_fw]
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  tfw_cfgop_vhosts_cleanup+0xe/0x10 [tempesta_fw]
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  spec_cleanup+0x5b/0x70 [tempesta_fw]
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  tfw_cfg_cleanup+0x21/0x50 [tempesta_fw]
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  tfw_cleanup+0x15/0x30 [tempesta_fw]
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  tfw_ctlfn_state_io+0x12d/0x300 [tempesta_fw]
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  ? tfw_cleanup+0x30/0x30 [tempesta_fw]
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  proc_sys_call_handler+0x13f/0x240
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  proc_sys_write+0x13/0x20
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  new_sync_write+0x117/0x1b0
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  vfs_write+0x185/0x250
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  ksys_write+0x67/0xe0
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  __x64_sys_write+0x1a/0x20
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  do_syscall_64+0x38/0x90
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RIP: 0033:0x7f03d43aa077
 Jul  3 13:07:33 192.168.50.117 [  410.247853] Code: 64 89 02 48 c7 c0 ff ff ff ff eb bb 0f 1f 80 00 00 00 00 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 51 c3 48 83 ec 28 48 89 54 24 18 48 89 74 24
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RSP: 002b:00007ffd7f256548 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RAX: ffffffffffffffda RBX: 000055ed3d3294a0 RCX: 00007f03d43aa077
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RDX: 0000000000000005 RSI: 000055ed3d3294e0 RDI: 0000000000000004
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RBP: 000055ed3d32b610 R08: 0000000000000010 R09: 0000000000000005
 Jul  3 13:07:33 192.168.50.117 [  410.247853] R10: 000055ed3d25016c R11: 0000000000000246 R12: 0000000000000005
 Jul  3 13:07:33 192.168.50.117 [  410.247853] R13: 0000000000000005 R14: 00007f03d4484a20 R15: 00007f03d44848a0
 Jul  3 13:07:33 192.168.50.117 [  410.247853] Modules linked in: tempesta_fw(OE) tempesta_db(OE) tempesta_tls(OE) tempesta_lib(OE) sha256_ssse3 sha512_ssse3 xt_conntrack xt_MASQUERADE nf_conntrack_netlink xfrm_user xfrm_algo xt_addrtype iptable_filter iptable_nat bpfilter br_netfilter bridge stp llc overlay nfnetlink_cttimeout nfnetlink openvswitch nsh nf_conncount nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 dm_multipath scsi_dh_rdac scsi_dh_emc scsi_dh_alua kvm_amd ccp kvm sch_fq_codel binfmt_misc input_leds joydev serio_raw netconsole qemu_fw_cfg mac_hid ramoops msr reed_solomon efi_pstore ip_tables x_tables autofs4 btrfs blake2b_generic zstd_compress raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear hid_generic usbhid hid crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel crypto_simd cryptd glue_helper bochs_drm drm_vram_helper drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops psmouse cec
 Jul  3 13:07:33 192.168.50.117 [  410.247853]  virtio_scsi drm e1000 i2c_piix4 pata_acpi floppy [last unloaded: tempesta_lib]
 Jul  3 13:07:33 192.168.50.117 [  410.247853] CR2: ffffffffffffffff
 Jul  3 13:07:33 192.168.50.117 [  410.247853] ---[ end trace 5047fd0c3a0f0f43 ]---
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RIP: 0010:tfw_cfgop_vhosts_list_free.part.0+0x48/0x170 [tempesta_fw]
 Jul  3 13:07:33 192.168.50.117 [  410.247853] Code: 10 53 48 c7 c3 ff ff ff ff 48 83 ec 08 4d 8b 3c 24 4d 85 ff 75 11 eb 61 e8 c5 23 7f e4 e8 b0 b4 d8 e3 4d 85 ff 74 52 4c 89 ff <4d> 8b 3f 48 8b 47 08 48 85 c0 74 1b 4c 89 38 4d 85 ff 74 04 49 89
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RSP: 0018:ffffb9a542827c68 EFLAGS: 00010286
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RAX: 0000000000000000 RBX: ffffffffffffffff RCX: 000000000000000f
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RDX: 0000000000000001 RSI: 0000000000000001 RDI: ffffffffffffffff
 Jul  3 13:07:33 192.168.50.117 [  410.247853] RBP: ffffb9a542827c98 R08: 0000000000000000 R09: 0000000000000001
 Jul  3 13:07:33 192.168.50.117 [  410.247853] R10: ffff980e6f139060 R11: 0000000000000001 R12: ffff980e6c638050
 Jul  3 13:07:33 192.168.50.117 [  410.247853] R13: ffff980e6c638000 R14: ffff980e6c63a010 R15: ffffffffffffffff
 Jul  3 13:07:33 192.168.50.117 [  410.247853] FS:  00007f03d448f580(0000) GS:ffff980f77d00000(0000) knlGS:0000000000000000
 Jul  3 13:07:33 192.168.50.117 [  410.247853] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
 Jul  3 13:07:33 192.168.50.117 [  410.247853] CR2: ffffffffffffffff CR3: 000000012ae06001 CR4: 0000000000770ee0
 Jul  3 13:07:33 192.168.50.117 [  410.247853] PKRU: 55555554
 Jul  3 13:07:33 192.168.50.117 [  410.247853] Kernel panic - not syncing: Fatal exception
 Jul  3 13:07:33 192.168.50.117 [  410.247853] Kernel Offset: 0x23800000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
 Jul  3 13:07:33 192.168.50.117 [  410.247853] Rebooting in 1 seconds..
```

# Testing

Ensure test works fine with `-R 50`

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
First of all we should check that vhost reference count is always greater or equal to zero. Also we should increment vhost reference count when we add vhost to sni map.

Closes #1928

### CODE REVIEW

File: fw/http_limits.c [hunk 1]
```diff
@@ -655,9 +655,11 @@ frang_http_domain_fronting_check(const TfwHttpReq *req, FrangAcc *ra)
 		frang_msg("vhost by SNI doesn't match vhost by authority",
 			  &FRANG_ACC2CLI(ra)->addr, " ('%.*s' vs '%.*s')\n",
 			  PR_TFW_STR(&tls_name), PR_TFW_STR(&req_name));
+		tfw_vhost_put(tls_vhost);
 		return TFW_BLOCK;
 	}
 
+	tfw_vhost_put(tls_vhost);
```
Comment (krizhanovsky) [inline fw/http_limits.c:662]: Oh, I did miss this during review. Could you please add comments to `__lookup_vhost_by_authority()` and/or other vhost lookup functions that it's a caller responsibility to put vhost?

**Review by krizhanovsky — APPROVED** [review]
LGTM

**Review by const-t — APPROVED** [review]
LGTM

File: fw/http_limits.c (hunk 1 above)
Comment (EvgeniiMekhanik) [reply fw/http_limits.c:662]: Yes fixed
