### PR TITLE
Fix crash during tempesta reconfiguration

### LINKED ISSUE #1761: Crash while restarting tests
Once test suite has been interrupted and started again tempesta cause panic.

## Reproduce
Run `run_tests.py t_long_body.test_long_request.LongBodyInRequest.test_http` and interrupt few times. Maybe need to run test many times before interruption. Can be reproduced after some number of tries. Also can be reproduced with `t_frang` tests.

<details>
  <summary>BUG: kernel NULL pointer dereference, address: 0000000000000030</summary>

```
[   90.457491] BUG: kernel NULL pointer dereference, address: 0000000000000030
[   90.458641] #PF: supervisor read access in kernel mode
[   90.459527] #PF: error_code(0x0000) - not-present page
[   90.460402] PGD 0 P4D 0 
[   90.460853] Oops: 0000 [#1] SMP NOPTI
[   90.461485] CPU: 3 PID: 3468 Comm: sysctl Kdump: loaded Tainted: G           OE     5.10.35+ #5
[   90.462982] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS Arch Linux 1.16.0-3-3 04/01/2014
[   90.464841] RIP: 0010:memcmp+0x16/0x30
[   90.465490] Code: 09 48 83 c0 01 48 39 c2 74 07 0f b6 08 39 f1 75 f0 c3 66 90 48 85 d2 74 1d 31 c9 eb 09 48 83 c1 01 48 39 ca 74 0f 0f b6 04 0f <44> 0f b6 04 0e 44 29 c0 74 e9 c3 c3 31 c0 c3 66 66 2e 0f 1f 84 00
[   90.468681] RSP: 0018:ffffc9000266fcb0 EFLAGS: 00010246
[   90.469572] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[   90.470766] RDX: 0000000000000010 RSI: 0000000000000030 RDI: ffff8881260af6f0
[   90.471985] RBP: ffff8881260af6c0 R08: ffffffffa0a1d2a0 R09: ffffffffa0a1d2a0
[   90.473228] R10: ffffc9000266fa90 R11: 0000000000000003 R12: 0000000000000008
[   90.474404] R13: ffff88812441a278 R14: ffffffffa0a1d2a0 R15: 0000000000000000
[   90.475635] FS:  00007f9c1e4ac580(0000) GS:ffff888276cc0000(0000) knlGS:0000000000000000
[   90.477033] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   90.478027] CR2: 0000000000000030 CR3: 0000000121976000 CR4: 0000000000350ee0
[   90.479258] Call Trace:
[   90.479694]  tfw_listen_socks_array_cmp+0x1f/0x30 [tempesta_fw]
[   90.480811]  bsearch+0x52/0x80
[   90.481452]  tfw_sock_clnt_start+0x130/0x3b0 [tempesta_fw]
[   90.482571]  ? tfw_cfgop_cleanup_srv_cfgs+0xa3/0xd0 [tempesta_fw]
[   90.483798]  ? tfw_sock_srv_start+0x272/0x320 [tempesta_fw]
[   90.484930]  tfw_ctlfn_state_io+0x18e/0x320 [tempesta_fw]
[   90.486031]  proc_sys_call_handler+0x141/0x260
[   90.486827]  new_sync_write+0x113/0x1b0
[   90.487407]  vfs_write+0x1bb/0x250
[   90.487904]  ksys_write+0x63/0xe0
[   90.488388]  do_syscall_64+0x33/0x80
[   90.488909]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   90.489642] RIP: 0033:0x7f9c1e3c28f3
[   90.490158] Code: 8b 15 a1 25 0e 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b7 0f 1f 00 64 8b 04 25 18 00 00 00 85 c0 75 14 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 55 c3 0f 1f 40 00 48 83 ec 28 48 89 54 24 18
[   90.492783] RSP: 002b:00007fff1a42fa98 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[   90.494461] RAX: ffffffffffffffda RBX: 00005646d24b74a0 RCX: 00007f9c1e3c28f3
[   90.495492] RDX: 0000000000000006 RSI: 00005646d24b74e0 RDI: 0000000000000004
[   90.496527] RBP: 00005646d24b9610 R08: 0000000000000010 R09: 0000000000000006
[   90.497535] R10: 0000000000000070 R11: 0000000000000246 R12: 0000000000000006
[   90.498541] R13: 0000000000000006 R14: 0000000000000006 R15: 00007f9c1e4a1880
[   90.499560] Modules linked in: tempesta_fw(OE) tempesta_db(OE) tempesta_tls(OE) tempesta_lib(OE) sha256_ssse3(E) sha512_ssse3(E) sha512_generic(E) 9p(E) fscache(E) joydev(E) uinput(E) rfkill(E) kvm_amd(E) ccp(E) rng_core(E) kvm(E) irqbypass(E) ghash_clmulni_intel(E) aesni_intel(E) libaes(E) crypto_simd(E) cryptd(E) glue_helper(E) snd_pcm(E) snd_timer(E) snd(E) soundcore(E) sg(E) serio_raw(E) 9pnet_virtio(E) pcspkr(E) virtio_console(E) 9pnet(E) evdev(E) msr(E) qemu_fw_cfg(E) parport_pc(E) ppdev(E) lp(E) parport(E) fuse(E) configfs(E) ip_tables(E) x_tables(E) autofs4(E) ext4(E) crc32c_generic(E) crc16(E) mbcache(E) jbd2(E) sr_mod(E) cdrom(E) ata_generic(E) virtio_blk(E) bochs_drm(E) drm_vram_helper(E) drm_ttm_helper(E) ttm(E) drm_kms_helper(E) cec(E) crct10dif_pclmul(E) crct10dif_common(E) crc32_pclmul(E) crc32c_intel(E) virtio_pci(E) ata_piix(E) virtio_ring(E) psmouse(E) libata(E) drm(E) virtio(E) e1000(E) i2c_piix4(E) scsi_mod(E) floppy(E) button(E) [last unloaded: tempesta_lib]
[   90.511969] CR2: 0000000000000030
[    0.015579] Tempesta: cannot allocate 256 continous huge pages at node 0[
```
</details>

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
In issue #1761 described a situation with tempesta crashing when restarting tests. Actually the problem is that when we stop tempesta, we clear the `tfw_listen_socks` list, but `tfw_listen_socks_sz` is a local variable and it's value isn't changed. Later, when we start tempesta again (without reload kernel modules) we allocate `listen_socks_array` with `tfw_listen_socks_sz` size, but we don't fill it with valid entries because `tfw_listen_socks` list is empty.

Closes #1761

### CODE REVIEW

**Comment by EvgeniiMekhanik** [comment]
Simple test to reproduce issue https://github.com/tempesta-tech/tempesta-test/pull/393

**Comment by EvgeniiMekhanik** [comment]
I see one more potential bug in `tfw_sock_clnt_start` (which not described in issue`, i try to check it in this PR

**Review by const-t — APPROVED** [review]
LGTM

File: fw/sock_clnt.c [hunk 1]
```diff
@@ -397,6 +397,8 @@ typedef struct {
  */
```
Comment (krizhanovsky) [inline fw/sock_clnt.c:397]: please update the copyright year

**Review by krizhanovsky — APPROVED** [review]
LGTM
