### PR TITLE
Fix parsing short headers

### LINKED ISSUE #1412: HTTP parser failure on both http2 and http1
## Scope

Form a request:
```
curl -kvvvf http://192.168.122.12/ -o rcv \
    -H ":authority: 192.168.122.12"  \
    -H ":method: GET" \
    -H ":path: /hello" \
    -H ":scheme: https" \
    -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" \
    -H "accept-encoding: gzip, deflate, br" \
    -H "accept-language: en-US,en;q=0.9,ru;q=0.8" \
    -H "cache-control: no-cache" \
    -H "dnt: 1" \
    -H "pragma: no-cache" \
    -H "sec-fetch-dest: document" \
    -H "sec-fetch-mode: navigate" \
    -H "sec-fetch-site: none" \
    -H "sec-fetch-user: ?1" \
    -H "upgrade-insecure-requests: 1" \
    -H "user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
```

If protocol is http you will get a crash:
```
 ------------[ cut here ]------------
 kernel BUG at /home/user/qtc/release/tempesta/tempesta_fw/http_msg.c:623!
 invalid opcode: 0000 [#1] SMP PTI
 Modules linked in: tempesta_fw(O) tempesta_db(O) tempesta_tls(O) tempesta_lib(O) sha256_ssse3 sha512_ssse3 sha512_generic ccm kvm_intel snd_hda_codec_generic iTCO_wdt iTCO_vendor_support kvm irqbypass snd_hda_intel crct10dif_pclmul snd_hda_codec crc32_pclmul snd_hda_core snd_hwdep snd_pcm snd_timer snd soundcore ghash_clmulni_intel sg virtio_balloon virtio_console virtio_gpu evdev pcspkr ttm serio_raw drm_kms_helper lpc_ich mfd_core binfmt_misc drm shpchp button ip_tables x_tables autofs4 ext4 crc16 mbcache jbd2 fscrypto ecb aesni_intel crypto_simd cryptd glue_helper aes_x86_64 crc32c_generic sr_mod cdrom virtio_blk virtio_net crc32c_intel psmouse ahci libahci i2c_i801 libata sym53c8xx ehci_pci uhci_hcd scsi_transport_spi ehci_hcd scsi_mod virtio_pci virtio_ring usbcore virtio usb_common
  [last unloaded: tempesta_lib]
 CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W  O L  4.14.0-tempesta-kmemleak-amd64 #1 Debian 4.14.32-tfw7-1
 Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS ?-20191223_100556-anatol 04/01/2014
 task: ffffffff84612480 task.stack: ffffffff84600000
 RIP: 0010:__tfw_http_msg_add_str_data+0xe2/0x100 [tempesta_fw]
 RSP: 0018:ffffa01a65403960 EFLAGS: 00010246
 RAX: ffffa019e9bf0caf RBX: ffffa019e9bf0caf RCX: 000000000000002d
 RDX: 0000000000000000 RSI: ffffa019ffe2c7f8 RDI: ffffa01a0039d020
 RBP: ffffa01a0039d020 R08: ffffa019feee0f00 R09: ffffa019e9bf0d2f
 R10: ffffa01a65403968 R11: ffffa019ffe2c760 R12: ffffa019e9bf0c82
 R13: 000000000000003e R14: ffffa019e9bf0caf R15: ffffa019ffe2c760
 FS:  0000000000000000(0000) GS:ffffa01a65400000(0000) knlGS:0000000000000000
 CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
 CR2: 00007efd2d1e4000 CR3: 000000002160a003 CR4: 00000000003606f0
 Call Trace:
  <IRQ>
  tfw_http_parse_req+0x1b41/0xc540 [tempesta_fw]
  ? __req_parse_content_type+0x1240/0x1240 [tempesta_fw]
  ? ss_skb_process+0x80/0x140 [tempesta_fw]
  ? tfw_http_msg_process_generic+0x1e5/0xd20 [tempesta_fw]
  ? call_function_single_interrupt+0x7d/0x90
  ? stack_access_ok+0x46/0x50
  ? unwind_next_frame+0x4bb/0x680
  ? __kernel_text_address+0xe/0x30
  ? unwind_get_return_address+0x1b/0x30
  ? __save_stack_trace+0x75/0x100
  ? __slab_free+0xa9/0x330
  ? tfw_http_msg_process+0x84/0xc0 [tempesta_fw]
  ? __gfsm_fsm_exec+0x56/0x90 [tempesta_fw]
  ? tfw_connection_recv+0x41/0x60 [tempesta_fw]
  ? tfw_connection_send+0x30/0x30 [tempesta_fw]
  ? ss_tcp_process_data+0x1ea/0x480 [tempesta_fw]
  ? ss_tcp_data_ready+0x43/0x90 [tempesta_fw]
  ? tcp_data_queue+0x4f5/0xc50
  ? tcp_rcv_established+0x27c/0x570
  ? tcp_v4_do_rcv+0x129/0x1d0
  ? tcp_v4_rcv+0x947/0xa50
  ? ip_local_deliver_finish+0x9a/0x1c0
  ? ip_local_deliver+0x6b/0xe0
  ? tcp_v4_early_demux+0x112/0x150
  ? ip_rcv_finish+0x17a/0x400
  ? ip_rcv+0x289/0x3c0
  ? inet_del_offload+0x40/0x40
  ? __netif_receive_skb_core+0x84f/0xb30
  ? process_backlog+0xa3/0x160
  ? process_backlog+0xa3/0x160
  ? net_rx_action+0x28e/0x3f0
  ? __do_softirq+0x10f/0x2a8
  ? irq_exit+0xae/0xb0
  ? call_function_single_interrupt+0x7d/0x90
  </IRQ>
  ? __sched_text_end+0x3/0x3
  ? native_safe_halt+0x2/0x10
  ? default_idle+0x1a/0xf0
  ? do_idle+0x16e/0x1f0
  ? cpu_startup_entry+0x6f/0x80
  ? start_kernel+0x467/0x487
  ? secondary_startup_64+0xa5/0xb0
 Code: 5c 41 5d c3 0f 0b b8 ea ff ff ff c3 48 89 16 4c 89 46 08 48 89 d0 e9 52 ff ff ff e8 f9 c8 33 c3 85 c0 75 0d b8 f4 ff ff ff eb ce <0f> 0b 0f 0b 0f 0b 48 c7 c7 80 9c 8c c0 31 c0 e8 55 cd e8 c2 b8 
 RIP: __tfw_http_msg_add_str_data+0xe2/0x100 [tempesta_fw] RSP: ffffa01a65403960
```

If protocol is http2, a warning appears:
```
[tempesta fw] Warning: HTTP/2 request dropped: state=Req_HdrPseudo input=0x64('dnt'), len=3, off=0
```

Reproduced on current master, configuration as follows:
```
listen 80;
listen 443 proto=h2;
response_body 502 /etc/tempesta/502_long;
cache 1;
cache_fulfill * *;
tls_certificate /home/user/cert/tfw-root.crt;
tls_certificate_key /home/user/cert/tfw-root.key;
srv_group default {
#    server 127.0.0.1:8080 conns_n=1;
    server 127.0.0.1:1234 conns_n=1;
}

block_action attack reply;
vhost default {
    proxy_pass default;
}

http_chain {
     -> default;
}

frang_limits {
}
```

This is real-life Chromium request.  Didn't noticed this previously when tested h2, probably Chromium updated something in it's requests... 

## Testing

This section is mandatory. Please, specify name of the test revealing the problem or at least generic considerations how to make a test for our QA. A link to a new issue in https://github.com/tempesta-tech/tempesta-test/issues would be just perfect.

### PR DESCRIPTION
**Pull request by ikoveshnikov**
fix #1412

### CODE REVIEW

File: tempesta_fw/http_parser.c [hunk 1]
```diff
@@ -1032,6 +1032,8 @@ __FSM_STATE(st_curr) {							\
 __FSM_STATE(RGen_HdrOtherN) {						\
 	__FSM_MATCH_MOVE(token, RGen_HdrOtherN, 0);			\
 	if (likely(*(p + __fsm_sz) == ':')) {				\
+		if (unlikely(!__fsm_sz))				\
+			TFW_PARSER_BLOCK(RGen_HdrOtherN);		\
```
Comment (krizhanovsky) [inline tempesta_fw/http_parser.c:1036]: Please add the functional test case of sending h2c message to the current HTTP/1 parser.

Comment (ikoveshnikov) [reply tempesta_fw/http_parser.c:1043]: Unit tests was added into this PR and functional was added into tempesta-tech/tempesta-test#163
