### PR TITLE
Fix #798: Avoid crash during processing of erroneous response.

### LINKED ISSUE #798: Kernel BUG at tempesta_fw/http.c:1156 on invalid Date: in response
Caught by accident when working on functional tests.

Reproducer is at tempesta-tech/tempesta@56443190fc2aa92f8e90e0c13af75dac6e307191 (branch [`crash/http.c-1156`](https://github.com/tempesta-tech/tempesta/tree/crash/http.c-1156).

```
[   68.201629] [tempesta] Warning: Parser error: state=Resp_HdrDateV input=0x4d('Mon, 14 Aug 2017') data_len=334 off=163
[   68.202437] ------------[ cut here ]------------
[   68.202755] kernel BUG at /root/tempesta/tempesta_fw/http.c:1156!
[   68.203171] invalid opcode: 0000 [#1] SMP
[   68.203454] Modules linked in: tfw_sched_ratio(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) tempesta_tls(O) fuse crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd snd_pcm snd_timer sg joydev evdev serio_raw ppdev parport_pc snd soundcore bochs_drm ttm drm_kms_helper drm pcspkr parport button ip_tables x_tables autofs4 ext4 crc16 jbd2 fscrypto mbcache sd_mod sr_mod cdrom ata_generic e1000 ata_piix crc32c_intel libata psmouse scsi_mod i2c_piix4 floppy
[   68.207151] CPU: 2 PID: 0 Comm: swapper/2 Tainted: G           O    4.9.35+ #1
[   68.207629] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-20170228_101828-anatol 04/01/2014
[   68.208302] task: ffff9f251c8c0000 task.stack: ffffc3938037c000
[   68.208696] RIP: 0010:[<ffffffffc07bfbe1>]  [<ffffffffc07bfbe1>] tfw_http_req_destruct+0x51/0x60 [tempesta_fw]
[   68.209380] RSP: 0018:ffff9f253fd03af8  EFLAGS: 00010297
[   68.209736] RAX: ffff9f251bc655a8 RBX: ffff9f251940b020 RCX: 0000000180100006
[   68.210210] RDX: 0000000180100007 RSI: ffffe8e480d9c200 RDI: ffff9f251940b020
[   68.210683] RBP: ffff9f251c1049a0 R08: ffff9f24f6708200 R09: 0000000180100006
[   68.211158] R10: ffff9f24f6708600 R11: 00000000ffffff00 R12: ffff9f24f6b5d020
[   68.211631] R13: 00000000fffffffe R14: 000000000000014e R15: 0000000000000000
[   68.212109] FS:  0000000000000000(0000) GS:ffff9f253fd00000(0000) knlGS:0000000000000000
[   68.212676] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   68.213089] CR2: 000055871abe4b58 CR3: 000000003669d000 CR4: 00000000001406e0
[   68.213678] Stack:
[   68.213831]  ffff9f24f6b5d020 ffffffffc07c3099 0000000000000000 ffffffffc07c110c
[   68.214380]  ffff9f24d57a2000 ffff9f251ba9f700 0000000000000246 0000000000000000
[   68.214921]  ffffffffb634c943 017aa8c0f6a28000 248e9cd82705edf0 ffffffff0000014e
[   68.215459] Call Trace:
[   68.215635]  <IRQ> [   68.215790]  [<ffffffffc07c3099>] ? tfw_http_msg_free+0x89/0xa0 [tempesta_fw]
[   68.216286]  [<ffffffffc07c110c>] ? tfw_http_msg_process+0x45c/0x760 [tempesta_fw]
[   68.216818]  [<ffffffffb634c943>] ? ip_finish_output2+0x183/0x370
[   68.217242]  [<ffffffffc07be296>] ? __gfsm_fsm_exec+0x56/0x90 [tempesta_fw]
[   68.217714]  [<ffffffffc07d9fed>] ? ss_tcp_process_data+0x18d/0x410 [tempesta_fw]
[   68.218240]  [<ffffffffc07da4e3>] ? ss_tcp_data_ready+0x43/0x80 [tempesta_fw]
[   68.218718]  [<ffffffffb6362ec5>] ? tcp_rcv_established+0x465/0x6c0
[   68.219148]  [<ffffffffb6320dbd>] ? sk_filter_trim_cap+0x2d/0x2c0
[   68.220224]  [<ffffffffb636d763>] ? tcp_v4_do_rcv+0x133/0x1f0
[   68.221240]  [<ffffffffb636ef07>] ? tcp_v4_rcv+0x8a7/0x9b0
[   68.222233]  [<ffffffffb6348559>] ? ip_local_deliver_finish+0x99/0x1c0
[   68.223286]  [<ffffffffb634881b>] ? ip_local_deliver+0x6b/0xf0
[   68.224285]  [<ffffffffb636e650>] ? tcp_v4_early_demux+0x130/0x140
[   68.225296]  [<ffffffffb6348241>] ? ip_rcv_finish+0x171/0x3f0
[   68.226283]  [<ffffffffb6348b26>] ? ip_rcv+0x286/0x3d0
[   68.227233]  [<ffffffffb63480d0>] ? inet_del_offload+0x40/0x40
[   68.228242]  [<ffffffffb63076d9>] ? __netif_receive_skb_core+0x4f9/0xa00
[   68.229317]  [<ffffffffc07e3bb3>] ? tfw_wq_pop_ticket+0x83/0x4d0 [tempesta_fw]
[   68.230406]  [<ffffffffb6308d78>] ? process_backlog+0x88/0x130
[   68.231394]  [<ffffffffb6308490>] ? net_rx_action+0x240/0x370
[   68.232394]  [<ffffffffb6410dda>] ? __do_softirq+0x10a/0x29a
[   68.233365]  [<ffffffffb5e80e8e>] ? irq_exit+0xae/0xb0
[   68.234278]  [<ffffffffb64104a2>] ? call_function_single_interrupt+0x82/0x90
[   68.235313]  <EOI> [   68.235459]  [<ffffffffb640db22>] ? native_safe_halt+0x2/0x10
[   68.236433]  [<ffffffffb640d86a>] ? default_idle+0x1a/0xd0
[   68.237373]  [<ffffffffb5ebd83a>] ? cpu_startup_entry+0x1ca/0x240
[   68.238332]  [<ffffffffb5e4810d>] ? start_secondary+0x14d/0x190
[   68.239258] Code: 87 d0 03 00 00 48 8d 97 d0 03 00 00 48 39 c2 75 1e 48 8b bf 58 03 00 00 48 85 ff 74 09 48 83 c4 08 e9 64 75 01 00 48 83 c4 08 c3 <0f> 0b 0f 0b 0f 0b 66 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 41
[   68.242224] RIP  [<ffffffffc07bfbe1>] tfw_http_req_destruct+0x51/0x60 [tempesta_fw]
[   68.243284]  RSP <ffff9f253fd03af8>
[   68.244094] ---[ end trace d0983e5060c9484a ]---
[   68.244986] Kernel panic - not syncing: Fatal exception in interrupt
[   68.246020] Kernel Offset: 0x34e00000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
```

### PR DESCRIPTION
**Pull request by aleksostapenko**
1. Sending error response to client (with correct removal of paired request).
2. Sending correct response to client after sibling message creation failure (before server connection closing).

### CODE REVIEW

File: tempesta_fw/http.c [hunk 1]
```diff
@@ -2542,9 +2540,9 @@ tfw_http_resp_process(TfwConn *conn, struct sk_buff *skb, unsigned int off)
 bad_msg:
 	bad_req = tfw_http_popreq(hmresp);
 	if (bad_req)
-		tfw_http_conn_msg_free((TfwHttpMsg *)bad_req);
+		tfw_http_send_500(bad_req, "response dropped: processing error");
 	tfw_http_conn_msg_free(hmresp);
-	return r;
+	return TFW_PASS;
```
Comment (ikoveshnikov) [inline tempesta_fw/http.c]: I argue against returning `TFW_PASS` here. If we've reach `bad_msg` label, it means that we've encountered an error during parsing. This means that the errored response wasn't red fully from the connection. So then we would get the parse error for every next read from the connection.

If error code is returned, we will close the server connection from the Tempesta side. The `ss_tcp_state_change()` callback with state `TCP_CLOSE` will be called and we will re-establish connection to the server.

Comment (aleksostapenko) [reply tempesta_fw/http.c]: Corrected.

File: tempesta_fw/http.c [hunk 2]
```diff
@@ -2507,6 +2507,15 @@ tfw_http_resp_process(TfwConn *conn, struct sk_buff *skb, unsigned int off)
...
 					 "to create a response sibling\n");
 				TFW_INC_STAT_BH(serv.msgs_otherr);
+				
+				/* 
+				 * We failed to create the sibling message,
+				 * but despite this, we have a correctly
+				 * parsed response. So we can send this
+				 * response to client before closing
+				 * server connection.
+				 */
```
Comment (keshonok) [inline tempesta_fw/http.c]: I would avoid using the word "we" in comments, and use an impersonalized style. Also, try to be concise.
_Unable to create a sibling message. Send the parsed response to the client and close the server connection._

Comment (aleksostapenko) [reply tempesta_fw/http.c]: Corrected.

File: tempesta_fw/http.c [hunk 3]
```diff
@@ -2542,7 +2549,7 @@ tfw_http_resp_process(TfwConn *conn, struct sk_buff *skb, unsigned int off)
 bad_msg:
 	bad_req = tfw_http_popreq(hmresp);
 	if (bad_req)
-		tfw_http_conn_msg_free((TfwHttpMsg *)bad_req);
+		tfw_http_send_500(bad_req, "response dropped: processing error");
```
Comment (krizhanovsky) [inline tempesta_fw/http.c]: Now I'm fine with the change - that's good as a default behaviour. However, `bad_msg` can be reached by `TFW_BLOCK` returned from GFSM hook, typically Frang security limit. A user should have an options whether to generate HTTP response, which is relatively heavy operation, or just drop malicious traffic (filtered by Frang). This is the subject for #658 which I reassign to you. Please note the place when you'll be working on it.

Comment (aleksostapenko) [reply tempesta_fw/http.c]: Ok
