### PR TITLE
tls: propagate sequence numbers through the touched parts of tcp write queue

### LINKED ISSUE #1177: tfw_tls_encrypt(): tls context NULL dereference
Just caught following crash on current `ak-1170` branch (https://github.com/tempesta-tech/tempesta/pull/1173/commits/62ab90d5124481a6fa5a6363fa03488059cc6d5f):
```
[ 1176.243945] kasan: CONFIG_KASAN_INLINE enabled
[ 1176.248288] kasan: GPF could be caused by NULL-ptr deref or user memory access
[ 1176.251001] general protection fault: 0000 [#1] SMP KASAN
[ 1176.253907] Modules linked in: tempesta_fw(O) tempesta_db(O) tempesta_tls(O) tempesta_lib(O) binfmt_misc bochs_drm ttm drm_kms_helper crct10dif_pclmul sg drm ppdev fb_sys_fops syscopyarea sysfillrect sysimgblt button pcspkr serio_raw parport_pc parport ip_tables x_tables ext4 crc16 mbcache jbd2 fscrypto sr_mod sd_mod cdrom ata_generic ata_piix libata psmouse scsi_mod e1000 i2c_piix4 [last unloaded: tempesta_lib]
[ 1176.268461] CPU: 3 PID: 28 Comm: ksoftirqd/3 Tainted: G        W  O    4.14.32-kdump+ #127
[ 1176.268463] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS ?-20180724_192412-buildhw-07.phx2.fedoraproject.org-1.fc29 04/01/2014
[ 1176.268465] task: ffff880100e130c0 task.stack: ffff880100ec0000
[ 1176.268505] RIP: 0010:ttls_xfrm_ready+0x19/0x50 [tempesta_tls]
[ 1176.268506] RSP: 0018:ffff880100ec7968 EFLAGS: 00010202
[ 1176.268509] RAX: dffffc0000000000 RBX: 0000000000000350 RCX: 0000000000000000
[ 1176.268511] RDX: 0000000000000070 RSI: ffff8801173e9000 RDI: 0000000000000380
[ 1176.268512] RBP: ffff8801173e9080 R08: ffff8801173e902c R09: 0000000000000b33
[ 1176.268513] R10: ffff8801173e9038 R11: 0000000000000000 R12: ffff8801173e9000
[ 1176.268515] R13: 0000000000000b33 R14: 0000000000000000 R15: 0000000000000b33
[ 1176.268517] FS:  0000000000000000(0000) GS:ffff88011b580000(0000) knlGS:0000000000000000
[ 1176.268518] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1176.268526] CR2: 00007f7660120000 CR3: 0000000042a0f001 CR4: 00000000003606e0
[ 1176.268527] Call Trace:
[ 1176.268552]  tfw_tls_encrypt+0x1ea/0x1440 [tempesta_fw]
[ 1176.268581]  ? ip_output+0x1a1/0x2b0
[ 1176.268583]  ? ip_output+0x1a1/0x2b0
[ 1176.268597]  ? tfw_tls_msg_process+0x920/0x920 [tempesta_fw]
[ 1176.268604]  ? tcp_transmit_skb+0x17d1/0x3420
[ 1176.268612]  ? pg_skb_alloc+0x51f/0xc80
[ 1176.268614]  ? skb_split+0x1da/0x1200
[ 1176.268617]  ? tcp_established_options+0x8f/0x400
[ 1176.268631]  ? sched_clock_cpu+0x18/0x170
[ 1176.268646]  ? tfw_tls_msg_process+0x920/0x920 [tempesta_fw]
[ 1176.268649]  tcp_write_xmit+0xb64/0x5600
[ 1176.268653]  ? tcp_tsq_handler.part.35+0x169/0x280
[ 1176.268655]  tcp_tasklet_func+0x399/0x520
[ 1176.268658]  ? tcp_release_cb+0x200/0x200
[ 1176.268671]  ? __switch_to_asm+0x34/0x70
[ 1176.268673]  ? __switch_to_asm+0x40/0x70
[ 1176.268676]  ? tcp_release_cb+0x200/0x200
[ 1176.268684]  tasklet_action+0x8d/0x220
[ 1176.268687]  __do_softirq+0x1d2/0x5bd
[ 1176.268690]  run_ksoftirqd+0x14/0x30
[ 1176.268694]  smpboot_thread_fn+0x438/0x680
[ 1176.268697]  ? sort_range+0x20/0x20
[ 1176.268700]  ? schedule+0x83/0x190
[ 1176.268702]  ? sort_range+0x20/0x20
[ 1176.268709]  kthread+0x2bd/0x3b0
```

I hit the bug on multiple reloading content of tempesta-tech.com with a Chrome history clearing (sometimes I cleared the cache while the content is still loading). The bug is caused by
```C
BUG_ON(!ttls_xfrm_ready(tls));
```
in `tfw_tls_encrypt()`, `tls` somehow is seen as zero.

Tempesta was serveral times restarted during debugging of TCP broken sequences, however there were no clues for memory corruptions.

### PR DESCRIPTION
**Pull request by i-rinat**
Currently, we encrypt data in TLS connections in `tfw_tls_encrypt()`, and during that operation, data chunks are enlarged to fit auxiliary data. As TCP sequence numbers are calculated earlier, we adjust the numbers on the go. To reduce TLS overhead, multiple skb's are aggregated into a single record if possible.

The patchset corrects sequence number calculation in the case where skb's are actually aggregated. Also, couple of side issues are addressed too: a NULL dereference and spurious WARN_ON assertion triggering.

(fixes #1177)

### CODE REVIEW

File: tempesta_fw/tls.c [hunk 1]
```diff
@@ -284,8 +291,7 @@ tfw_tls_encrypt(struct sock *sk, struct sk_buff *skb, unsigned int limit)
 			break;
 
 		/* @next has original seqnos, so advance both of them. */
-		tcb->seq += head_sz;
-		tcb->end_seq += head_sz;
+		tfw_tls_tcp_propagate_dseq(sk, skb_tail);
```
Comment (krizhanovsky) [inline tempesta_fw/tls.c]: If the reason for the change is that we `skb_tail` can contain seqnos not updated from previous run and we have to move them further than `head_sz`, then please update the comment to say what's happening here. The seqno games are quite subtle, so it'd be good to have good comments here.

I guess now you have warning about unused `tcb` in non-debugging build. I propose just to use `TCP_SKB_CB(next)` in `T_DBG3()`.

Comment (i-rinat) [reply tempesta_fw/tls.c]: I've changed comment to mention why we are calling `tfw_tls_tcp_propagate_dseq()` and why `skb_tail` is used.
