### PR TITLE
Fix incorrect processing of request method by frang

### LINKED ISSUE #1872: frang: parsing of request method with TCP segmentation
# Scope
For frang config:
```
frang_limits {
    http_methods get post;
}
```
Send GET or POST request with TCP segmentation 1 byte:
AR: Tempesta returns 403 response and dmesg warning `frang: restricted HTTP method for 127.0.0.1: 17 (0x20000u)`;
ER: Tempesta forwards request to server;

# Testing
`t_frang.test_http_methods.FrangHttpMethodsTestCase` and `t_frang.test_http_method_override_allowed.FrangHttpMethodsOverrideTestCase` with -T 1 option

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
When we send request with TCP SEGMENTATION, we call frang on each parsed byte. But when we parse request method we set it value to _TFW_HTTP_METH_UNKNOWN,
before we finish parsing request method. Implement additional value for request method, to mark that
we not fully parse request method and do not process such method value by frang.

Closes #1872

### CODE REVIEW

File: fw/http.h [hunk 1]
```diff
@@ -114,6 +114,7 @@ typedef enum {
 	TFW_HTTP_METH_PURGE,
 	/* Unknown method, passed to upstream without additional processing. */
 	_TFW_HTTP_METH_UNKNOWN,
+	_TFW_HTTP_METH_MAYBE_UNKNOWN,
```
Comment (keshonok) [inline fw/http.h:117]: `_TFW_HTTP_METH_INCOMPLETE` might be a better name for this purpose.

File: fw/http_parser.c [hunk 2]
```diff
@@ -5551,8 +5551,8 @@ do {									\
 	__fsm_n += step_inc;						\
 	goto match_meth;						\
 } while (0)
-#define __MK_METH_UNKNOWN()						\
-do { req->method = _TFW_HTTP_METH_UNKNOWN; } while (0)
+#define __MK_METH_INCOMPLETE()						\
+do { req->method = _TFW_HTTP_METH_INCOMPLETE; } while (0)
```
Comment (krizhanovsky) [inline fw/http_parser.c:5555]: I'd propose to not to go with the single line macro and just directly assign the method to `req->method` in the code

**Review by krizhanovsky — APPROVED** [review]
LGTM
