### PR TITLE
Fix #1175: Add synchronization of disconnect procedure for server con…

### LINKED ISSUE #1175: Race condition during stopping of server connection.
The crash occurred during long tests on 9011 server (dump `201812220406`):
```
[133672.417707] [tempesta] Warning: request dropped: processing error, status 502: 192.168.0.2
[133672.417719] [tempesta] Warning: request dropped: processing error, status 502: 192.168.0.2
[133672.417723] [tempesta] Warning: request dropped: processing error, status 502: 192.168.0.2
[133672.417727] [tempesta] Warning: request dropped: processing error, status 502: 192.168.0.2
[133672.417728] [tempesta] Warning: request dropped: processing error, status 502: 192.168.0.2
[133672.417731] [tempesta] Warning: request dropped: processing error, status 502: 192.168.0.2
[133672.417745] [tempesta] Warning: request dropped: processing error, status 502: 192.168.0.2
[133672.417746] [tempesta] Warning: request dropped: processing error, status 502: 192.168.0.2
[133672.417749] [tempesta] Warning: request dropped: processing error, status 502: 192.168.0.2
[133676.171920] ------------[ cut here ]------------
[133676.176810] kernel BUG at /root/builds/tempesta/source/tempesta_fw/connection.h:449!
[133676.184846] invalid opcode: 0000 [#1] SMP PTI
[133676.189501] Modules linked in: tempesta_fw(O) tempesta_db(O) tempesta_tls(O) tempesta_lib(O) iptable_mangle xt_mark tcp_diag inet_diag fuse 8021q garp mrp stp mlx5_core llc mlx4_ib ib_core mlx4_en intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm ast irqbypass ttm crct10dif_pclmul crc32_pclmul drm_kms_helper iTCO_wdt ghash_clmulni_intel iTCO_vendor_support mei_me intel_cstate intel_uncore igb ipmi_si drm dca pcspkr joydev intel_rapl_perf i2c_algo_bit mei i2c_i801 intel_pch_thermal ipmi_devintf sg ie31200_edac ipmi_msghandler video button mlx4_core devlink ptp pps_core ip_tables x_tables autofs4 ext4 crc16 mbcache jbd2 crc32c_generic fscrypto ecb sd_mod evdev hid_generic usbhid hid crc32c_intel mpt3sas xhci_pci raid_class xhci_hcd scsi_transport_sas aesni_intel aes_x86_64 crypto_simd
[133676.262538]  scsi_mod cryptd usbcore glue_helper usb_common shpchp fan thermal [last unloaded: tempesta_lib]
[133676.272771] CPU: 1 PID: 16 Comm: ksoftirqd/1 Tainted: G           O    4.14.0-tempesta-amd64 #1 Debian 4.14.32-tfw1-1~bpo9+1
[133676.284392] Hardware name: Supermicro Super Server/X11SSL-CF, BIOS 1.0a 01/29/2016
[133676.292384] task: ffff8ad2b3f78f80 task.stack: ffff9eecc3218000
[133676.292393] RIP: 0010:tfw_sock_srv_del_conns+0x117/0x130 [tempesta_fw]
[133676.292394] RSP: 0018:ffff9eecc321bd80 EFLAGS: 00010203
[133676.292395] RAX: 0000000000000001 RBX: ffff8ad1b72d0118 RCX: dead000000000200
[133676.292395] RDX: ffff8ad1b72d17d8 RSI: 00000000fffffe01 RDI: ffffffffc0bd2847
[133676.292396] RBP: ffff8ad1b72d00e0 R08: ffff8ad1b72d0b60 R09: 000000018024000e
[133676.292396] R10: ffff9eecc321bca0 R11: 0000000000000000 R12: ffff8ad1ade480c8
[133676.292397] R13: ffff8ad1b72d17a0 R14: ffff8ad1ade480b8 R15: ffffffffc102e858
[133676.292398] FS:  0000000000000000(0000) GS:ffff8ad2f7840000(0000) knlGS:0000000000000000
[133676.292398] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[133676.292399] CR2: 000000000206bbe4 CR3: 00000001a880a003 CR4: 00000000003606e0
[133676.292400] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[133676.292400] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[133676.292400] Call Trace:
[133676.292408]  tfw_server_destroy+0x1a/0x70 [tempesta_fw]
[133676.292412]  ss_tx_action+0x438/0x550 [tempesta_fw]
[133676.292415]  ? mlx4_en_poll_rx_cq+0xc1/0x100 [mlx4_en]
[133676.292417]  ? net_rx_action+0x25d/0x3f0
[133676.292418]  net_tx_action+0x9e/0x1d0
[133676.292419]  __do_softirq+0x10f/0x2a8
[133676.292422]  run_ksoftirqd+0x1c/0x40
[133676.292424]  smpboot_thread_fn+0x10e/0x160
[133676.292425]  kthread+0xff/0x130
[133676.292426]  ? sort_range+0x20/0x20
[133676.292427]  ? kthread_create_on_node+0x70/0x70
[133676.292429]  ret_from_fork+0x35/0x40
[133676.292430] Code: 21 49 8b 85 88 00 00 00 48 85 c0 74 13 49 8b 4d 38 4c 89 ed 49 89 d5 48 39 cb 0f 85 34 ff ff ff 0f 0b 5b 5d 41 5c 41 5d 41 5e c3 <0f> 0b 0f 0b 0f 0b 0f 0b 0f 0b 0f 0b 0f 0b 90 66 2e 0f 1f 84 00
[133676.292448] RIP: tfw_sock_srv_del_conns+0x117/0x130 [tempesta_fw] RSP: ffff9eecc321bd80
```

### PR DESCRIPTION
**Pull request by aleksostapenko**
…nections.

### CODE REVIEW

File: tempesta_fw/sock_srv.c [hunk 1]
```diff
@@ -229,10 +237,6 @@ tfw_sock_srv_connect_try_later(TfwSrvConn *srv_conn)
 {
 	unsigned long timeout;
 
-	/* Don't rearm the reconnection timer if we're about to shutdown. */
-	if (unlikely(!ss_active()))
-		return;
```
Comment (krizhanovsky) [inline tempesta_fw/sock_srv.c]: Why should we reconnect if we're about to shutdown? This may lead new reconnection/shutdown races.

File: tempesta_fw/sock_srv.c [hunk 2]
```diff
@@ -307,18 +311,11 @@ tfw_srv_conn_release(TfwSrvConn *srv_conn)
 	 * in deferred context after a short pause (in a timer
```
Comment (krizhanovsky) [inline tempesta_fw/sock_srv.c]: By the way, `tfw_srv_conn_release()` is called only in this file, so please make it static and remove it's declaration from `server.h`.

File: tempesta_fw/sock_srv.c [hunk 3]
```diff
@@ -143,6 +150,7 @@ tfw_sock_srv_connect_try(TfwSrvConn *srv_conn)
 	                   &sk);
 	if (r) {
 		TFW_ERR("Unable to create server socket\n");
+		tfw_srv_conn_stop(srv_conn);
```
[the remark this answers is not in the document]
Comment (aleksostapenko) [reply tempesta_fw/sock_srv.c]: If we exit here on error from `ss_sock_create()`, there will be no more calls to `tfw_sock_srv_connect_try()` since the timer is expired (and, consequently, deactivated) and not rearmed (as e.g. below - after `ss_connect()` error). So, in fact - the connection will be stopped here and we need to set appropriate bit and put the server. This behavior provides determination of all states in which connection is allowed to be, and support consistency with the waiting cycle in `tfw_sock_srv_disconnect()` (as described in [comment](https://github.com/tempesta-tech/tempesta/blob/0fc370f5d3cc47df513dab7dbe214fd46eb12c8c/tempesta_fw/sock_srv.c#L451)).

File: tempesta_fw/sock_srv.c (hunk 1 above)
Comment (aleksostapenko) [reply tempesta_fw/sock_srv.c]: This check doesn't save us from reconnections on shutdown: failovering thread can pass this check before we set `false` for `__ss_active` during shutdown process, and we can get into `tfw_sock_srv_disconnect()` during live reconnection attempt. To prevent all these races - the waiting cycle had been introduced in `tfw_sock_srv_disconnect()`; so now if we missed connection during shutdown and it has time to begin `tfw_sock_srv_connect_try_later()`, it will still be stopped before reconnection attempt - due to successful timer deactivation in cycle [here](https://github.com/tempesta-tech/tempesta/blob/0fc370f5d3cc47df513dab7dbe214fd46eb12c8c/tempesta_fw/sock_srv.c#L479); in the rare worst case (which we cannot avoid in any way, in current architecture), when the timer handler is already started, and `del_timer_sync()` failed and return 0 (after handler finished), then three variants are possible:
1. Connection will be stopped [here](https://github.com/tempesta-tech/tempesta/blob/0fc370f5d3cc47df513dab7dbe214fd46eb12c8c/tempesta_fw/sock_srv.c#L151) (see [comment](https://github.com/tempesta-tech/tempesta/pull/1179/files#r255839826) above);
2. Connection destructor will be called [here](https://github.com/tempesta-tech/tempesta/blob/0fc370f5d3cc47df513dab7dbe214fd46eb12c8c/tempesta_fw/sock_srv.c#L201) and connection will be definitely stopped in it (since `TFW_CONN_B_DEL` is already set);
3. Connection is successfully restored, its reference count will became not equal `TFW_CONN_DEATHCNT` - then connection will be stopped in usual way, via `tfw_connection_close()` [here](https://github.com/tempesta-tech/tempesta/blob/0fc370f5d3cc47df513dab7dbe214fd46eb12c8c/tempesta_fw/sock_srv.c#L489).

In all these cases the race conditions are avoided, since we are waiting in `tfw_sock_srv_disconnect()` until connection will be stopped consistently before cleaning any of its resources.

File: tempesta_fw/sock_srv.c [hunk 4]
```diff
@@ -126,6 +126,13 @@ static const unsigned long tfw_srv_tmo_vals[] = { 1, 10, 100, 250, 500, 1000 };
 	TFW_WARN_MOD_ADDR(sock_srv, check, addr, TFW_NO_PORT, fmt,	\
```
[the remark this answers is not in the document]
Comment (aleksostapenko) [reply tempesta_fw/sock_srv.c]: Done.

File: tempesta_fw/sock_srv.c (hunk 2 above)
Comment (aleksostapenko) [reply tempesta_fw/sock_srv.c]: Done.

File: tempesta_fw/sock_srv.c [hunk 5]
```diff
@@ -434,33 +430,76 @@ static const SsHooks tfw_sock_srv_ss_hooks = {
  * If a server connection is closed at the time this function runs, then
  * it had been closed by a backend before the shutdown, and the connection
  * is still in failover (not re-connected yet). The resources attached to
- * the connection had not been released, and it has to be done forcefully.
+ * the connection may had not been released, and it has to be done forcefully.
  */
 static int
 tfw_sock_srv_disconnect(TfwConn *conn)
```
Comment (ikoveshnikov) [inline tempesta_fw/sock_srv.c]: The function always returns `0`, so it can be `void`. Frankly, the non-success return code from `disconnect()` is quite a strange thing.

File: tempesta_fw/sock_srv.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (ikoveshnikov) [reply tempesta_fw/sock_srv.c]: Seems like the error may happen at Nth reconnect attempt, and connection will never be connected again.

File: tempesta_fw/sock_srv.c (hunk 5 above)
Comment (aleksostapenko) [reply tempesta_fw/sock_srv.c]: There may be one case when the function can return non-zero value: if `tfw_connection_close()` failed, so we cannot stop connection in this case, and should return error code.

File: tempesta_fw/sock_srv.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (aleksostapenko) [reply tempesta_fw/sock_srv.c]: Added reconnecting on OOM.
