### PR TITLE
Fix #692 & #615: skb page refcounting, forwarded skb initialization

### LINKED ISSUE #692: Server failovering may cause crashes under load or during getting of perfstat
Hard to reproduce.

Ways to reproduce:
1. start nginx on host 1, Keep-alive requests limit = 100;
2. start tempesta on host 1;
3. run wrk  on host 2;
4. read performance stats.

In this case i have 80-95% probability of crash during `wrk` job or when reading statistics. Running all the programs on same host  does not cause crash. If nginx's keep-alive requests limit will be set to some big value (e.g. 1M, nginx does not allow to switch off the limitation) crash does not happen.

Here are my configs:
Nginx:
```

pid /home/user/nginx/nginx_8000.pid ;
worker_processes 1 ;

events {
    worker_connections   1024;
    use epoll;
}

http {
    keepalive_timeout 65;
    keepalive_requests 100;
    sendfile         on;
    tcp_nopush       on;
    tcp_nodelay      on;

    open_file_cache max=1000;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors off;

    # [ debug | info | notice | warn | error | crit | alert | emerg ]
    # Fully disable log errors.
    error_log /dev/null emerg;

    # Disable access log altogether.
    access_log off;

    server {
        listen 8000 ;

        location / {
            root /srv/http ;
        }
        location /nginx_status {
            stub_status on;
        }
    }
}
  
```

Tempesta:
```
cache 0;
sched round-robin;
server 10.0.10.2:8000;
```

Script to reproduce, run it on host 2.
```
#!/bin/bash

TEMPESTA_HOST="root@10.0.10.2"
TEMPESTA_DIR="/home/user/tempesta"
NGINX_CONFIG="/home/user/nginx/nginx_8000.conf"
NGINX_PIDFILE="/home/user/nginx/nginx_8000.pid"
WRK="wrk"

REMOTE='true'
if [ ${REMOTE} != 'true' ]; then
        RUN='eval '
else
        RUN="ssh ${TEMPESTA_HOST} "
fi

echo Start nginx...
${RUN} "nginx -c ${NGINX_CONFIG}"
echo Start Tempesta...
${RUN} "${TEMPESTA_DIR}/scripts/tempesta.sh --start"
sleep 2
echo "Run Wrk for 5 secondss..."
${WRK} -d 5 -t 4 -c 10 http://10.0.10.2/
echo Get Tempesta perfstats...
${RUN} "cat /proc/tempesta/perfstat"
echo Stop Tempesta....
${RUN} "${TEMPESTA_DIR}/scripts/tempesta.sh --stop"
echo stop nginx...
${RUN} "xargs -a ${NGINX_PIDFILE} kill -s TERM"
```

Crash dump:
```
[   77.480951] [tdb] Start Tempesta DB
[   77.485841] [tempesta] Initializing Tempesta FW kernel module...
[   77.492390] [tempesta] Registering new scheduler: hash
[   77.494745] [tempesta] Registering new scheduler: http
[   77.497258] [tempesta] Registering new scheduler: round-robin
[   77.500871] [tempesta] Starting all modules...
[   77.511487] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff88007c400000
[   77.513919] [tempesta] Open listen socket on: 0.0.0.0
[   77.515172] [tempesta] modules are started
[   83.199119] [tempesta] Warning: Unable to find a backend server
[   83.200107] [tempesta] Warning: Unable to find a backend server
[   83.200472] [tempesta] Warning: Unable to find a backend server
[   83.200490] [tempesta] Warning: Unable to find a backend server
[   83.200504] [tempesta] Warning: Unable to find a backend server
[   83.248867] [tempesta] Warning: Unable to find a backend server
[   83.248900] [tempesta] Warning: Unable to find a backend server
[   83.248906] [tempesta] Warning: Unable to find a backend server
[   83.248910] [tempesta] Warning: Unable to find a backend server
[   83.248913] [tempesta] Warning: Unable to find a backend server
[   84.507090] ------------[ cut here ]------------
[   84.507992] kernel BUG at net/core/skbuff.c:1667!
[   84.508440] invalid opcode: 0000 [#1] PREEMPT SMP
[   84.508961] Modules linked in: tfw_sched_rr(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) tempesta_tls(O) mousedev crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel snd_hda_codec_generic bochs_drm snd_hda_intel aesni_intel ttm aes_x86_64 lrw snd_hda_codec ppdev gf128mul glue_helper iTCO_wdt ablk_helper iTCO_vendor_support drm_kms_helper cryptd snd_hda_core evdev input_leds led_class mac_hid snd_hwdep psmouse pcspkr snd_pcm snd_timer snd drm acpi_cpufreq soundcore parport_pc syscopyarea sysfillrect sysimgblt fb_sys_fops lpc_ich tpm_tis intel_agp i2c_i801 shpchp i2c_smbus tpm_tis_core intel_gtt tpm parport qemu_fw_cfg button sch_fq_codel ip_tables x_tables ext4 crc16 jbd2 fscrypto mbcache sr_mod cdrom virtio_console virtio_net virtio_blk virtio_balloon serio_raw atkbd libps2 uhci_hcd ahci libahci virtio_pci virtio_ring virtio libata scsi_mod ehci_pci ehci_hcd usbcore usb_common i8042 serio
[   84.519036] CPU: 1 PID: 0 Comm: swapper/1 Tainted: G           O    4.8.15-3-tempesta #3
[   84.520845] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.10.1-20161122_114906-anatol 04/01/2014
[   84.522157] task: ffff88005c8ce3c0 task.stack: ffff88005c8e0000
[   84.523535] RIP: 0010:[<ffffffff814d77e0>]  [<ffffffff814d77e0>] skb_put+0x40/0x60
[   84.525864] RSP: 0018:ffff88007fd03878  EFLAGS: 00010202
[   84.526914] RAX: ffff88005b948c30 RBX: ffff88005b948a00 RCX: ffff88005b948cf0
[   84.528218] RDX: 0000000000000130 RSI: 0000000000000011 RDI: ffff88005b948a00
[   84.529528] RBP: ffff88007fd03960 R08: 0000000000000130 R09: ffff88005b948a00
[   84.530762] R10: 0000000000000000 R11: 0000000000000053 R12: 0000000000000011
[   84.531785] R13: 00000000000005a8 R14: ffff88005938a8f0 R15: 0000000000000000
[   84.533032] FS:  0000000000000000(0000) GS:ffff88007fd00000(0000) knlGS:0000000000000000
[   84.534040] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   84.535282] CR2: 000055e1b81ba588 CR3: 000000005b909000 CR4: 00000000003406e0
[   84.537277] Stack:
[   84.537722]  ffffffff814d8f4e ffff88007fd038c0 ffffffffffffffbe 000000000000000a
[   84.539097]  ffff880002026600 00000053fffffff4 0000000000000000 0000000000000042
[   84.540472]  00000000000000ee 0000000000000001 ffff88005b948a00 0000000000000042
[   84.541713] Call Trace:
[   84.542021]  <IRQ> 
[   84.542392]  [<ffffffff814d8f4e>] ? skb_segment+0x50e/0xc30
[   84.543438]  [<ffffffffa04e7e1c>] ? tfw_http_conn_send+0x1c/0x20 [tempesta_fw]
[   84.544692]  [<ffffffff815575f3>] tcp_gso_segment+0xf3/0x4d0
[   84.545686]  [<ffffffffa04e8c40>] ? tfw_http_send_502+0xf0/0xf0 [tempesta_fw]
[   84.546960]  [<ffffffff81548430>] ? tcp_event_new_data_sent+0x90/0x90
[   84.548091]  [<ffffffff81557a0e>] tcp4_gso_segment+0x3e/0xa0
[   84.548994]  [<ffffffff815688de>] inet_gso_segment+0x13e/0x3a0
[   84.549737]  [<ffffffff814ebf7a>] skb_mac_gso_segment+0xba/0x130
[   84.550256]  [<ffffffff814ec0ad>] __skb_gso_segment+0xbd/0x150
[   84.551412]  [<ffffffff814ec533>] validate_xmit_skb+0x153/0x2d0
[   84.552736]  [<ffffffff814ec6f3>] validate_xmit_skb_list+0x43/0x70
[   84.554278]  [<ffffffff81514d49>] sch_direct_xmit+0x169/0x1b0
[   84.555453]  [<ffffffff814ecdd0>] __dev_queue_xmit+0x3b0/0x670
[   84.556098]  [<ffffffff814ed0a0>] dev_queue_xmit+0x10/0x20
[   84.556624]  [<ffffffff8152edc7>] ip_finish_output2+0x1a7/0x370
[   84.557154]  [<ffffffff81552c00>] ? tcp_v4_rcv+0xbd0/0xdc0
[   84.557649]  [<ffffffff815309a8>] ip_finish_output+0x128/0x1c0
[   84.558179]  [<ffffffff8153146e>] ip_output+0x6e/0xf0
[   84.558634]  [<ffffffff814d2dbc>] ? __pg_skb_alloc+0x25c/0x500
[   84.559164]  [<ffffffff81530be5>] ip_local_out+0x35/0x40
[   84.559644]  [<ffffffff81530f10>] ip_queue_xmit+0x160/0x3b0
[   84.560165]  [<ffffffff81549b8e>] tcp_transmit_skb+0x48e/0x910
[   84.560705]  [<ffffffff8154a1ed>] tcp_write_xmit+0x1dd/0xf00
[   84.561221]  [<ffffffff8154b1a5>] __tcp_push_pending_frames+0x35/0xd0
[   84.561810]  [<ffffffff81538c7e>] tcp_push+0xee/0x110
[   84.562278]  [<ffffffffa0500780>] ss_tx_action+0x330/0x3a0 [tempesta_fw]
[   84.563062]  [<ffffffff810aa8b9>] ? try_to_wake_up+0x189/0x3b0
[   84.563942]  [<ffffffff814e89f4>] net_tx_action+0xa4/0x210
[   84.564453]  [<ffffffff81602552>] __do_softirq+0x112/0x2d7
[   84.565035]  [<ffffffff81085e03>] irq_exit+0xa3/0xb0
[   84.565487]  [<ffffffff81050543>] smp_call_function_single_interrupt+0x33/0x40
[   84.566184]  [<ffffffff81601bd2>] call_function_single_interrupt+0x82/0x90
[   84.567590]  <EOI> 
[   84.567785]  [<ffffffff810605f6>] ? native_safe_halt+0x6/0x10
[   84.568375]  [<ffffffff81037c70>] default_idle+0x20/0x110
[   84.569049]  [<ffffffff8103843f>] arch_cpu_idle+0xf/0x20
[   84.569784]  [<ffffffff810c4aca>] default_idle_call+0x2a/0x40
[   84.570725]  [<ffffffff810c4df1>] cpu_startup_entry+0x311/0x380
[   84.571410]  [<ffffffff81050f18>] start_secondary+0x158/0x1a0
[   84.571931] Code: f6 87 a3 00 00 00 20 75 22 8b 8f 94 00 00 00 85 c9 75 18 01 f2 01 b7 90 00 00 00 3b 97 dc 00 00 00 89 97 d8 00 00 00 77 04 f3 c3 <0f> 0b 55 48 c7 c1 d0 13 88 81 48 89 e5 48 8b 55 08 e8 8a eb ff 
[   84.575094] RIP  [<ffffffff814d77e0>] skb_put+0x40/0x60
[   84.575589]  RSP <ffff88007fd03878>
[   84.575946] ---[ end trace 4688883cc6ef63c0 ]---
[   84.576468] Kernel panic - not syncing: Fatal exception in interrupt
[   84.577228] Kernel Offset: disabled
[   84.577565] ---[ end Kernel panic - not syncing: Fatal exception in interrupt
```

Tempesta rev: 7672713c5b928a7d1421ce65d8df24d4d1dd9d38

### PR DESCRIPTION
**Pull request by krizhanovsky**
1. Fix #692 in the kernel.

2. ss_skb_init_for_xmit() initializes forwarded skbs;

3. Protect tcp_v4_connect() -> tcp_connect() by the socket lock to let it
   finish it's operation before getting response (e.g. ACK) from the peer
   (crucial for loopback connections sending packets just by function calls);

4. Add assertions to guarantee that socket lock is aquired by current CPU;

5. Many replacements of BUG() assertions by WARN_ON_ONCE() for better
   reliability.

6. Define TFW_CLASSIFIER_ACCSZ in dependence on CONFIG_DEBUG_LOCK_ALLOC
   and several other minor fixes and cleanups;

I reviewed UDP/datagram code as well and the patch introduces several
fixes applicable to datagrams (e.g. skb_morph()), so I believe #615 can be safely closed.

### CODE REVIEW

File: tempesta_fw/ss_skb.c [hunk 1]
```diff
@@ -1127,14 +1175,14 @@ ss_skb_unroll(SsSkbList *skb_list, struct sk_buff *skb)
...
-	 * not break the things we must take reference back.
-	 */
 	ss_skb_queue_tail(skb_list, skb);
 	skb_walk_frags(skb, f_skb) {
 		if (f_skb->nohdr) {
+			/*
+			 * skb_gro_receive() drops reference to the SKB's header
+			 * via the __skb_header_release(). So, to not break the
+			 * things we must take reference back.
+			 */
```
Comment (keshonok) [inline tempesta_fw/ss_skb.c]: Frankly, I believe that original placement of this comment was better. This is a small piece of code, and it looks dense, nice, and very readable. The comment explains what happens in the logical block of code that follows it, and it's sufficient for understanding the block of code.  Placing multi-line comment in the middle of it just dilutes this small block of code and makes it a bit more difficult to follow.

I know that this may be a matter of taste. :-) I believe the code in the kernel in general is written more like to what I describe above.
