### PR TITLE
fix(2169): save `msg->ss_flags` for later access

### LINKED ISSUE #2169: Hang with use-after-free in tfw_tls_conn_send+0x66
Run Tempesta FW in a 4 CPU VM with 8GB RAM of version #2162. Run `taskset --cpu-list 6,7,8,9,10,11,12,13 h2load -n 1000000 -c 1024 -t 8 -m 50 https://tempesta-tech.com` and on 60% of requests I got the KASAN report:
```
[ 3430.520348] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.521546] ==================================================================
[ 3430.522798] BUG: KASAN: use-after-free in tfw_tls_conn_send+0x66/0xe0 [tempesta_fw]
[ 3430.523807] Read of size 4 at addr ffff88814cfe5038 by task rs:main Q:Reg/10588
[ 3430.524916]
[ 3430.525508] CPU: 1 PID: 10588 Comm: rs:main Q:Reg Kdump: loaded Tainted: G           O      5.10.35-tfw-secperf+ #7
[ 3430.527046] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014
[ 3430.528468] Call Trace:
[ 3430.529382]  <IRQ>
[ 3430.530264]  dump_stack+0x7d/0xa3
[ 3430.531288]  print_address_description.constprop.0+0x1c/0x210
[ 3430.535477]  ? _raw_spin_lock_irqsave+0x6b/0xb0
[ 3430.536747]  ? _raw_spin_unlock_bh+0x20/0x20
[ 3430.537992]  ? tfw_tls_conn_send+0x66/0xe0 [tempesta_fw]
[ 3430.539391]  kasan_report.cold+0x1f/0x37
[ 3430.540686]  ? tfw_tls_conn_send+0x66/0xe0 [tempesta_fw]
[ 3430.542147]  tfw_tls_conn_send+0x66/0xe0 [tempesta_fw]
[ 3430.543630]  tfw_cli_conn_send+0x17/0x90 [tempesta_fw]
[ 3430.545166]  tfw_h2_resp_fwd+0x78/0x180 [tempesta_fw]
[ 3430.546677]  tfw_h2_send_err_resp+0xca/0xf0 [tempesta_fw]
[ 3430.548256]  ? tfw_h2_send_resp+0x90/0x90 [tempesta_fw]
[ 3430.549858]  ? ___ratelimit+0xf4/0x1b0
[ 3430.549926] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 200 0 "-" "h2load nghttp2/1.43.0"
[ 3430.551345]  tfw_http_send_err_resp+0x9c/0x160 [tempesta_fw]
[ 3430.555767]  ? tfw_http_cli_error_resp_and_log+0x3b0/0x3b0 [tempesta_fw]
[ 3430.557760]  tfw_http_req_zap_error+0x86/0x1d0 [tempesta_fw]
[ 3430.559691]  tfw_http_popreq+0x40c/0xae0 [tempesta_fw]
[ 3430.561601]  ? frang_resp_handler+0x1a8/0x640 [tempesta_fw]
[ 3430.563617]  ? tfw_http_req_zap_error+0x1d0/0x1d0 [tempesta_fw]
[ 3430.565699]  ? tfw_http_parse_resp+0xaa2/0x1c430 [tempesta_fw]
[ 3430.567780]  ? ktime_get_real_ts64+0xdc/0x130
[ 3430.568767] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.569771]  tfw_http_resp_cache+0x104/0x320 [tempesta_fw]
[ 3430.572784] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.575076]  ? tfw_gfsm_move+0xfa/0x4e0 [tempesta_fw]
[ 3430.575098]  ? tfw_http_conn_repair+0x8f0/0x8f0 [tempesta_fw]
[ 3430.575122]  tfw_http_resp_process+0x64f/0x7d0 [tempesta_fw]
[ 3430.578762] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.581128]  ? tfw_http_conn_drop+0x2c0/0x2c0 [tempesta_fw]
[ 3430.581134]  ? __ip_finish_output+0x151/0x340
[ 3430.584004] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.586442]  ? pcpu_get_vm_areas+0x200/0x1a00
[ 3430.586445]  ? ip_output+0xfb/0x1b0
[ 3430.586446]  ? ip_mc_output+0x420/0x420
[ 3430.586469]  tfw_http_msg_process_generic+0x14f/0x330 [tempesta_fw]
[ 3430.586492]  ? tfw_http_req_process+0xc00/0xc00 [tempesta_fw]
[ 3430.589843] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.592423]  ? __ip_queue_xmit+0x365/0x7d0
[ 3430.595881] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.598928]  ? tfw_http_msg_process+0x20/0xa0 [tempesta_fw]
[ 3430.598952]  tfw_connection_recv+0x14f/0x200 [tempesta_fw]
[ 3430.602091] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.604709]  ? tfw_connection_send+0x60/0x60 [tempesta_fw]
[ 3430.604733]  ss_tcp_process_skb.constprop.0+0x29c/0x590 [tempesta_fw]
[ 3430.604758]  ? __sk_close_locked+0x110/0x110 [tempesta_fw]
[ 3430.604761]  ? __tcp_send_ack+0x189/0x2a0
[ 3430.604784]  ss_tcp_process_data+0x1ef/0x310 [tempesta_fw]
[ 3430.604807]  ? ss_tcp_process_skb.constprop.0+0x590/0x590 [tempesta_fw]
[ 3430.604809]  ? __tcp_select_window+0x155/0x390
[ 3430.604831]  ss_tcp_data_ready+0x8f/0x1a0 [tempesta_fw]
[ 3430.604833]  tcp_rcv_established+0x8fb/0xe40
[ 3430.604836]  ? tcp_data_queue+0xac0/0xac0
[ 3430.604839]  ? bpf_skb_adjust_room+0x2f0/0x310
[ 3430.604841]  tcp_v4_do_rcv+0x24a/0x340
[ 3430.604843]  tcp_v4_rcv+0x13ac/0x14b0
[ 3430.604845]  ? tcp_v4_early_demux+0x2e0/0x2e0
[ 3430.604848]  ip_protocol_deliver_rcu+0x39/0x2f0
[ 3430.604851]  ip_local_deliver_finish+0xac/0xd0
[ 3430.604853]  ip_local_deliver+0xe9/0x1a0
[ 3430.604855]  ? ip_local_deliver_finish+0xd0/0xd0
[ 3430.604857]  ? ip_rcv_finish_core.constprop.0+0x166/0x5b0
[ 3430.604859]  ip_rcv+0x12e/0x140
[ 3430.604861]  ? ip_local_deliver+0x1a0/0x1a0
[ 3430.604863]  ? ip_rcv_finish_core.constprop.0+0x5b0/0x5b0
[ 3430.604865]  ? ip_local_deliver+0x1a0/0x1a0
[ 3430.604868]  __netif_receive_skb_one_core+0xb9/0xf0
[ 3430.604870]  ? __netif_receive_skb_core+0x1750/0x1750
[ 3430.604873]  ? _raw_spin_lock+0x65/0xa0
[ 3430.604874]  ? _raw_read_lock_irq+0x30/0x30
[ 3430.604877]  ? nohz_balancer_kick+0x64/0x430
[ 3430.604879]  process_backlog+0xe3/0x270
[ 3430.604881]  napi_poll+0x112/0x3a0
[ 3430.604882]  net_rx_action+0x14f/0x300
[ 3430.604884]  ? napi_poll+0x3a0/0x3a0
[ 3430.604887]  ? __kernel_fpu_begin_mask+0x102/0x120
[ 3430.604890]  ? __list_add_valid+0x2b/0xa0
[ 3430.604892]  __do_softirq+0xf4/0x430
[ 3430.604895]  asm_call_irq_on_stack+0xf/0x20
[ 3430.604896]  </IRQ>
[ 3430.604899]  do_softirq_own_stack+0x32/0x40
[ 3430.604901]  irq_exit_rcu+0xbb/0x110
[ 3430.604904]  sysvec_call_function_single+0x2e/0x80
[ 3430.604906]  asm_sysvec_call_function_single+0x12/0x20
[ 3430.604910] RIP: 0010:__asan_load4+0x55/0x80
[ 3430.604913] Code: 00 00 00 00 00 fc ff df 48 c1 e8 03 0f b6 04 08 84 c0 75 33 c3 48 b9 00 00 00 00 00 fc ff df 48 89 fe 48 c1 ee 03 80 3c 0e 00 <74> 0f 4c 89 c1 31 d2 be 04 00 00 00 e9 8a fb ff ff 48 c1 e8 03 0f
[ 3430.604915] RSP: 0018:ffff8880326d7598 EFLAGS: 00000246
[ 3430.604918] RAX: ffffffffc0979590 RBX: ffffffffc08ccf68 RCX: dffffc0000000000
[ 3430.604919] RDX: 0000000000000000 RSI: 1ffffffff812f2b1 RDI: ffffffffc097958d
[ 3430.604921] RBP: ffffffffc096ffd9 R08: ffffffffa9c88483 R09: ffffffffc098b5ac
[ 3430.604922] R10: fffffbfff81316b5 R11: 0000000000000001 R12: ffffffffc096ffd9
[ 3430.604923] R13: ffffffffc0982b45 R14: ffffffffc097958d R15: ffffffffc096ffd9
[ 3430.604956]  ? ext4_da_write_begin+0x398/0x5d0 [ext4]
[ 3430.604959]  ? __orc_find+0x63/0xc0
[ 3430.604961]  __orc_find+0x63/0xc0
[ 3430.604963]  unwind_next_frame+0x107/0x8d0
[ 3430.604994]  ? ext4_da_write_begin+0x399/0x5d0 [ext4]
[ 3430.604997]  ? __module_address+0x141/0x1d0
[ 3430.604998]  ? deref_stack_reg+0xb0/0xb0
[ 3430.605000]  ? is_module_text_address+0x76/0xa0
[ 3430.605030]  ? ext4_da_write_begin+0x399/0x5d0 [ext4]
[ 3430.605061]  ? ext4_da_write_begin+0x399/0x5d0 [ext4]
[ 3430.605063]  ? kernel_text_address+0x40/0x120
[ 3430.605065]  ? stack_trace_save+0xa0/0xa0
[ 3430.605067]  arch_stack_walk+0x61/0xb0
[ 3430.605098]  ? ext4_da_write_begin+0x399/0x5d0 [ext4]
[ 3430.605100]  stack_trace_save+0x7c/0xa0
[ 3430.605102]  ? create_prof_cpu_mask+0x20/0x20
[ 3430.605104]  kasan_save_stack+0x1b/0x40
[ 3430.605106]  ? kasan_save_stack+0x1b/0x40
[ 3430.605107]  ? __kasan_kmalloc.constprop.0+0xc2/0xd0
[ 3430.605109]  ? kmem_cache_alloc+0xcd/0x220
[ 3430.605118]  ? jbd2__journal_start+0xe9/0x340 [jbd2]
[ 3430.605147]  ? __ext4_journal_start_sb+0x181/0x1a0 [ext4]
[ 3430.605177]  ? ext4_truncate+0x267/0x6f0 [ext4]
[ 3430.605208]  ? ext4_da_write_begin+0x399/0x5d0 [ext4]
[ 3430.605210]  ? stack_trace_save+0xa0/0xa0
[ 3430.605211]  ? arch_stack_walk+0x71/0xb0
[ 3430.605213]  ? _raw_spin_lock+0x65/0xa0
[ 3430.605214]  ? _raw_read_lock_irq+0x30/0x30
[ 3430.605216]  ? __list_add_valid+0x2b/0xa0
[ 3430.605218]  ? deactivate_slab+0x459/0x660
[ 3430.605226]  ? jbd2__journal_start+0xe9/0x340 [jbd2]
[ 3430.605227]  ? set_track+0x4b/0xc0
[ 3430.605229]  ? init_object+0x49/0x80
[ 3430.605231]  ? alloc_debug_processing+0x42/0x160
[ 3430.605233]  ? ___slab_alloc+0x239/0x470
[ 3430.605241]  ? jbd2__journal_start+0xe9/0x340 [jbd2]
[ 3430.605242]  ? kasan_unpoison_shadow+0x34/0x40
[ 3430.605244]  __kasan_kmalloc.constprop.0+0xc2/0xd0
[ 3430.605246]  kmem_cache_alloc+0xcd/0x220
[ 3430.605254]  jbd2__journal_start+0xe9/0x340 [jbd2]
[ 3430.605285]  __ext4_journal_start_sb+0x181/0x1a0 [ext4]
[ 3430.605316]  ext4_truncate+0x267/0x6f0 [ext4]
[ 3430.605347]  ? ext4_punch_hole+0x780/0x780 [ext4]
[ 3430.605349]  ? down_read_killable+0x180/0x180
[ 3430.605380]  ext4_da_write_begin+0x399/0x5d0 [ext4]
[ 3430.605411]  ? ext4_write_begin+0x790/0x790 [ext4]
[ 3430.605412]  ? ktime_get_coarse_real_ts64+0x4a/0x90
[ 3430.605415]  generic_perform_write+0x146/0x290
[ 3430.605417]  ? add_page_wait_queue+0xf0/0xf0
[ 3430.605419]  ? current_time+0x160/0x160
[ 3430.605450]  ext4_buffered_write_iter+0x129/0x220 [ext4]
[ 3430.605453]  new_sync_write+0x22b/0x330
[ 3430.605455]  ? new_sync_read+0x320/0x320
[ 3430.605457]  ? __fsnotify_parent+0x398/0x4b0
[ 3430.605459]  ? rw_verify_area+0x51/0x120
[ 3430.605461]  vfs_write+0x2ae/0x350
[ 3430.605463]  ksys_write+0xa0/0x120
[ 3430.605465]  ? __ia32_sys_read+0x40/0x40
[ 3430.605467]  ? fpregs_assert_state_consistent+0x4d/0x60
[ 3430.605468]  do_syscall_64+0x2d/0x70
[ 3430.605470]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[ 3430.605472] RIP: 0033:0x7f538af288bf
[ 3430.605476] Code: 89 54 24 18 48 89 74 24 10 89 7c 24 08 e8 49 c1 f7 ff 48 8b 54 24 18 48 8b 74 24 10 41 89 c0 8b 7c 24 08 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 31 44 89 c7 48 89 44 24 08 e8 8c c1 f7 ff 48
[ 3430.605477] RSP: 002b:00007f5389a51740 EFLAGS: 00000293 ORIG_RAX: 0000000000000001
[ 3430.605480] RAX: ffffffffffffffda RBX: 00007f537400b8b0 RCX: 00007f538af288bf
[ 3430.605481] RDX: 0000000000000087 RSI: 00007f537400bb90 RDI: 0000000000000008
[ 3430.605482] RBP: 00007f537400bb90 R08: 0000000000000000 R09: 0000000000000000
[ 3430.605483] R10: 0000000000000000 R11: 0000000000000293 R12: 0000000000000000
[ 3430.605485] R13: 000056002c54b4cc R14: 0000000000000087 R15: 00007f537400b8b0
[ 3430.605486]
[ 3430.605487] The buggy address belongs to the page:
[ 3430.605491] page:00000000cf53bb5b refcount:0 mapcount:0 mapping:0000000000000000 index:0x0 pfn:0x14cfe5
[ 3430.605492] flags: 0x2fff80000000000()
[ 3430.605496] raw: 02fff80000000000 ffffea00054dbb48 ffffea0004f23648 0000000000000000
[ 3430.605498] raw: 0000000000000000 0000000000000000 00000000ffffffff 0000000000000000
[ 3430.605499] page dumped because: kasan: bad access detected
[ 3430.605500]
[ 3430.605500] Memory state around the buggy address:
[ 3430.605503]  ffff88814cfe4f00: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
[ 3430.605504]  ffff88814cfe4f80: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
[ 3430.605506] >ffff88814cfe5000: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
[ 3430.605507]                                         ^
[ 3430.605508]  ffff88814cfe5080: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
[ 3430.605510]  ffff88814cfe5100: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
[ 3430.605510] ==================================================================
[ 3430.605512] Disabling lock debugging due to kernel taint
[ 3430.605545] BUG: unable to handle page fault for address: ffff88814cfe5038
[ 3430.605547] #PF: supervisor read access in kernel mode
[ 3430.605548] #PF: error_code(0x0000) - not-present page
[ 3430.605549] PGD 1bca01067 P4D 1bca01067 PUD 23f705067 PMD 23f69d067 PTE 800ffffeb301a060
[ 3430.605554] Oops: 0000 [#1] SMP DEBUG_PAGEALLOC KASAN
[ 3430.605557] CPU: 1 PID: 10588 Comm: rs:main Q:Reg Kdump: loaded Tainted: G    B      O      5.10.35-tfw-secperf+ #7
[ 3430.605559] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014
[ 3430.605580] RIP: 0010:tfw_tls_conn_send+0x66/0xe0 [tempesta_fw]
[ 3430.605581] Code: e8 3f 7b d3 e8 44 89 e2 48 8b bd 40 04 00 00 48 8d 73 10 83 e2 db e8 19 cb fe ff 41 89 c4 85 c0 75 51 4c 89 ef e8 1a 7a d3 e8 <8b> 43 18 41 89 c4 41 83 e4 04 74 3d 83 e0 20 4c 8d ad b8 04 00 00
[ 3430.605583] RSP: 0018:ffff8881f6489000 EFLAGS: 00010282
[ 3430.605584] RAX: 0000000000000001 RBX: ffff88814cfe5020 RCX: ffffffffaa930bad
[ 3430.605585] RDX: 1ffffffff595e9f0 RSI: 0000000000000286 RDI: ffffffffacaf4f80
[ 3430.605587] RBP: ffff888140083910 R08: 0000000000000001 R09: ffffffffacab5d67
[ 3430.605588] R10: fffffbfff5956bac R11: 0000000000000001 R12: 0000000000000000
[ 3430.605589] R13: ffff88814cfe5038 R14: ffff888140083dc0 R15: ffff88812f7e5250
[ 3430.605593] FS:  00007f5389a52640(0000) GS:ffff8881f6480000(0000) knlGS:0000000000000000
[ 3430.605594] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 3430.605595] CR2: ffff88814cfe5038 CR3: 0000000125dd8000 CR4: 0000000000750ee0
[ 3430.605596] PKRU: 55555554
[ 3430.605600] Call Trace:
[ 3430.605602]  <IRQ>
[ 3430.605623]  tfw_cli_conn_send+0x17/0x90 [tempesta_fw]
[ 3430.605642]  tfw_h2_resp_fwd+0x78/0x180 [tempesta_fw]
[ 3430.605660]  tfw_h2_send_err_resp+0xca/0xf0 [tempesta_fw]
[ 3430.605682]  ? tfw_h2_send_resp+0x90/0x90 [tempesta_fw]
[ 3430.608659] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.611174]  ? ___ratelimit+0xf4/0x1b0
[ 3430.611199]  tfw_http_send_err_resp+0x9c/0x160 [tempesta_fw]
[ 3430.615415] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.618707]  ? tfw_http_cli_error_resp_and_log+0x3b0/0x3b0 [tempesta_fw]
[ 3430.618731]  tfw_http_req_zap_error+0x86/0x1d0 [tempesta_fw]
[ 3430.622044] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.625434]  tfw_http_popreq+0x40c/0xae0 [tempesta_fw]
[ 3430.625456]  ? frang_resp_handler+0x1a8/0x640 [tempesta_fw]
[ 3430.625480]  ? tfw_http_req_zap_error+0x1d0/0x1d0 [tempesta_fw]
[ 3430.629003] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.631984]  ? tfw_http_parse_resp+0xaa2/0x1c430 [tempesta_fw]
[ 3430.631990]  ? ktime_get_real_ts64+0xdc/0x130
[ 3430.636330] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 504 0 "-" "h2load nghttp2/1.43.0"
[ 3430.639826]  tfw_http_resp_cache+0x104/0x320 [tempesta_fw]
[ 3430.639851]  ? tfw_gfsm_move+0xfa/0x4e0 [tempesta_fw]
[ 3430.643668] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 200 0 "-" "h2load nghttp2/1.43.0"
[ 3430.646659]  ? tfw_http_conn_repair+0x8f0/0x8f0 [tempesta_fw]
[ 3430.646682]  tfw_http_resp_process+0x64f/0x7d0 [tempesta_fw]
[ 3430.646705]  ? tfw_http_conn_drop+0x2c0/0x2c0 [tempesta_fw]
[ 3430.651616] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 200 0 "-" "h2load nghttp2/1.43.0"
[ 3430.651723] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 200 0 "-" "h2load nghttp2/1.43.0"
[ 3430.654014]  ? __ip_finish_output+0x151/0x340
[ 3430.654022]  ? pcpu_get_vm_areas+0x200/0x1a00
[ 3430.692682] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 200 0 "-" "h2load nghttp2/1.43.0"
[ 3430.693188]  ? ip_output+0xfb/0x1b0
[ 3430.734766] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 200 0 "-" "h2load nghttp2/1.43.0"
[ 3430.738804]  ? ip_mc_output+0x420/0x420
[ 3430.738831]  tfw_http_msg_process_generic+0x14f/0x330 [tempesta_fw]
[ 3430.817926] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 200 0 "-" "h2load nghttp2/1.43.0"
[ 3430.820181]  ? tfw_http_req_process+0xc00/0xc00 [tempesta_fw]
[ 3430.989798] [tempesta fw] 192.168.100.1 "default" "GET / HTTP/2.0" 200 0 "-" "h2load nghttp2/1.43.0"
```

The system hangs. 

The kernel (5.10.35 as of09f6e2a043d099627d0617dbe34c2d1521540927 ) config is in the attachment.

`tfw_tls_conn_send+0x66` corresponds to
```C
static int
tfw_tls_conn_send(TfwConn *c, TfwMsg *msg)
{
        int r;
        TlsCtx *tls = tfw_tls_context(c);

        T_DBG("TLS %lu bytes (%u bytes)"
              " are to be sent on conn=%pK/sk_write_xmit=%pK ready=%d\n",
              msg->len, tls->io_out.msglen + TLS_HEADER_SIZE, c,
              c->sk->sk_write_xmit, ttls_xfrm_ready(tls));

        if (ttls_xfrm_ready(tls)) {
                msg->ss_flags |= SS_SKB_TYPE2F(TTLS_MSG_APPLICATION_DATA) |
                        SS_F_ENCRYPT;
        }

        r = ss_send(c->sk, &msg->skb_head,
                    msg->ss_flags & ~SS_F_CLOSE_FORCE);
        if (r)
                return r;

        /*
         * We can not send the alert on conn_drop hook, because the hook
         * is called on already closed socket.
         */
        if (msg->ss_flags & SS_F_CONN_CLOSE) {            // <===== tfw_tls_conn_send+0x66
                int close_type = msg->ss_flags & __SS_F_FORCE ?
                        TTLS_F_ST_CLOSE : TTLS_F_ST_SHUTDOWN;

                spin_lock(&tls->lock);
                r = ttls_close_notify(tls, close_type);
                spin_unlock(&tls->lock);
        }

        return r;
}
```

[linux-config.txt](https://github.com/user-attachments/files/16202544/linux-config.txt)

Our website [LXC container](https://github.com/tempesta-tech/tempesta-tech.com/tree/master/container#local-staging) is used as a backend and Tempesta FW config is
```
cache 2;
cache_fulfill * *;
cache_methods GET HEAD;
cache_ttl 3600;

listen 192.168.100.4:443 proto=h2,https;
#listen 192.168.100.4:80;

srv_group default {
        server 10.245.18.108:80;
	#server 127.0.0.1:80;
}

tls_certificate /root/tempesta/etc/tfw-root.crt;
tls_certificate_key /root/tempesta/etc/tfw-root.key;

#tls_certificate /home/tempesta/fullchain.pem;
#tls_certificate_key /home/tempesta/privkey.pem;
req_hdr_add X-Forwarded-Proto "https";
resp_hdr_set Strict-Transport-Security "max-age=31536000; includeSubDomains";

vhost default {
        tls_match_any_server_name;
        resp_hdr_set Cache-Control;
        nonidempotent GET * *;
        nonidempotent HEAD * *;
        nonidempotent POST * *;
        proxy_pass default;
}

frang_limits {
#        request_rate 200;
        http_method_override_allowed true;
        http_methods post put get;
}

#cache_purge;
#cache_purge_acl 3.72.94.204 127.0.0.1;

access_log on;

block_action attack reply;
block_action error reply;

http_chain {

        # Set cache_ttl for speciefic locations
        uri == "/blog/*" -> cache_ttl = 1;
        uri == "/knowledge-base/*" -> cache_ttl = 600;

        # Set Security
#        mark == 23 -> default;
        -> default;
}
```

### PR DESCRIPTION
**Pull request by kingluo**
close #2169

The message sending may happen in a softirq on another CPU, which may happen before the next statement referencing `msg->ss_flags`. This means it may access a freed message, triggering a KASAN report.

### CODE REVIEW

File: fw/tls.c [hunk 1]
```diff
@@ -797,6 +797,7 @@ tfw_tls_conn_send(TfwConn *c, TfwMsg *msg)
 {
 	int r;
 	TlsCtx *tls = tfw_tls_context(c);
+	int ss_flags = msg->ss_flags;
```
Comment (keshonok) [inline fw/tls.c:800]: Usually I find your commits commented pretty well. In this case, though, I would really appreciate a more comprehensive commit message (or a block comment here in the code) as it's not really clear (to me) exactly what, why and how happens. Perhaps, it's just me though. Thanks.

Comment (kingluo) [reply fw/tls.c:800]: The commit already has a blocked message besides the first line, which describes why the flag should be saved in the first place. Also, the issue reference link will have detailed background information.

Comment (keshonok) [reply fw/tls.c:800]: Yeah, that's exactly what I was talking about. I didn't understand the commit message which should be self-sufficient and clear enough. From what I can see, we are in the sending function, and a specific message is given to it for sending. Which means no one else can work on it, doesn't it? How would accessing the flags just a few cycles earlier (saving the flags) significantly change the situation? I admit that I don't know this code well enough, but I believe that the commit message should be more comprehensive than it is now. Thanks.

Comment (kingluo) [reply fw/tls.c:800]: Sending to the client (downstream) is asynchronous, and `tfw_tls_conn_send` is in the path of receiving the response from the backend (upstream), and does not actually send.

The CPU is not always exclusively occupied by softirqs, and other hardware interrupts may also preempt the CPU with an indeterminate period. On the other hand, sending (`ss_tx_action`) is not necessarily triggered by an IPI or even softirq, and can be processed quickly if the softirq handler is already running. So, in summary, there is likely a small window that allows the message to be sent and released faster than the next `if` statement in `tfw_tls_conn_send`.

---

Regarding the clarification of the commit message, I think we cannot or are not suitable to describe everything in the commit message unless the issue is extremely simple. Even 10,000 words cannot make it clear to readers without any prior background knowledge. However, we do have to define the commit message to make it clear what it does or why it does it. And I think if the reviewer really does a serious review, he should at least read the issue comments first, or even read some related code to get a prior understanding. And, to be honest, I have no idea how to convert a long issue comment page into a commit message or even code comments: https://github.com/tempesta-tech/tempesta/issues/2169#issuecomment-2247592874.

Last but not least, no offense, please look at the bugfix first and think about the correctness, which is more important than the commit message style.

Comment (EvgeniiMekhanik) [reply fw/tls.c:800]: I can't understand how this  fix help. If msg->ss_flags can be changed on other CPU it can occurs also at line msg->ss_flags |= SS_SKB_TYPE2F(TTLS_MSG_APPLICATION_DATA) or when it is passed to `ss_send`. Moreover there is a chance that it can be canged just before you save it in a local variable. At what place  (what function) changes `ss_flags` on other CPU?

Comment (keshonok) [reply fw/tls.c:800]: @EvgeniiMekhanik -- Yeah, thanks. I failed in making this clear enough.

File: fw/tls.c [hunk 2]
```diff
@@ -817,8 +818,8 @@ tfw_tls_conn_send(TfwConn *c, TfwMsg *msg)
 	 * We can not send the alert on conn_drop hook, because the hook
```
Comment (krizhanovsky) [inline fw/tls.c:818]: Please write a comment above the `ss_send()` that the actual message transmission may happen on another CPU, so after `ss_send()` `msg` can not be user. Otherwise we can step the same issue in future. Also `tfw_connection_send()` must be commented that it's unsafe to reference `msg` after the call and reference `tfw_tls_conn_send()`.

File: fw/tls.c (hunk 1 above)
Comment (krizhanovsky) [inline fw/tls.c:800]: Don't we need `READ_ONCE()` here to make sure that the compiler won't optimize out the temporal variable?

Comment (krizhanovsky) [reply fw/tls.c:800]: @EvgeniiMekhanik in my understanding the `msg` is deleted by a callback form the TCP transmission, which may happen on another CPU thanks to scheduling logic in `ss_send()`. Doesn't https://github.com/tempesta-tech/tempesta/issues/2169#issuecomment-2247592874 answer your question?

**Review by krizhanovsky — APPROVED** [review]
Looks good for me, but a comment and seems a barrier are required.

**Review by EvgeniiMekhanik — APPROVED** [review]

**Comment by EvgeniiMekhanik** [comment]
I understand the problem. msg can be freed in skb->destructor during ss_do_send both in success or fail. LGTM. Please add comment about it in code and in commit message

File: fw/tls.c (hunk 1 above)
Comment (EvgeniiMekhanik) [reply fw/tls.c:800]: We no't need READ_ONCE, because as i can see the problem is that message destroyed in ss_do_send callback which is called after ss_send on other cpu

File: fw/connection.c [hunk 3]
```diff
@@ -139,6 +139,10 @@ tfw_connection_release(TfwConn *conn)
  * ensure that conn->sk remains valid for the life of @conn instance.
  * The socket itself may have been closed, but not deleted. ss_send()
  * makes sure that data is sent only on an active socket.
+ *
+ * NOTE: after `tfw_connection_send` returns, `msg` should not be used!
+ * See `tfw_tls_conn_send` for reference.
+ *
```
Comment (krizhanovsky) [inline fw/connection.c:145]: I'm not sure if this is the best place to comment this - a code observer interested in `tfw_connection_send()` may not see the header comment

Comment (kingluo) [reply fw/connection.c]: moved to the function body.
