### PR TITLE
Fix race with using parser fields.

### LINKED ISSUE #1965: Kernel BUG in ss_skb_cutoff_data in t_sites.test_wordpress.TestWordpressSiteH2.test_blog_post_not_cached_for_autheticated_user
[tempesta fw] Configuration processing is completed.
[  121.929058] [tdb] Opened table /opt/tempesta/db/filter0.tdb: size=16777216 rec_size=20 base=00000000779eff93
[  122.014601] [tdb] Opened table /opt/tempesta/db/cache0.tdb: size=268435456 rec_size=0 base=00000000052d4f48
[  122.020475] [tdb] Opened table /opt/tempesta/db/sessions0.tdb: size=16777216 rec_size=312 base=00000000b052a88d
[  122.026116] [tdb] Opened table /opt/tempesta/db/client0.tdb: size=16777216 rec_size=624 base=00000000c9458d98
[  122.139551] [tempesta fw] Open listen socket on: 0.0.0.0:443
[  122.203546] [tempesta fw] Tempesta FW is ready
[  127.495137] [tempesta fw] ERROR: Cache: cannot copy HTTP body
[  127.495578] ------------[ cut here ]------------
[  127.495881] kernel BUG at /home/evgeny/workdir/tempesta/fw/ss_skb.c:1048!
[  127.496327] invalid opcode: 0000 [#1] SMP NOPTI
[  127.496624] CPU: 0 PID: 14256 Comm: docker-proxy Tainted: G           OE     5.10.35+ #309
[  127.497160] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014
[  127.497809] RIP: 0010:ss_skb_cutoff_data+0x2eb/0x3e0 [tempesta_fw]
[  127.498215] Code: c0 85 c0 75 54 48 8b 45 d0 65 48 2b 04 25 28 00 00 00 0f 85 f6 00 00 00 48 83 c4 70 44 89 c0 5b 41 5c 41 5d 41 5e 41 5f 5d c3 <0f> 0b 48 c7 c7 50 20 ef c2 e8 e4 0b a9 c0 41 89 c0 eb c8 0f 0b 48
[  127.499455] RSP: 0018:ffffb4c540003668 EFLAGS: 00010246
[  127.499800] RAX: 0000000000000000 RBX: ffff89fe5a2d11a8 RCX: 0000000000000002
[  127.500298] RDX: 0000000000000000 RSI: ffff89fe5a2d11a8 RDI: ffff89fe5bc34b80
[  127.500765] RBP: ffffb4c540003700 R08: 0000000000000001 R09: 0000000000000000
[  127.501239] R10: ffff89fe57dbd010 R11: 0000000000000000 R12: 000000000001882c
[  127.501705] R13: 0000000000000000 R14: ffff89fe57dbd020 R15: 000000000000002b
[  127.502173] FS:  00007fb4c97fa640(0000) GS:ffff89ff37c00000(0000) knlGS:0000000000000000
[  127.502716] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  127.503105] CR2: 00007f95ab3ee048 CR3: 000000017df5e000 CR4: 0000000000750ef0
[  127.503669] PKRU: 55555554
[  127.503852] Call Trace:
[  127.504017]  <IRQ>
[  127.504165]  tfw_http_msg_cutoff_body_chunks+0x33/0x80 [tempesta_fw]
[  127.504586]  tfw_h2_resp_adjust_fwd+0x73a/0x770 [tempesta_fw]
[  127.504967]  tfw_http_resp_cache_cb+0x33/0x2f0 [tempesta_fw]
[  127.505341]  tfw_cache_do_action+0x584/0x1250 [tempesta_fw]
[  127.505710]  ? tfw_h2_resp_adjust_fwd+0x770/0x770 [tempesta_fw]
[  127.506102]  ? frang_resp_handler+0xcc/0x410 [tempesta_fw]
[  127.506465]  ? frang_resp_handler+0xcc/0x410 [tempesta_fw]
[  127.506827]  ? tfw_hash_str_len+0xbc/0x170 [tempesta_fw]
[  127.507179]  ? tfw_h2_resp_adjust_fwd+0x770/0x770 [tempesta_fw]
[  127.507573]  tfw_cache_process+0xc9/0x360 [tempesta_fw]
[  127.507919]  ? tfw_cache_process+0xc9/0x360 [tempesta_fw]
[  127.508270]  tfw_http_resp_cache+0xfa/0x1b0 [tempesta_fw]
[  127.508617]  tfw_http_msg_process_generic+0x3f5/0x740 [tempesta_fw]
[  127.509021]  ? __coalesce_frag+0x99/0x150 [tempesta_fw]
[  127.509454]  tfw_http_msg_process+0x3e/0x60 [tempesta_fw]
[  127.509804]  tfw_connection_recv+0x87/0x110 [tempesta_fw]
[  127.510176]  ? ss_skb_unroll+0xce/0x280 [tempesta_fw]

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
There were some fields in parser structure, which
can be used later in cache thread. But parser struture is one for the whole connection, so it can be race in this case. Move this fields to TfwHttpMsg struture to prevent this race.

Closes #1965

### CODE REVIEW

File: fw/http.h [hunk 1]
```diff
@@ -371,6 +371,13 @@ typedef struct {
  * @destructor		- called when a connection is destroyed;
  * @crlf		- pointer to CRLF between headers and body;
  * @body		- pointer to the body of a message;
+ * @body_start_data	- beginning of body used during HTTP1 to HTTP2 body
+ *			  transformation. Must be deprecated when new cutting
+ *			  strategy will be implemented;
```
Comment (krizhanovsky) [inline fw/http.h:376]: Could you please reference an issue number in the comment?

File: fw/http.h [hunk 2]
```diff
@@ -371,6 +371,13 @@ typedef struct {
...
+ * @body_start_skb	- skb with start of the body;
+ * @cut 		- descriptors of http chunked body to be cutted during
```
Comment (krizhanovsky) [inline fw/http.h:378]:
```suggestion
 * @cut 		- descriptors of http chunked body to be cut during
```
irregular verb

File: fw/http.h [hunk 3]
```diff
@@ -394,7 +401,11 @@ typedef struct {
 	TfwConn		*conn;						\
 	void (*destructor)(void *msg);					\
 	TfwStr		crlf;						\
-	TfwStr		body;
+	TfwStr		body;						\
+	char		*body_start_data;				\
+	struct sk_buff	*body_start_skb;				\
+	TfwStr		cut;
```
Comment (krizhanovsky) [inline fw/http.h:407]: According to the patch the fields are used for responses only, so we can also make memory footprint bit smaller by placing them into `TfwHttpResp` and do not spend extra memory for requests

**Review by krizhanovsky — APPROVED** [review]
The change looks good for me in general, just a couple of improvement and cleanup.

However, I didn't get which race happens in #1965? Did you experience that while one response is written to the cache in one softirqd, the other softirq (on other CPU, but the same TCP connection!) parses another (apparently, pipelined) response? That'd be helpful if you could describe the race condition in the commit message.

File: fw/http.h (hunk 2 above)
Comment (EvgeniiMekhanik) [reply fw/http.h:378]: Fixed

File: fw/http.h (hunk 3 above)
Comment (EvgeniiMekhanik) [reply fw/http.h:407]: Fixed
