### PR TITLE
Fix race in `tfw_connection_abort`

### LINKED ISSUE #2345: Hardly reproduced BUG from 2328 issue
[ 215.051812] net_ratelimit: 2463 callbacks suppressed
[ 215.051814] [tempesta fw] Warning: pending active connections for 5s (connections count 0x1, queues count 0)
[ 215.054939] [tempesta fw] Warning: cpu 0(2), backlog size 0, active connections mask 0x1500000000, cntwork queue size 0, close backlog is empty
[ 215.056163] [tempesta fw] Warning: cpu 1(2), backlog size 0, active connections mask 0xfffffff600000000, cntwork queue size 0, close backlog is empty
[ 215.057512] [tempesta fw] Warning: cpu 2(2), backlog size 0, active connections mask 0xffffffef00000000, cntwork queue size 0, close backlog is empty
[ 215.058976] [tempesta fw] Warning: cpu 3(2), backlog size 0, active connections mask 0x700000000, cntwork queue size 0, close backlog is empty
[ 215.123845] ==================================================================
[ 215.124585] BUG: KASAN: use-after-free in tfw_sched_ratio_del_grp+0x89/0x100 [tempesta_fw]
[ 215.125658] Read of size 8 at addr ffff888139a4fe58 by task sysctl/5632
[ 215.126529]
[ 215.126745] CPU: 2 PID: 5632 Comm: sysctl Tainted: G W OE 5.10.35+ https://github.com/tempesta-tech/tempesta/pull/466
[ 215.127744] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.16.2-debian-1.16.2-1 04/01/2014
[ 215.128904] Call Trace:
[ 215.129141] dump_stack+0x96/0xc4
[ 215.129452] print_address_description.constprop.0+0x21/0x220
[ 215.129979] ? _raw_spin_lock_irqsave+0x8e/0xf0
[ 215.130395] ? _raw_write_unlock_bh+0x30/0x30
[ 215.130799] ? usleep_range+0xe0/0xe0
[ 215.131158] ? tfw_sched_ratio_del_grp+0x89/0x100 [tempesta_fw]
[ 215.131691] kasan_report.cold+0x31/0x48
[ 215.132046] ? down_write+0x60/0x110
[ 215.132396] ? tfw_sched_ratio_del_grp+0x89/0x100 [tempesta_fw]
[ 215.132932] __asan_load8+0x69/0x90
[ 215.133277] tfw_sched_ratio_del_grp+0x89/0x100 [tempesta_fw]
[ 215.133823] ? tfw_sock_srv_grace_shutdown_cb+0x140/0x140 [tempesta_fw]
[ 215.134446] tfw_sg_release_all+0x8b/0x1e0 [tempesta_fw]
[ 215.134955] ? tfw_sock_srv_grace_shutdown_cb+0x140/0x140 [tempesta_fw]
[ 215.135578] tfw_sock_srv_stop+0x1d9/0x220 [tempesta_fw]
[ 215.136089] ? tfw_sock_srv_grace_shutdown_cb+0x140/0x140 [tempesta_fw]
[ 215.136722] tfw_mods_stop+0x51/0xe0 [tempesta_fw]
[ 215.137180] tfw_ctlfn_state_io+0x295/0x540 [tempesta_fw]
[ 215.137687] ? tfw_cleanup+0x30/0x30 [tempesta_fw]
[ 215.138141] ? tfw_cleanup+0x30/0x30 [tempesta_fw]
[ 215.138572] ? __cgroup_bpf_run_filter_sysctl+0x274/0x430
[ 215.139062] ? __kasan_kmalloc.constprop.0+0xcf/0xe0
[ 215.139511] ? __kasan_check_read+0x11/0x20
[ 215.139892] proc_sys_call_handler+0x227/0x390
[ 215.140294] ? sysctl_head_grab+0x60/0x60
[ 215.140667] ? __mod_memcg_state.part.0+0x4e/0x140
[ 215.141096] proc_sys_write+0x13/0x20
[ 215.141425] new_sync_write+0x29d/0x3c0
[ 215.141769] ? new_sync_read+0x3c0/0x3c0
[ 215.142120] ? lru_cache_add_inactive_or_unevictable+0x38/0x100
[ 215.142648] ? handle_mm_fault+0xa62/0x2640
[ 215.143026] ? rw_verify_area+0x7c/0x150
[ 215.143379] vfs_write+0x311/0x3d0
[ 215.143688] ksys_write+0xcd/0x170
[ 215.143995] ? __ia32_sys_read+0x50/0x50
[ 215.144347] ? __kasan_check_read+0x11/0x20
[ 215.144736] ? fpregs_assert_state_consistent+0x5a/0x70
[ 215.145213] __x64_sys_write+0x42/0x50
[ 215.145560] do_syscall_64+0x38/0x90
[ 215.145892] entry_SYSCALL_64_after_hwframe+0x44/0xa9
[ 215.146354] RIP: 0033:0x7f7cd5d59887
[ 215.146688] Code: 10 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b7 0f 1f 00 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 51 c3 48 83 ec 28 48 89 54 24 18 48 89 74 24
[ 215.148366] RSP: 002b:00007ffe90ca0548 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[ 215.149056] RAX: ffffffffffffffda RBX: 0000564f0ef07560 RCX: 00007f7cd5d59887
[ 215.149699] RDX: 0000000000000005 RSI: 0000564f0ef075a0 RDI: 0000000000000004
[ 215.150342] RBP: 0000564f0ef096d0 R08: 0000000000000010 R09: 0000564f0ef096d0
[ 215.150984] R10: 0000000000000077 R11: 0000000000000246 R12: 0000000000000005
[ 215.151627] R13: 0000000000000005 R14: 00007f7cd5e5bb80 R15: 00007f7cd5e5ba00
[ 215.152270]
[ 215.152416] Allocated by task 5548:
[ 215.152744] kasan_save_stack+0x23/0x50
[ 215.153098] __kasan_kmalloc.constprop.0+0xcf/0xe0
[ 215.153535] kasan_slab_alloc+0xe/0x10
[ 215.153877] kmem_cache_alloc+0xf7/0x290
[ 215.154259] tfw_server_create+0x22/0xd0 [tempesta_fw]
[ 215.154749] tfw_cfgop_server+0x259/0x5b0 [tempesta_fw]
[ 215.155248] tfw_cfgop_out_server+0x5a/0xe0 [tempesta_fw]
[ 215.155762] spec_handle_entry+0xaa/0xe0 [tempesta_fw]
[ 215.156252] tfw_cfg_parse_mods+0x283/0x310 [tempesta_fw]
[ 215.156771] tfw_cfg_parse+0x89/0xd0 [tempesta_fw]
[ 215.157230] tfw_ctlfn_state_io+0x3b1/0x540 [tempesta_fw]
[ 215.157720] proc_sys_call_handler+0x227/0x390
[ 215.158126] proc_sys_write+0x13/0x20
[ 215.158463] new_sync_write+0x29d/0x3c0
[ 215.158815] vfs_write+0x311/0x3d0
[ 215.159128] ksys_write+0xcd/0x170
[ 215.159441] __x64_sys_write+0x42/0x50
[ 215.159785] do_syscall_64+0x38/0x90
[ 215.160115] entry_SYSCALL_64_after_hwframe+0x44/0xa9
[ 215.160578]
[ 215.160723] Freed by task 5675:
[ 215.161012] kasan_save_stack+0x23/0x50
[ 215.161363] kasan_set_track+0x20/0x30
[ 215.161707] kasan_set_free_info+0x1f/0x40
[ 215.162083] __kasan_slab_free+0x116/0x160
[ 215.162458] kasan_slab_free+0xe/0x10
[ 215.162796] slab_free_freelist_hook+0x47/0x140
[ 215.163209] kmem_cache_free+0x105/0x410
[ 215.163592] tfw_server_destroy+0xa4/0xc0 [tempesta_fw]
[ 215.164090] tfw_srv_conn_release+0xd0/0xe0 [tempesta_fw]
[ 215.164614] tfw_sock_srv_connect_drop+0x2e0/0x2f0 [tempesta_fw]
[ 215.165181] ss_conn_drop_guard_exit+0x6a/0xa0 [tempesta_fw]
[ 215.165696] tcp_done+0x14d/0x1e0
[ 215.166004] tcp_reset+0x6c/0x110
[ 215.166306] tcp_validate_incoming+0x707/0xa30
[ 215.166708] tcp_rcv_state_process+0x51b/0x1f50
[ 215.167121] tcp_v4_do_rcv+0x164/0x360
[ 215.167464] tcp_v4_rcv+0x1600/0x1770
[ 215.167805] ip_protocol_deliver_rcu+0x46/0x2e0
[ 215.168218] ip_local_deliver_finish+0xc6/0xe0
[ 215.168628] ip_local_deliver+0x1f5/0x210
[ 215.168996] ip_rcv_finish+0xcf/0xf0
[ 215.169325] ip_rcv+0x16d/0x180
[ 215.169617] __netif_receive_skb_core.constprop.0+0x964/0x18d0
[ 215.170145] __netif_receive_skb_one_core+0xa8/0x140
[ 215.170597] __netif_receive_skb+0x26/0xb0
[ 215.170971] process_backlog+0xfe/0x290
[ 215.171323] net_rx_action+0x287/0x6b0
[ 215.171667] __do_softirq+0xfe/0x383
[ 215.171996]
[ 215.172142] The buggy address belongs to the object at ffff888139a4fde8
[ 215.172142] which belongs to the cache tfw_srv_cache of size 176
[ 215.173287] The buggy address is located 112 bytes inside of
[ 215.173287] 176-byte region [ffff888139a4fde8, ffff888139a4fe98)
[ 215.174354] The buggy address belongs to the page:
[ 215.174802] page:00000000b3b7984c refcount:1 mapcount:0 mapping:0000000000000000 index:0xffff888139a4fbd8 pfn:0x139a4c
[ 215.175789] head:00000000b3b7984c order:2 compound_mapcount:0 compound_pincount:0
[ 215.176483] flags: 0x17ffffc0010200(slab|head)
[ 215.176906] raw: 0017ffffc0010200 ffff88815b977c50 ffff88815b977c50 ffff88810d3bcf40
[ 215.177626] raw: ffff888139a4fbd8 00000000001f0001 00000001ffffffff 0000000000000000
[ 215.178343] page dumped because: kasan: bad access detected
[ 215.178864]
[ 215.179013] Memory state around the buggy address:
[ 215.179464] ffff888139a4fd00: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[ 215.180136] ffff888139a4fd80: fc fc fc fc fc fc fc fc fc fc fc fc fc fa fb fb
[ 215.180811] >ffff888139a4fe00: fb fb fb fb fb fb fb fb fb fb fb fb fb fb fb fb
[ 215.181481] ^
[ 215.182048] ffff888139a4fe80: fb fb fb fc fc fc fc fc fc fc fc fc fc fc fc fc
[ 215.182719] ffff888139a4ff00: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[ 215.183389] ==================================================================
[ 215.184060] Disabling lock debugging due to kernel taint
[ 215.184643] ------------[ cut here ]------------
[ 215.185079] kernel BUG at /home/evgeny/workdir/tempesta/fw/server.h:223!
[ 215.185708] invalid opcode: 0000 [https://github.com/tempesta-tech/tempesta/issues/1] SMP DEBUG_PAGEALLOC KASAN NOPTI
[ 215.186424] CPU: 2 PID: 5632 Comm: sysctl Tainted: G B W OE 5.10.35+ https://github.com/tempesta-tech/tempesta/pull/466
[ 215.187104] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.16.2-debian-1.16.2-1 04/01/2014
[ 215.187955] RIP: 0010:__tfw_sg_del_srv+0x131/0x140 [tempesta_fw]
[ 215.188491] Code: 8d 7b 40 4d 89 74 24 30 4d 89 74 24 38 e8 47 4b 97 cc 48 83 6b 40 01 48 c7 c7 40 e7 d9 c1 e8 e6 04 68 cc e9 5b ff ff ff 0f 0b <0f> 0b 4c 89 e7 e8 d5 ee ff ff e9 7a ff ff ff 0f 1f 44 00 00 55 48
[ 215.190152] RSP: 0000:ffff8881453c78f0 EFLAGS: 00010297
[ 215.190619] RAX: ffffffffffffffff RBX: ffff888183db0800 RCX: ffffffffc1d20761
[ 215.191247] RDX: 0000000000000001 RSI: 0000000000000008 RDI: ffff888139a4fe78
[ 215.191876] RBP: ffff8881453c7918 R08: 0000000000000001 R09: 0000000000000007
[ 215.192515] R10: ffffed1027349fcf R11: 0000000000000001 R12: ffff888139a4fde8
[ 215.193144] R13: ffff888183db0820 R14: ffff888139a4fe18 R15: ffff888183db0820
[ 215.193752] FS: 00007f7cd5c42740(0000) GS:ffff88824d100000(0000) knlGS:0000000000000000
[ 215.194435] CS: 0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 215.194924] CR2: 00007efc53f16030 CR3: 000000017845c000 CR4: 0000000000750ee0
[ 215.195528] PKRU: 55555554
[ 215.195767] Call Trace:
[ 215.196012] tfw_sg_release_all+0xd3/0x1e0 [tempesta_fw]
[ 215.196493] ? tfw_sock_srv_grace_shutdown_cb+0x140/0x140 [tempesta_fw]
[ 215.197222] tfw_sock_srv_stop+0x1d9/0x220 [tempesta_fw]
[ 215.198039] ? tfw_sock_srv_grace_shutdown_cb+0x140/0x140 [tempesta_fw]
[ 215.198794] tfw_mods_stop+0x51/0xe0 [tempesta_fw]
[ 215.199250] tfw_ctlfn_state_io+0x295/0x540 [tempesta_fw]
[ 215.199780] ? tfw_cleanup+0x30/0x30 [tempesta_fw]
[ 215.200232] ? tfw_cleanup+0x30/0x30 [tempesta_fw]
[ 215.200693] ? __cgroup_bpf_run_filter_sysctl+0x274/0x430
[ 215.201155] ? __kasan_kmalloc.constprop.0+0xcf/0xe0
[ 215.201766] ? __kasan_check_read+0x11/0x20
[ 215.202126] proc_sys_call_handler+0x227/0x390
[ 215.202573] ? sysctl_head_grab+0x60/0x60
[ 215.203037] ? __mod_memcg_state.part.0+0x4e/0x140
[ 215.203447] proc_sys_write+0x13/0x20
[ 215.203927] new_sync_write+0x29d/0x3c0
[ 215.204316] ? new_sync_read+0x3c0/0x3c0
[ 215.204662] ? lru_cache_add_inactive_or_unevictable+0x38/0x100
[ 215.205260] ? handle_mm_fault+0xa62/0x2640
[ 215.205687] ? rw_verify_area+0x7c/0x150
[ 215.206189] vfs_write+0x311/0x3d0
[ 215.206491] ksys_write+0xcd/0x170
[ 215.206883] ? __ia32_sys_read+0x50/0x50
[ 215.207304] ? __kasan_check_read+0x11/0x20
[ 215.207755] ? fpregs_assert_state_consistent+0x5a/0x70
[ 215.208390] __x64_sys_write+0x42/0x50
[ 215.208815] do_syscall_64+0x38/0x90
[ 215.209127] entry_SYSCALL_64_after_hwframe+0x44/0xa9
[ 215.209560] RIP: 0033:0x7f7cd5d59887
[ 215.209925] Code: 10 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b7 0f 1f 00 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 51 c3 48 83 ec 28 48 89 54 24 18 48 89 74 24
[ 215.211578] RSP: 002b:00007ffe90ca0548 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[ 215.212264] RAX: ffffffffffffffda RBX: 0000564f0ef07560 RCX: 00007f7cd5d59887
[ 215.212920] RDX: 0000000000000005 RSI: 0000564f0ef075a0 RDI: 0000000000000004
[ 215.213591] RBP: 0000564f0ef096d0 R08: 0000000000000010 R09: 0000564f0ef096d0
[ 215.214240] R10: 0000000000000077 R11: 0000000000000246 R12: 0000000000000005
[ 215.214866] R13: 0000000000000005 R14: 00007f7cd5e5bb80 R15: 00007f7cd5e5ba00
[ 215.215494] Modules linked in: tempesta_fw(OE) tempesta_db(OE) sha256_ssse3 sha512_ssse3 tempesta_tls(OE) tempesta_lib(OE) nvme_tcp nvme_fabrics nvme_core vhost_vsock vmw_vsock_virtio_transport_common vhost vhost_iotlb vsock xt_conntrack xt_MASQUERADE nf_conntrack_netlink xfrm_user xfrm_algo xt_addrtype nft_compat br_netfilter nft_masq nft_counter nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 bridge stp llc nf_tables nfnetlink snd_hda_codec_generic ledtrig_audio overlay snd_hda_intel snd_intel_dspcfg snd_hda_codec snd_hda_core kvm_intel snd_hwdep kvm snd_pcm crct10dif_pclmul snd_seq_midi snd_seq_midi_event ghash_clmulni_intel snd_rawmidi binfmt_misc qxl aesni_intel joydev drm_ttm_helper crypto_simd 9pnet_virtio cryptd nls_iso8859_1 glue_helper ttm input_leds snd_seq snd_seq_device serio_raw snd_timer drm_kms_helper 9pnet snd soundcore cec fb_sys_fops syscopyarea sysfillrect sysimgblt mac_hid qemu_fw_cfg sch_fq_codel msr ramoops reed_solomon drm parport_pc ppdev lp parport
[ 215.215599] efi_pstore virtio_rng ip_tables x_tables autofs4 btrfs blake2b_generic xor zstd_compress raid6_pq libcrc32c psmouse ahci crc32_pclmul i2c_i801 i2c_smbus libahci lpc_ich virtio_net virtio_blk net_failover failover hid_generic usbhid hid
[ 215.225107] ---[ end trace ac645c107f7b64bd ]---
[ 215.225525] RIP: 0010:__tfw_sg_del_srv+0x131/0x140 [tempesta_fw]
[ 215.226038] Code: 8d 7b 40 4d 89 74 24 30 4d 89 74 24 38 e8 47 4b 97 cc 48 83 6b 40 01 48 c7 c7 40 e7 d9 c1 e8 e6 04 68 cc e9 5b ff ff ff 0f 0b <0f> 0b 4c 89 e7 e8 d5 ee ff ff e9 7a ff ff ff 0f 1f 44 00 00 55 48
[ 215.227601] RSP: 0000:ffff8881453c78f0 EFLAGS: 00010297
[ 215.228057] RAX: ffffffffffffffff RBX: ffff888183db0800 RCX: ffffffffc1d20761
[ 215.228670] RDX: 0000000000000001 RSI: 0000000000000008 RDI: ffff888139a4fe78
[ 215.229272] RBP: ffff8881453c7918 R08: 0000000000000001 R09: 0000000000000007
[ 215.229876] R10: ffffed1027349fcf R11: 0000000000000001 R12: ffff888139a4fde8
[ 215.230482] R13: ffff888183db0820 R14: ffff888139a4fe18 R15: ffff888183db0820
[ 215.231085] FS: 00007f7cd5c42740(0000) GS:ffff88824d100000(0000) knlGS:0000000000000000
[ 215.231782] CS: 0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 215.232272] CR2: 00007efc53f16030 CR3: 000000017845c000 CR4: 0000000000750ee0
[ 215.232882] PKRU: 55555554

[ 215.233120] Kernel panic - not syncing: Fatal exception
[ 215.233864] Kernel Offset: 0xd200000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[ 215.234762] Rebooting in 1 seconds..
[ 216.227238] ACPI MEMORY or I/O RESET_REG.

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
Previously we use `tfw_connection_get` in `tfw_connection_abort` to prevent (when `tfw_connection_abort` is called
from process context) connection destruction in running in parallel softirq. But there is one more race when we abort hung server connection - if backend sends TCP RST at the time when we call `tfw_connection_abort` (from process context), connection reference counter will be decremented on other cpu and connection will be released. In this case we call `tfw_connection_get` for connection with reference counter which is equal to zero and release connection second time, that can lead to several bugs. So call `__tfw_connection_get_if_not_death` to prevent aborting already released server connection. For client connection we have no such problems, because we call `tfw_connection_unlink_from_peer` when client connection released, this function lock peer `conn_lock`, which already locked during aborting hung connections, so client connection will never destroyed on other cpu.

Closed #2345

### CODE REVIEW

File: fw/connection.c [hunk 1]
```diff
@@ -88,16 +91,26 @@ tfw_connection_close(TfwConn *conn, bool sync)
...
-	r = TFW_CONN_HOOK_CALL(conn, conn_abort);
-	WARN_ON(r);
-	tfw_connection_put(conn);
+	if (__tfw_connection_get_if_not_death(conn)) {
+		int r;
+
+		r = TFW_CONN_HOOK_CALL(conn, conn_abort);
+		WARN_ON(r);
+		tfw_connection_put(conn);
+	}
```
Comment (const-t) [inline fw/connection.c:113]: It looks good. There is option to have another one `tfw_connection_abort()` for clients to not to do `__tfw_connection_get_if_not_death` because it called under lock. However I'm not sure, because it complicates already complex code.

**Review by const-t — APPROVED** [review]

File: fw/connection.c (hunk 1 above)
Comment (krizhanovsky) [reply fw/connection.c:113]: I think it's fine: under lock we don't have contention on the atomic in `__tfw_connection_get_if_not_death()` and not loop spinning

**Review by krizhanovsky — APPROVED** [review]
LGTM
