### PR TITLE
fix(1902): correct trailer headers placement

### LINKED ISSUE #1902: Correct handling on trailer headers in h1 -> h2 proxying
# Scope
For response:
```python3
HTTP/1.1 200 OK
Content-type: text/html
Last-Modified: Wed, 14 Jun 2023 10:18:29 GMT
Date: Wed, 14 Jun 2023 10:18:29 GMT
Server: Deproxy Server
Transfer-Encoding: chunked
Trailer: X-Token

10
abcdefghijklmnop
10
qrstuvwxyzABCDEF
10
GHIJKLMNOPQRSTUV
4
WXYZ
0
X-Token: value
```
Tempesta forwarded h2 response:

```python3
:status: 200
content-type: text/html
last-modified: Wed, 14 Jun 2023 10:19:11 GMT
date: Wed, 14 Jun 2023 10:19:11 GMT
trailer: X-Token
x-token: value
via: 2.0 tempesta_fw (Tempesta FW pre-0.7.0)
content-length: 52
server: Tempesta FW/pre-0.7.0

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ

```

and garbage as separate TCP frame:
```python3
b'Token: value\r\n\r\n'
```

# Testing

encoding.test_encoding.TestH2ChunkedWithTrailer

### PR DESCRIPTION
**Pull request by kingluo**
close #1902

### CODE REVIEW

File: fw/http_frame.c [hunk 1]
```diff
@@ -1967,23 +1973,30 @@ tfw_h2_insert_frame_header(struct sock *sk, TfwH2Ctx *ctx, TfwStream *stream,
 	length = tfw_h2_calc_frame_length(ctx, stream, type, len,
 					  max_len - FRAME_HEADER_SIZE);
 	if (type == HTTP2_DATA) {
-		ctx->rem_wnd -= length;
-		stream->rem_wnd -= length;
+		if (!stream->xmit.t_len) {
```
Comment (EvgeniiMekhanik) [inline fw/http_frame.c:1976]: This is mistake, we should adjust window in case when response contains trailers.
I implement new test for this case.
https://github.com/tempesta-tech/tempesta-test/pull/651
It passes on master but fails on your branch

File: fw/http2.c [hunk 2]
```diff
@@ -489,6 +489,38 @@ tfw_h2_stream_xmit_prepare_resp(TfwStream *stream)
...
+		// and append them to the resp->msg.skb_head.
+		struct sk_buff *skb_head, *skb, *nskb_head, *nskb;
+		unsigned long acc;
+
+		skb_head = resp->msg.skb_head;
+		skb = resp->mit.iter.skb;
+		resp->msg.skb_head = resp->mit.iter.skb = NULL;
+		acc = resp->mit.acc_len;
+
+		r = tfw_h2_hpack_encode_trailer_headers(resp);
```
Comment (EvgeniiMekhanik) [inline fw/http2.c:505]: I don't agree with this solution. We should rework our standard functions to add trailers. Here we have extra loop over skbs and it looks bad for me. @krizhanovsky @const-t please look he and write your opinion.

File: fw/cache.c [hunk 3]
```diff
@@ -2838,14 +2861,48 @@ tfw_cache_build_resp(TfwHttpReq *req, TfwCacheEntry *ce, long lifetime)
...
+		TfwHttpTransIter pmit, nmit;
+		struct sk_buff *pskb_head = resp->msg.skb_head;
+
+		has_trailers = true;
+		pmit = nmit = resp->mit;
+		nmit.start_off = 0;
+		nmit.iter.skb = nmit.iter.skb_head = NULL;
+		nmit.iter.frag = -1;
+
+		resp->msg.skb_head = NULL;
```
Comment (EvgeniiMekhanik) [inline fw/cache.c:2884]: I don't agree with this solution. We should rework our standard functions to add trailers. Here we have extra loop over skbs and it looks bad for me. @krizhanovsky @const-t please look he and write your opinion.

File: fw/http_frame.c [hunk 4]
```diff
@@ -1967,23 +1973,30 @@ tfw_h2_insert_frame_header(struct sock *sk, TfwH2Ctx *ctx, TfwStream *stream,
...
+			ctx->rem_wnd -= length;
+			stream->rem_wnd -= length;
+		}
 		stream->xmit.b_len -= length;
-	} else {
+	} else if (stream->xmit.h_len) {
 		stream->xmit.h_len -= length;
+	} else if (stream->xmit.t_len) {
+		ctx->rem_wnd -= length;
```
Comment (EvgeniiMekhanik) [inline fw/http_frame.c:1984]: Why we decrement window here? trailers are the headers frames.

File: fw/http_frame.c (hunk 1 above)
Comment (kingluo) [reply fw/http_frame.c:1976]: I thought we could adjust the wnd stuff until trailers handling, but yes, you're right, maybe just revert them.

File: fw/http_frame.c (hunk 4 above)
Comment (kingluo) [reply fw/http_frame.c:1984]: ditto.

File: fw/http2.c [hunk 5]
```diff
@@ -489,6 +489,38 @@ tfw_h2_stream_xmit_prepare_resp(TfwStream *stream)
 	if (test_bit(TFW_HTTP_B_CHUNKED, resp->flags))
 		r = tfw_http_msg_cutoff_body_chunks(resp);
```
Comment (EvgeniiMekhanik) [inline fw/http2.c:490]: we should check r here, and do not process trailers in case of error.

File: fw/http2.c (hunk 2 above)
Comment (EvgeniiMekhanik) [reply fw/http2.c:505]: I don't see any problem here. I  implement such part of code
```
if (resp->trailers_len > 0) {
		{
			TfwHttpTransIter *mit = &resp->mit;
			TfwMsgIter *it = &mit->iter;
			
			it->frag = 4; // Setup it->frag or Iter->skb and frag which points to the end of the body. I set here 4, to check that test works fine.
 		}

		{
			unsigned long acc = resp->mit.acc_len;
			r = tfw_h2_hpack_encode_trailer_headers(resp);
			if (unlikely(r))
				goto finish;
			stream->xmit.t_len = resp->mit.acc_len - acc;
		}
```
And all works fine. So we don't need all previous code. We have two solutions:
1. Bad solution, not better performance that current solution, but less code. Use `tfw_http_iter_set_at
` or `tfw_msg_iter_move` to set at the end of the body.
2. Save pointer to the body and use it, may found body end during `tfw_http_msg_cutoff_body_chunks`

File: fw/hpack.c [hunk 6]
```diff
@@ -3488,6 +3488,59 @@ tfw_hpack_hdr_expand(TfwHttpResp *__restrict resp, TfwStr *__restrict hdr,
...
 		return -EINVAL;
 
+	// compact str with sparse chunks in place
+	// e.g. changes
+	// "f" "o" ":" " " "b" "a"
+	// into
+	// "fo" ": " "ba"
+	// it's different from `tfw_http_hdr_split()`, which only splits
+	// name chunks and value chunks into two strs, no compact.
+	if (hdr->flags & TFW_STR_TRAILER) {
```
Comment (EvgeniiMekhanik) [inline fw/hpack.c:3498]: Why we should do it? Is this transformation necessary according RFC? If yes please add comment. And we don't need this part of code. I think that we can do it during parsing trailer headers in http_parser.c. @const-t how do you think?

Comment (kingluo) [reply fw/hpack.c:3498]: This conversion only makes sense for our implementation to satisfy the needs of the header encoding below.

File: fw/http_frame.c [hunk 7]
```diff
@@ -2116,6 +2149,13 @@ do {									\
 						       &stream->xmit.postponed);
```
Comment (EvgeniiMekhanik) [inline fw/http_frame.c:2149]: As I think trailers works same as headers frames. So we can't send postponed skbs if we start but not finished sending trailer frames. We also need test this rarely case. We should implement test with a very long trailer. And simulate a situation when client sends us new settings (for example) after receiving first trailer frame but before receiving all trailers.

Comment (kingluo) [reply fw/http_frame.c:2149]: The role of trailers is equivalent to the body. In fact, the only application of HTTP/2 trailers so far is GRPC, which uses the trailers to represent the call result, and the trailers are expected to follow the body from the perspective of GRPC client.

File: fw/http_frame.c [hunk 8]
```diff
@@ -2095,7 +2104,31 @@ do {									\
...
+					       snd_wnd, stream->xmit.t_len);
+		if (unlikely(r)) {
+			T_WARN("Failed to make trail headers frame %d", r);
+			return r;
+		}
+
+		T_FSM_JMP(HTTP2_SEND_FRAMES);
+	}
+
+	T_FSM_STATE(HTTP2_MAKE_TRAILER_CONTINUATION_FRAMES) {
```
Comment (EvgeniiMekhanik) [inline fw/http_frame.c:2122]: I add test for long trailers https://github.com/tempesta-tech/tempesta-test/pull/651/commits/ec625cefffced6fd6e0334d5cebf08c545e59ba3 and it doesn't pass

File: fw/http_frame.c (hunk 7 above)
Comment (EvgeniiMekhanik) [reply fw/http_frame.c:2149]: I mean that if we have long trailer about 30000 bytes for example we can't send it without continuation frame. If we send some other frame after we send first trailer (in fact headers) frame but before we send continuation trailer (continuation headers) frame we catch connection error of type protocol error. For this purpose we have postponed skbs.

File: fw/http2.c (hunk 2 above)
Comment (kingluo) [reply fw/http2.c:501]: If we really need to eliminate the "ugly" skb_head and mit manipulation, we can simply do `it->skb = NULL`, which triggers the new skb allocation to contain encoded trailers.
https://github.com/tempesta-tech/tempesta/blob/2a8d72d25aa638e58bdd2d0359d71c64f259ef9b/fw/http_msg.c#L1303

Comment (EvgeniiMekhanik) [reply fw/http2.c:501]: We don't need to allocate extra skb if there is enough place in current skb. For short answers with trailers (which could be placed in one skb, you double the number of sending skbs, which is very inefficient.

File: fw/http_frame.c (hunk 7 above)
Comment (kingluo) [reply fw/http_frame.c:2149]: I get it. I'll check it later.
A quick question, shouldn't `stream->xmit.frame_length` be non-zero if any continuations? If so, why it will come into this branch?

Comment (EvgeniiMekhanik) [reply fw/http_frame.c:2149]: We come to this branch after all continuation frames will be sent

File: fw/http_stream.h [hunk 9]
```diff
@@ -121,23 +123,27 @@ typedef enum {
...
 	TfwHttpResp 		*resp;
 	struct sk_buff		*skb_head;
 	struct sk_buff		*postponed;
 	unsigned int		h_len;
+	unsigned int		t_len;
 	unsigned int		frame_length;
 	u64			b_len : 60;
 	u64			is_blocked : 1;
-	u64			state : 3;
+	u64			state : 4;
```
Comment (EvgeniiMekhanik) [inline fw/http_stream.h:145]: This field moved to another u64 bitfield. The idea was that b_len + is_blocked + state == 64 bits. I think you can reduce b_len to 58 and nove t_len after this bitfield. Now there is a hole between frame_length and b_len

File: fw/http_frame.c (hunk 7 above)
Comment (kingluo) [reply fw/http_frame.c:2149]: Yes, I know. I mean the code should use `*_len` as conditional. The `frame_length` here looks rather obscure. I'll tune it later.

File: fw/http_frame.c [hunk 10]
```diff
@@ -1894,21 +1894,25 @@ tfw_h2_calc_frame_length(TfwH2Ctx *ctx, TfwStream *stream, TfwFrameType type,
...
-		return stream->xmit.h_len ? 0 : HTTP2_F_END_HEADERS;
-	case HTTP2_DATA:
-		return stream->xmit.b_len ? 0 : HTTP2_F_END_STREAM;
-	default:
-		BUG();
-	};
+	char flags = 0;
 
-	return 0;
+	if (stream->xmit.h_len && !stream->xmit.b_len
```
Comment (EvgeniiMekhanik) [inline fw/http_frame.c:1899]: According to RFC 9113 8.1:

Trailer fields are carried in a field block that also terminates the stream. That is, trailer fields comprise a sequence starting with a [HEADERS](https://www.rfc-editor.org/rfc/rfc9113.html#HEADERS) frame, followed by zero or more [CONTINUATION](https://www.rfc-editor.org/rfc/rfc9113.html#CONTINUATION) frames, where the [HEADERS](https://www.rfc-editor.org/rfc/rfc9113.html#HEADERS) frame bears an END_STREAM flag. Trailers MUST NOT include [pseudo-header fields](https://www.rfc-editor.org/rfc/rfc9113.html#PseudoHeaderFields) ([Section 8.3](https://www.rfc-editor.org/rfc/rfc9113.html#PseudoHeaderFields)). An endpoint that receives pseudo-header fields in trailers MUST treat the request or response as [malformed](https://www.rfc-editor.org/rfc/rfc9113.html#malformed) ([Section 8.1.1](https://www.rfc-editor.org/rfc/rfc9113.html#malformed)).

So if trailer exists we should set HTTP2_F_END_STREAM after sending HEADERS frame for trailers.

File: fw/http_frame.c [hunk 11]
```diff
@@ -1894,21 +1894,25 @@ tfw_h2_calc_frame_length(TfwH2Ctx *ctx, TfwStream *stream, TfwFrameType type,
 static inline char
 tf2_h2_calc_frame_flags(TfwStream *stream, TfwFrameType type)
```
Comment (EvgeniiMekhanik) [inline fw/http_frame.c:1895]: please rename this functiin to `tf2_h2_calc_frame_flags` it was my mistake, I miss it in my PR

Comment (kingluo) [reply fw/http_frame.c:1895]: what do you mean? It's already named as `tf2_h2_calc_frame_flags`.

Comment (EvgeniiMekhanik) [reply fw/http_frame.c:1895]: tfw_h2_calc_frame_flags sorry again my mistake)

File: fw/http2.c (hunk 2 above)
Comment (kingluo) [reply fw/http2.c:501]: You can't use the response body's skb to hpack the trailer, because the skb is allocated from `pg_skb_alloc`, but `tfw_http_msg_expand_data` used by hpack assumes that you can use a whole page with one frag, which is conflicted to each other, and may cause the trailer to be truncated. Your successful case of reusing the frag in the test was nothing but a lucky case where the frag lounge just fit the trailer size. If you try to rerun the test with `-T 1`, you will see an error (frag=1, but the frag cannot actually accept the trailer). So all in all, a new skb seems to be the only feasible way. Note that we also can't use `resp->pool`, as mentioned repeatedly before, that way assumes that the response body follows the headers, i.e., that is a dedicated method for allocating normal headers and body, which does not work with trailers.

File: fw/cache.c (hunk 3 above)
Comment (kingluo) [reply fw/cache.c:2884]: Can't find a way to eliminate this `skb_head` operation, because the response built from cache requires the headers to be built first, so there's no way to avoid creating a new skb before building the body and appending it after the body.

File: fw/http2.c (hunk 2 above)
Comment (EvgeniiMekhanik) [reply fw/http2.c:501]: It works! You should setup iterator->skb to the last body skb and iterator->frag to the last frag (which contains body!) of the last body skb. I write code below and it works! It is a dirty code to show that if you setup iterator all works fine. You should find a way to find the end of the body (skb and its last used fragment) and setup itertor!
```
{
			TfwHttpTransIter *mit = &resp->mit;
			TfwMsgIter *it = &mit->iter;
			
			struct sk_buff *skb = resp->msg.skb_head;
			do {
				if (skb->next == resp->msg.skb_head)
					break;
				skb = skb->next;
			} while(skb != resp->msg.skb_head);

			it->skb = skb;
			it->frag = skb_shinfo(it->skb)->nr_frags - 1;
		}

		{
			unsigned long acc = resp->mit.acc_len;
			TfwHttpTransIter *mit = &resp->mit;
			TfwMsgIter *it = &mit->iter;
			
			r = tfw_h2_hpack_encode_trailer_headers(resp);
			if (unlikely(r))
				goto finish;
			stream->xmit.t_len = resp->mit.acc_len - acc;
		}
```

File: fw/http_stream.h [hunk 12]
```diff
@@ -121,23 +123,27 @@ typedef enum {
...
  * @state		- current stream xmit state (what type of
  * 			  frame should be made for this stream);
+ * @is_trailer_cont	- need to send trailer CONTINUATION frames;
  */
 typedef struct {
 	TfwHttpResp 		*resp;
 	struct sk_buff		*skb_head;
 	struct sk_buff		*postponed;
 	unsigned int		h_len;
+	unsigned int		t_len;
```
Comment (EvgeniiMekhanik) [inline fw/http_stream.h:141]: This structure now has 5 bytes hole. please move `t_len` to avoid this
 `pahole -C TfwHttpXmit fw/tempesta_fw.ko`

File: fw/http_frame.c (hunk 10 above)
Comment (EvgeniiMekhanik) [reply fw/http_frame.c:1899]: This comment is not resolved. If trailers are present we should not set HTTP2_F_END_STREAM here according RFC

File: fw/http2.c (hunk 2 above)
Comment (EvgeniiMekhanik) [reply fw/http2.c:501]: I also change increase body size in test and check it also for segmentation. If you setup iterator all works fine!

Comment (kingluo) [reply fw/http2.c:501]: I don't understand.

resp body skbs come from `pg_skb_alloc` used by the kernel from the backend socket receive path, once the frag is allocated, it cannot be extended in place, but a new chunk is allocated as a new frag.

```c
static int
__skb_fragment(struct sk_buff *skb_head, struct sk_buff *skb, char *pspt,
	       int len, TfwStr *it, int *fragn)
{
...
	/* See if the split starts in the page fragments data. */
	for (i = 0; i < si->nr_frags; ++i) {
		const skb_frag_t *frag = &si->frags[i];
		d_size = skb_frag_size(frag);
		offset = pspt - (char *)skb_frag_address(frag);

		/*
		 * @pspt can be the end of a frag, but it can also be a start of
		 * another fragment. Not necessary, that both frags are
		 * neighbours.
		 */
		if (offset >= 0 && offset < d_size) {
			len = max_t(long, len, offset - d_size);
			ret = __split_pgfrag(skb_head, skb, i, offset, len, it, fragn);
			goto done;
		}
		/*
		 * In case another fragment does not exist, remember the
		 * fragment number, after which you need to insert/delete data.
		 */
		if (offset == d_size)
			j = i;
	}
```
__skb_fragmentkb_fragment
```

In contrast, "tfw_http_msg_add_data" determines the fragment lounge, assuming it can use the entire page where the existing fragment resides.

```c
int
tfw_http_msg_add_data(TfwMsgIter *it, TfwHttpMsg *hm, TfwStr *field,
		      const TfwStr *data)
{
	const TfwStr *c, *end;

	BUG_ON(TFW_STR_DUP(data));
	if (WARN_ON_ONCE(it->frag >= skb_shinfo(it->skb)->nr_frags))
		return -E2BIG;

	TFW_STR_FOR_EACH_CHUNK(c, data, end) {
		char *p;
		unsigned int c_off = 0, c_size, f_room, n_copy;
this_chunk:
		c_size = c->len - c_off;
		if (it->frag >= 0) {
			unsigned int f_size;
			skb_frag_t *frag = &skb_shinfo(it->skb)->frags[it->frag];

			f_size = skb_frag_size(frag);
			f_room = PAGE_SIZE - frag->bv_offset - f_size;
			p = (char *)skb_frag_address(frag) + f_size;
			n_copy = min(c_size, f_room);
			skb_frag_size_add(frag, n_copy);
			ss_skb_adjust_data_len(it->skb, n_copy);
		} else {
			f_room = skb_tailroom(it->skb);
			n_copy = min(c_size, f_room);
			p = skb_put(it->skb, n_copy);
		}
```

We can see that the latter frag extend will overwrite the unallocated area of ​​the previous frag extend. Isn't it? So is it really safe to reuse skb between two different frag extend strategies?

File: fw/http_frame.c (hunk 10 above)
Comment (kingluo) [reply fw/http_frame.c:1899]: What do you mean? Please see this [commit](https://github.com/tempesta-tech/tempesta/pull/2173/commits/372dbb0e17b1172a8e9e22af2d01008de52be96b).

If there are trailers, the body would not be empty. So the code you refer to cannot be true: `!stream->xmit.b_len`.

File: fw/http2.c (hunk 2 above)
Comment (EvgeniiMekhanik) [reply fw/http2.c:501]: And also I check that you can use pool. You just should force allocate new frag in `tfw_http_msg_alloc_from_pool` and setup iterator.

```
static int
tfw_http_msg_alloc_from_pool(TfwHttpTransIter *mit, TfwPool* pool, size_t size, bool forse)
{
	if (!forse) {
		addr = tfw_pool_alloc_not_align_np(pool, size, &np);
	}
	else {
		addr = __tfw_pool_alloc_page(pool, size, /* align */ true);
		np = true;
	}
```

Also little rework of `__tfw_http_msg_expand_from_pool` is necessary in `if (unlikely(skb_room == 0 || nr_frags == MAX_SKB_FRAGS))` part of code.

Comment (EvgeniiMekhanik) [reply fw/http2.c:501]: Here is a branch with example of code https://github.com/tempesta-tech/tempesta/tree/MekhanikEvgenii/fix-1902-dirty

Comment (kingluo) [reply fw/http2.c:502]: **As I raised my doubt above, the response has three different frag allocation strategies:**
`headers (per-cpu page cache) --> body (pg_skb_alloc) --> trailers (kernel pages)`.

**So no matter use pool or not, and no matter reuse the last skb of the body to hpack trailers or not, we cannot reuse the last frag of the body.**

I make a small change to consider both skb reuse and frag distinguish, please check this [commit](https://github.com/tempesta-tech/tempesta/pull/2173/commits/3d06edbbd2a58f319e06e8851ad8ea2e08c4e330). Hopefully it satisfy your need.

---

_P.S. no need to rework the pool functions to adapt trailers, because it has the assumption of the header-body order, if we rework it, the functions will be too much fan in, which seems not a good coding practice. And no offense, but your example code requires much more work to get it to work, where I also tried before._

File: fw/cache.c (hunk 3 above)
Comment (kingluo) [reply fw/cache.c:2884]: Remove the skb_head manipulation loop: [commit](https://github.com/tempesta-tech/tempesta/pull/2173/commits/6bcd9e49065c028403a1c93b5722e3cbaea366d3).

File: fw/http2.c (hunk 2 above)
Comment (EvgeniiMekhanik) [reply fw/http2.c:502]: I don't see problems in different allocation strategies. @const-t please pay attention on this place. Moreover in my example of usage pool  we don't reuse the last frag of the body, but allocate new one. And in my example we don't need a big part of code in `tfw_hpack_hdr_expand`. Much more work is not a problem as I think.

File: fw/hpack.c (hunk 6 above)
Comment (EvgeniiMekhanik) [reply fw/hpack.c:3498]: We don't need this part of code if we use pool.

File: fw/cache.c (hunk 3 above)
Comment (EvgeniiMekhanik) [reply fw/cache.c:2884]: I try to rewrite cache functions to make them able to work with trailers in the proper way next Friday (review day).

File: fw/http_frame.c (hunk 8 above)
Comment (kingluo) [reply fw/http_frame.c:2126]: It's not due to these statements, but `ss_skb_cutoff_data`.

```
[10845.573649] Call Trace:
[10845.575340]  <IRQ>
[10845.577160]  dump_stack+0x96/0xc4
[10845.578844]  skb_fragment.cold+0x5/0x31 [tempesta_fw]
[10845.580546]  ss_skb_cutoff_data+0x696/0x6e0 [tempesta_fw]
[10845.582240]  ? ss_skb_list_chop_head_tail+0x1d0/0x1d0 [tempesta_fw]
[10845.584021]  ? __asan_storeN+0x12/0x20
[10845.585705]  ? eb_delete+0x203/0x210 [tempesta_lib]
[10845.587407]  tfw_http_msg_cutoff_body_chunks+0x6d/0xc0 [tempesta_fw]
[10845.589112]  tfw_h2_stream_xmit_prepare_resp+0x3d8/0x410 [tempesta_fw]
[10845.590800]  tfw_h2_make_frames+0x7dc/0x9d0 [tempesta_fw]
[10845.592491]  ? tcp_established_options+0x1ab/0x330
[10845.594184]  ? tfw_h2_frame_process+0xc80/0xc80 [tempesta_fw]
[10845.595847]  ? bpf_skops_hdr_opt_len+0x210/0x210
[10845.597516]  tfw_sk_fill_write_queue+0x323/0x3e0 [tempesta_fw]
[10845.599158]  ? tfw_cli_conn_release+0xc0/0xc0 [tempesta_fw]
[10845.600788]  ? tfw_h2_sched_activate_stream+0xc8/0x190 [tempesta_fw]
[10845.602427]  ? ss_skb_tcp_entail_list+0x25/0x1a0 [tempesta_fw]
[10845.604115]  ss_tx_action+0xacf/0xc90 [tempesta_fw]
[10845.605703]  ? ss_skb_tcp_entail_list+0x1a0/0x1a0 [tempesta_fw]
[10845.607384]  ? __kernel_fpu_begin_mask+0x9a/0x150
[10845.609071]  net_tx_action+0xfa/0x3c0
[10845.610741]  __do_softirq+0xfe/0x383
[10845.612321]  asm_call_irq_on_stack+0x12/0x20
[10845.613910]  </IRQ>

```

```c
static int
skb_fragment(struct sk_buff *skb_head, struct sk_buff *skb, char *pspt,
             int len, TfwStr *it, int *fragn)
{
        if (unlikely(abs(len) > PAGE_SIZE)) {
                T_WARN("Attempt to add or delete too much data: %u\n", len);
                return -EINVAL;
        }
...
```

File: fw/cache.c (hunk 3 above)
Comment (kingluo) [reply fw/cache.c:2884]: Ok, looking forward to your suggested commits which I can then push directly, thanks.

File: fw/http2.c (hunk 2 above)
Comment (kingluo) [reply fw/http2.c:502]: [done](https://github.com/tempesta-tech/tempesta/pull/2173/commits/bb1589a70478b69aff2a7a455c72da865a0ec4bd).

File: fw/hpack.c (hunk 6 above)
Comment (kingluo) [reply fw/hpack.c:3491]: [ditto](https://github.com/tempesta-tech/tempesta/pull/2173/commits/bb1589a70478b69aff2a7a455c72da865a0ec4bd).

File: fw/http_frame.c (hunk 8 above)
Comment (kingluo) [reply fw/http_frame.c:2127]: No matter whether one trailer header is too long or too much trailer headers, as long as the size of the body plus trailers exceeds a `PAGE_SIZE`, it will fail at `tfw_http_msg_cutoff_body_chunks`, so this is not the bug of this PR, instead, we need to fix it individually.

I hacked the trailer `HEADER_FRAME` size to 100 bytes so the other trailer data could get packed into `CONTINUATION_FRAME`. It passes the test. So the trailer continuation framing logic has no problem.

Please resolve this conversation.

```diff
diff --git a/fw/http_frame.c b/fw/http_frame.c
index 94ccee5e..b6a71d5f 100644
--- a/fw/http_frame.c
+++ b/fw/http_frame.c
@@ -2114,7 +2114,7 @@ do {                                                                      \
        T_FSM_STATE(HTTP2_MAKE_TRAILER_FRAMES) {
                CALC_SND_WND_AND_SET_FRAME_TYPE(HTTP2_HEADERS);
                r = tfw_h2_insert_frame_header(sk, ctx, stream, frame_type,
-                                              snd_wnd, stream->xmit.t_len);
+                                              snd_wnd, 100);
                if (unlikely(r)) {
                        T_WARN("Failed to make trail headers frame %d", r);
                        return r;

```

```diff
diff --git a/encoding/test_encoding.py b/encoding/test_encoding.py
index 5bf2662..bda4e0b 100644
--- a/encoding/test_encoding.py
+++ b/encoding/test_encoding.py
@@ -526,8 +526,12 @@ class TestH2ChunkedWithTrailer(tester.TempestaTest, CommonUtils):

     def setUp(self):
         self.backends = copy.deepcopy(self.backends_template)
+        trailers = f"X-Token: {self.token}\r\n"
+        for i in range(100):
+            trailers += f"foobar-{i}: {'a'*10}\r\n"
+        trailers += "\r\n"
         self.backends[0]["response_content"] += (
-            self.encode_chunked(BODY_PAYLOAD, CHUNK_SIZE)[:-2] + f"X-Token: {self.token}\r\n\r\n"
+            self.encode_chunked(BODY_PAYLOAD, CHUNK_SIZE)[:-2] + f"{trailers}"
         )
         super().setUp()

```

```bash
$ t encoding.test_encoding.TestH2ChunkedWithTrailer
Root privileges are required: need access to module loading on localhost.

----------------------------------------------------------------------
Running functional tests...
----------------------------------------------------------------------

test (encoding.test_encoding.TestH2ChunkedWithTrailer) ... ok

----------------------------------------------------------------------
Ran 1 test in 2.308s

OK

```

```
[73739.183457] [tempesta fw] Tempesta FW is ready
[73739.235065] ---> HTTP2_MAKE_TRAILER_CONTINUATION_FRAMES
```

File: fw/cache.c (hunk 3 above)
Comment (kingluo) [reply fw/cache.c]: @EvgeniiMekhanik Done. https://github.com/tempesta-tech/tempesta/pull/2173/commits/4932ecbd306c5cdc3e80d8198ab6d2de869a9389

File: fw/http_frame.c [hunk 13]
```diff
@@ -1931,13 +1939,14 @@ tfw_h2_insert_frame_header(struct sock *sk, TfwH2Ctx *ctx, TfwStream *stream,
...
 	int r;
+	char flags;
 
 
 	/*
 	 * Very unlikely case, when skb_head and one or more next skbs
 	 * are empty because of transformation during making HEADERS.
 	 */
-	if (type == HTTP2_CONTINUATION || type == HTTP2_DATA) {
+	if (type == HTTP2_CONTINUATION || type == HTTP2_DATA || !stream->xmit.h_len) {
```
[the remark this answers is not in the document]
Comment (kingluo) [reply fw/http_frame.c:1949]: yes, but that script was added after this PR.

File: fw/cache.c [hunk 14]
```diff
@@ -2838,13 +2860,16 @@ tfw_cache_build_resp(TfwHttpReq *req, TfwCacheEntry *ce, long lifetime)
 	if (tfw_cache_set_status(db, ce, resp, &trec, &p, &h_len))
 		goto free;
 
-	for (h = TFW_HTTP_HDR_REGULAR; h < ce->hdr_num; ++h) {
-		bool skip = !TFW_MSG_H2(req) && (h >= ce->hdr_h2_off);
+	trailer_off = TFW_MSG_H2(req) ? ce->trailer_off : ce->hdr_num;
+	for (h = TFW_HTTP_HDR_REGULAR; h < trailer_off; ++h) {
+		bool skip = !TFW_MSG_H2(req) && (h >= ce->hdr_h2_off)
+			     && (h < ce->trailer_off);
```
[the remark this answers is not in the document]
Comment (kingluo) [reply fw/cache.c:2866]: because `trailer_off` can be `ce->hdr_num`.

File: fw/cache.c [hunk 15]
```diff
@@ -2155,6 +2161,21 @@ tfw_cache_copy_resp(TfwCacheEntry *ce, TfwHttpResp *resp, TfwStr *rph,
 	ce->hdr_h2_off = ce->hdr_num + 1;
 	ce->hdr_num += 2;
 
+	ce->trailer_off = ce->hdr_num;
+	ce->trailers = TDB_OFF(db->hdr, p);
+	FOR_EACH_HDR_FIELD_FROM(field, end1, resp, TFW_HTTP_HDR_REGULAR) {
```
[the remark this answers is not in the document]
Comment (kingluo) [reply fw/cache.c:2166]: I tried one loop before, but the previous comment said it brings in too many conditions.

File: fw/cache.c [hunk 16]
```diff
@@ -2155,6 +2161,21 @@ tfw_cache_copy_resp(TfwCacheEntry *ce, TfwHttpResp *resp, TfwStr *rph,
...
+		int hid = field - resp->h_tbl->tbl;
+
+		if (!(field->flags & TFW_STR_TRAILER))
```
[the remark this answers is not in the document]
Comment (kingluo) [reply fw/cache.c:2169]: These conditions are non-sense to trailers, so I removed them.

File: fw/http_frame.c (hunk 10 above)
Comment (kingluo) [reply fw/http_frame.c:1899]: done: https://github.com/tempesta-tech/tempesta/pull/2173/commits/7c4107e41c246a346d7edb965a039e6d0e247285

File: fw/http_frame.c (hunk 7 above)
Comment (EvgeniiMekhanik) [reply fw/http_frame.c:2156]: It is not correct you should send postponed frames after sending headers frames, when h_len == 0 (before you send body) and after you send trailer frames (t_len == 0). Otherwise you can block all other frames until body and trailers will be send (body can be very long)

File: fw/http2.c (hunk 2 above)
Comment (kingluo) [reply fw/http2.c:501]: Can you re-think if it's ok to reuse the skb/frag? They use different allocations, if we mix them, we may override something. Please check my comments above. Anyway, if you're all 100% sure, I'll not insist, then please go ahead with one of your solutions.
`headers (pool, i.e. per-cpu page cache) --> body (pg_skb_alloc) --> trailers (kernel pages)`

File: fw/cache.c (hunk 15 above)
[the remark this answers is not in the document]
Comment (kingluo) [reply fw/cache.c:2165]: Can you give some suggestions? And it's the same with your comment above?

File: fw/http_frame.c (hunk 7 above)
Comment (kingluo) [reply fw/http_frame.c:2156]: I don't get your words. Can you make a suggestion change directly? Thanks.

File: fw/cache.c (hunk 16 above)
[the remark this answers is not in the document]
Comment (const-t) [reply fw/cache.c:2168]: Why are they non-sense? Can you guarantee that hop-by-hop headers from trailer will not be saved into the cache?

Should `cache_resp_hdr_del`  be applicable to trailer headers?

File: fw/cache.c (hunk 15 above)
[the remark this answers is not in the document]
Comment (const-t) [reply fw/cache.c:2165]: I'm suggesting:
```
if (resp->trailers_len > 0) {
    FOR_EACH_HDR_FIELD_FROM(field, end1, resp, TFW_HTTP_HDR_REGULAR) {
    ...
    }
}
```

File: fw/http2.c (hunk 2 above)
Comment (const-t) [reply fw/http2.c:501]: I've seen this patch. However, from my point of view, would be better to do it another way, without changing `tfw_http_msg_expand_data()` and without code duplication in `tfw_hpack_hdr_expand()`. We must using pool and use `tfw_hpack_transform()`. There are few reasons why it's better:
1. We don't change common purpose function `tfw_http_msg_expand_data()` only for trailers case.
2. We don't add [this code](https://github.com/tempesta-tech/tempesta/blob/bfe4c9cab5075d8ced311571299e308cf780b660/fw/hpack.c#L3492).
3. We could use dynamic table, because now we can't do it.
4. Preparation of pool will be located in same place where we do other work with trailers.

File: fw/cache.c (hunk 16 above)
[the remark this answers is not in the document]
Comment (kingluo) [reply fw/cache.c:2168]: I can't refer to any standard specification, but in practice, trailers are user data just like the body. The most typical usage is in scenarios like GRPC (for HTTP/1.1, they are converted one-to-one from GRPC). Also, they should not be modified by proxies, just like the body should be transmitted as is.

But yes, I can add back the conditions if needed.

File: fw/http2.c (hunk 2 above)
Comment (kingluo) [reply fw/http2.c:501]: Fine with me. Submit your commit directly or provide suggested changes please, thank you.

File: fw/cache.c (hunk 15 above)
[the remark this answers is not in the document]
Comment (kingluo) [reply fw/cache.c]: done: https://github.com/tempesta-tech/tempesta/pull/2173/commits/7290143ded06a2f8175773dc2e34901fabea2388

File: fw/http2.c (hunk 2 above)
Comment (EvgeniiMekhanik) [reply fw/http2.c:502]: I fix this part of code. @const-t can you look on it?

**Review by const-t — APPROVED** [review]
LGTM, but need minor fixes. I have to add, that `resp_hdr_set`(delete/replace header) will to work with trailers. Could you please describe it on the wiki page of `resp_hdr_set`.

File: fw/http2.c [hunk 17]
```diff
@@ -485,8 +485,27 @@ tfw_h2_stream_xmit_prepare_resp(TfwStream *stream)
...
+		if (unlikely(r)) {
+			T_WARN("Failed to encode body");
+			goto finish;
+		}
+	}
+
+	if (resp->trailers_len > 0) {
+		unsigned long acc = resp->mit.acc_len;
+		resp->mit.iter.skb = resp->msg.skb_head->prev;
+		resp->mit.iter.frag = skb_shinfo(resp->msg.skb_head->prev)->nr_frags - 1;
```
Comment (krizhanovsky) [inline fw/http2.c:499]: Too long line. No copyright updates.

Please enable git hooks with the coding style checks and automatic copyrights!

File: fw/http_msg.h [hunk 18]
```diff
@@ -2,7 +2,7 @@
  *		Tempesta FW
  *
  * Copyright (C) 2014 NatSys Lab. (info@natsys-lab.com).
- * Copyright (C) 2015-2023 Tempesta Technologies, Inc.
+ * Copyright (C) 2015-2024 Tempesta Technologies, Inc.
```
Comment (krizhanovsky) [inline fw/http_msg.h:5]: The only file with update copyright is the file, which wasn't updated :)

**Review by krizhanovsky — CHANGES_REQUESTED** [review]
With https://github.com/tempesta-tech/tempesta/issues/1902#issuecomment-2091286028 I meant to *remove* the current logic of a trailer header movement to normal headers, even for HTTP/1, but with this PR I see a lot of new code, but not code removals.

The code complexity grows making the performance worse and maintenance harder.

Also now we still have the problem that `Trailer: X-Token` remains in headers.

Lastly, please resolve all comments which are actually resolved.

**Review by const-t — CHANGES_REQUESTED** [review]

File: fw/http.c [hunk 19]
```diff
@@ -673,7 +674,7 @@ tfw_h2_prep_resp(TfwHttpResp *resp, unsigned short status, TfwStr *msg)
 
 	body = TFW_STR_BODY_CH(msg);
 
-	r = tfw_h2_frame_local_resp(resp, hdrs_len, body);
+	r = tfw_h2_frame_local_resp(resp, hdrs_len, body, h2_mode);
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/http.c:677]: `tfw_h2_frame_local_resp` is called from `tfw_cache_build_resp`, so we should check h2_mode

[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/http.c]: Yes fixed

File: fw/cache.c [hunk 20]
```diff
@@ -2690,8 +2692,11 @@ tfw_cache_add_body_page(TfwMsgIter *it, char *p, int sz, bool h2)
  */
 static int
 tfw_cache_build_resp_body(TDB *db, TdbVRec *trec, TfwMsgIter *it, char *p,
-			  unsigned long body_sz, bool h2)
+			  unsigned long body_sz, bool h2, bool chunked_body)
 {
+#define S_CRLF "\r\n"
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/cache.c]: Yes fixed

File: fw/cache.c [hunk 21]
```diff
@@ -2107,7 +2107,8 @@ tfw_cache_copy_resp(TfwCacheEntry *ce, TfwHttpResp *resp, TfwStr *rph,
 			continue;
 		}
 
-		if (hid == TFW_HTTP_HDR_TRANSFER_ENCODING) {
+		if (hid == TFW_HTTP_HDR_TRANSFER_ENCODING
+		    && TFW_MSG_H2(req)) {
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/cache.c]: Yes fixed implement new Cstr flags

File: fw/cache.c [hunk 22]
```diff
@@ -2099,6 +2099,7 @@ tfw_cache_copy_resp(TfwCacheEntry *ce, TfwHttpResp *resp, TfwStr *rph,
 		 */
 		if ((field->flags & (TFW_STR_HBH_HDR | TFW_STR_NOCCPY_HDR |
 				     TFW_STR_TRAILER))
+		    || (field->flags & TFW_STR_TRAILER_HDR && TFW_MSG_H2(req))
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/cache.c]: Yes fixed implement new Cstr flags

**Review by const-t — APPROVED** [review]
LGTM

File: fw/cache.c [hunk 23]
```diff
@@ -2155,6 +2160,24 @@ tfw_cache_copy_resp(TfwCacheEntry *ce, TfwHttpResp *resp, TfwStr *rph,
 	ce->hdr_h2_off = ce->hdr_num + 1;
 	ce->hdr_num += 2;
 
+	ce->trailer_off = ce->hdr_num;
+	ce->trailers = TDB_OFF(db->hdr, p);
+	if (resp->trailers_len > 0) {
+		FOR_EACH_HDR_FIELD_FROM(field, end1, resp, TFW_HTTP_HDR_REGULAR) {
+			int hid = field - resp->h_tbl->tbl;
+
+			if (!(field->flags & TFW_STR_TRAILER))
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/cache.c:2194]: @krizhanovsky  how do you think? I think that trailers are additional headers which should not be checked. Please answer here.

File: fw/http_parser.c [hunk 24]
```diff
@@ -2492,6 +2492,133 @@ __req_parse_transfer_encoding(TfwHttpMsg *hm, unsigned char *data, size_t len)
 	return __parse_transfer_encoding(hm, data, len, true, false);
 }
 
+static int
+__resp_parse_trailer(TfwHttpMsg *hm, unsigned char *data, size_t len)
```
Comment (const-t) [inline fw/http_parser.c:2496]: From my point of view, too much efforts to support rarely used feature. I would suggest to drop `Trailer` header at all even without parsing for both directions, downstream and upstream. Accordingly to [RFC](https://datatracker.ietf.org/doc/html/rfc9110#section-6.6.2) `Trailer` is just a hint, that doesn't give any guaranties and implementation shouldn't rely on it.


> A sender that intends to generate one or more trailer fields in a message **SHOULD** generate a [Trailer](https://datatracker.ietf.org/doc/html/rfc9110#field.trailer) header field in the header section of that message to indicate which fields might be present in the trailers

> though there is no guarantee that a sender of Trailer will always follow through by sending the named fields

**Review by const-t — CHANGES_REQUESTED** [review]
Needed small changes and discussion

File: fw/http_parser.c (hunk 24 above)
Comment (const-t) [inline fw/http_parser.c:2496]: Seems we allow duplicated `Trailer` header, though RFC doesn't contain direct prohibitions this looks like confusion and we must not allow duplicated `Trailer` header.

File: fw/http_frame.c [hunk 25]
```diff
@@ -1883,23 +1883,28 @@ tfw_h2_calc_frame_length(TfwH2Ctx *ctx, TfwStream *stream, TfwFrameType type,
...
-			(stream->xmit.b_len ? HTTP2_F_END_HEADERS :
-			 HTTP2_F_END_HEADERS | HTTP2_F_END_STREAM);
-	case HTTP2_CONTINUATION:
-		return stream->xmit.h_len ? 0 : HTTP2_F_END_HEADERS;
-	case HTTP2_DATA:
-		return stream->xmit.b_len ? 0 : HTTP2_F_END_STREAM;
-	default:
-		BUG();
-	};
+	char flags = 0;
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/http_frame.c:1889]: Yes fixed

File: fw/http_frame.c [hunk 26]
```diff
@@ -1919,16 +1924,18 @@ tfw_h2_insert_frame_header(struct sock *sk, TfwH2Ctx *ctx, TfwStream *stream,
 	unsigned int mark = stream->xmit.skb_head->mark;
 	unsigned int max_len = (*snd_wnd > TLS_MAX_PAYLOAD_SIZE + TLS_MAX_OVERHEAD) ?
 		TLS_MAX_PAYLOAD_SIZE : *snd_wnd - TLS_MAX_OVERHEAD;
+	bool trailers = false;
 	unsigned int length;
 	char *data;
 	int r = 0;
-
+	char flags;
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/http_frame.c:1931]: Yes fixed

File: fw/http_stream.c [hunk 27]
```diff
@@ -320,7 +321,7 @@ tfw_h2_stream_add_closed(TfwH2Ctx *ctx, TfwStream *stream)
  */
 TfwStreamFsmRes
 tfw_h2_stream_fsm(TfwH2Ctx *ctx, TfwStream *stream, unsigned char type,
-		  unsigned char flags, bool send, TfwH2Err *err)
+		  char flags, bool send, TfwH2Err *err)
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/http_stream.c:324]: yes fixed

File: fw/http_msg.c [hunk 28]
```diff
@@ -1098,16 +1132,48 @@ tfw_http_msg_del_hbh_hdrs(TfwHttpMsg *hm)
...
 }
 
+int
+tfw_http_msg_adjust_trailer_hdr(TfwHttpMsg *hm)
+{
+	TfwHttpHdrTbl *ht = hm->h_tbl;
+	int r = 0;
+
+	if (unlikely(hm->trailer_hid)) {
+		TfwStr *hdr = &ht->tbl[hm->trailer_hid];
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/http_msg.c]: Remove this part of code

File: fw/http_parser.c (hunk 24 above)
Comment (EvgeniiMekhanik) [reply fw/http_parser.c:2524]: Remove this part of code

File: fw/http_parser.c [hunk 29]
```diff
@@ -5283,6 +5327,15 @@ tfw_http_parse_req(void *req_data, unsigned char *data, unsigned int len,
 				p += 17;
 				__FSM_MOVE_hdr_fixup(RGen_LWS, 1);
 			}
+			if (likely(__data_available(p, 8))
+				   && C8_INT_LCM(p, 't', 'r', 'a', 'i',
+						    'l', 'e', 'r', ':'))
+			{
+				__msg_hdr_chunk_fixup(data, __data_off(p + 8));
+				parser->_i_st = &&Req_HdrTrailerV;
+				p += 8;
```
Comment (const-t) [inline fw/http_parser.c:5336]: For HTTP1 if there is no whitespaces we parse headers into 3 chunks: [name][:][value], some functions may rely on that. But here we will have [name:][v][alue]. Or if there is whitespace we will have: [name:][ ][value] and in this case we lose flag for whitespace. Let's do this consistent to other headers, `p += 7` and let `__FSM_MOVE_hdr_fixup(RGen_LWS, 1);` to fixup whitespace.

File: fw/http_parser.c [hunk 30]
```diff
@@ -11172,6 +11245,14 @@ __resp_parse_cache_control(TfwHttpResp *resp, unsigned char *data, size_t len)
 
 	__FSM_START(parser->_i_st);
 
+	/*
+	 * According RFC 7230 4.1.2:
+	 * A sender MUST NOT generate a trailer that contains response
+	 * control data (e.g., see Section 7.1 of [RFC7231]).
+	 */
+	if (unlikely(test_bit(TFW_HTTP_B_HEADERS_PARSED, resp->flags)))
```
Comment (const-t) [inline fw/http_parser.c:11253]: Let's move this condition to `Resp_I_CC_start` just to not walk through it on each function call, on segmentation. In other functions as well, where it is possible.

**Review by const-t — APPROVED** [review]
LGTM, but need minor changes.

File: fw/http_parser.c (hunk 30 above)
Comment (EvgeniiMekhanik) [reply fw/http_parser.c:11253]: Yes fixed

File: fw/http_parser.c (hunk 29 above)
Comment (EvgeniiMekhanik) [reply fw/http_parser.c:5336]: Yes fixed

File: fw/cache.c [hunk 31]
```diff
@@ -2818,16 +2876,50 @@ tfw_cache_build_resp_body(TDB *db, TdbVRec *trec, TfwMsgIter *it, char *p,
...
+	if (unlikely(!body_sz))
+		goto add_zero_chunk;
+
+	if (chunked_body) {
+		char cstr_blen[TFW_ULTOA_BUF_SIZ] = {0};
+		/*
+		 * Encode body in one single chunk.
+		 * blen\r\nbody
+		 */
+		TfwStr b_len = {
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/cache.c:2888]: Yes fixed

File: fw/http2.c [hunk 32]
```diff
@@ -513,14 +513,36 @@ tfw_h2_stream_xmit_prepare_resp(TfwStream *stream)
...
+		}
+
 		stream->xmit.b_len = TFW_HTTP_RESP_CUT_BODY_SZ(resp);
 		/*
 		 * Response is chunked encoded, but it is not a response
 		 * on HEAD request.
 		 */
 		if (test_bit(TFW_HTTP_B_CHUNKED, resp->flags)
-		    && !test_bit(TFW_HTTP_B_VOID_BODY, resp->flags))
+		    && !test_bit(TFW_HTTP_B_VOID_BODY, resp->flags)) {
```
Comment (krizhanovsky) [inline fw/http2.c:539]:
```suggestion
		    && !test_bit(TFW_HTTP_B_VOID_BODY, resp->flags))
		{
```

File: fw/http_frame.c [hunk 33]
```diff
@@ -1883,23 +1883,28 @@ tfw_h2_calc_frame_length(TfwH2Ctx *ctx, TfwStream *stream, TfwFrameType type,
...
+	if (!stream->xmit.b_len && !stream->xmit.t_len
+	    && (type == HTTP2_HEADERS || type == HTTP2_DATA)
+	    && !tfw_h2_stream_is_eos_sent(stream))
+		flags |= HTTP2_F_END_STREAM;
+
+	if (!stream->xmit.b_len && stream->xmit.t_len
+	    && type == HTTP2_HEADERS && trailers)
+		flags |= HTTP2_F_END_STREAM;
+
+
```
Comment (krizhanovsky) [inline fw/http_frame.c:1900]: extra empty line

File: fw/http_parser.c [hunk 34]
```diff
@@ -467,6 +467,7 @@ __FSM_STATE(st, cold) {							\
 	__FSM_JMP(RGen_HdrOtherN);					\
 }
 
+
```
Comment (krizhanovsky) [inline fw/http_parser.c:470]: extra empty line

**Review by krizhanovsky — APPROVED** [review]
LGTM, I didn't see any issues, just some cleanups are required

File: fw/cache.c [hunk 35]
```diff
@@ -196,6 +201,16 @@ __tfw_dbg_dump_ce(const TfwCacheEntry *ce)
...
 #define TFW_CSTR_SPEC_IDX	0x2
+/*
+ * TfwCStr contains header, which should be skipped for http2 responses
+ * constructed from cache.
+ */
+#define TFW_CSTR_SKIP_FOR_H2	0x4
+
+/*
+ * TfwCStr contains trailer.
+ */
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/cache.c:212]: Yes fixed

File: fw/cache.c [hunk 36]
```diff
@@ -989,37 +1017,58 @@ do {									\
...
+					|| (type == TFW_CACHE_TRAILER
+					    && (s->flags & TFW_CSTR_TRAILER))));
+		}
+
 		*p += TFW_CSTR_HDRLEN;
 		r = write_actor(db, trec, resp, p, s->len, &dc_iter);
-		if (unlikely(r))
-			break;
+			if (unlikely(r))
+				break;
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/cache.c:1069]: yes fixed

File: fw/http_parser.c (hunk 34 above)
Comment (EvgeniiMekhanik) [reply fw/http_parser.c:470]: Yes fixed

File: fw/http_frame.c (hunk 33 above)
Comment (EvgeniiMekhanik) [reply fw/http_frame.c:1900]: Yes fixed

File: fw/http2.c (hunk 32 above)
Comment (EvgeniiMekhanik) [reply fw/http2.c:539]: Yes fixed

File: fw/http.h [hunk 37]
```diff
@@ -764,6 +766,7 @@ int tfw_h2_resp_add_loc_hdrs(TfwHttpResp *resp, const TfwHdrMods *h_mods,
 int tfw_h2_resp_status_write(TfwHttpResp *resp, unsigned short status,
 			     bool use_pool, bool cache);
 int tfw_h2_resp_encode_headers(TfwHttpResp *resp);
+int tfw_h2_hpack_encode_trailer_headers(TfwHttpResp *resp);
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/http.h:769]: yes fixed

File: fw/cache.c [hunk 38]
```diff
@@ -2946,6 +3056,7 @@ tfw_cache_build_resp(TfwHttpReq *req, TfwCacheEntry *ce, long age)
 	if (!(resp = tfw_http_msg_alloc_resp(req)))
 		goto out;
 
+
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/cache.c]: yes fixed

File: fw/http.c [hunk 39]
```diff
@@ -5099,6 +5080,47 @@ tfw_h2_hpack_encode_headers(TfwHttpResp *resp, const TfwHdrMods *h_mods)
...
+		if (hid == TFW_HTTP_HDR_SERVER)
+			continue;
+
+		r = tfw_hpack_transform(resp, tgt);
+		if (unlikely(r))
+			return r;
+	}
+
+	return 0;
+}
```
[the remark this answers is not in the document]
Comment (EvgeniiMekhanik) [reply fw/http.c:5122]: yes fixed

**Review by EvgeniiMekhanik — APPROVED** [review]
