### PR TITLE
Fix failover reference accounting (fixes #580)

### LINKED ISSUE #580: BUG while restarting backend
BUG occurs when Tempesta runs as usual being loaded with `ab` and the backend server (nginx) were restarted.

~~~
[  853.347930] [tempesta] Warning: sched_http: Unable to select server from group 'default'
[  853.347933] [tempesta] Warning: Unable to find a backend server
[  853.348116] [tempesta] Warning: sched_http: Unable to select server from group 'default'
[  853.348118] [tempesta] Warning: Unable to find a backend server
[  853.349482] [tempesta] Warning: sched_http: Unable to select server from group 'default'
[  853.349485] [tempesta] Warning: Unable to find a backend server
[  853.351177] [tempesta] Warning: sched_http: Unable to select server from group 'default'
[  853.351180] [tempesta] Warning: Unable to find a backend server
[  853.353840] [tempesta] Warning: sched_http: Unable to select server from group 'default'
[  853.353844] [tempesta] Warning: Unable to find a backend server
[  853.500336] ------------[ cut here ]------------
[  853.500370] kernel BUG at /root/projects/tempesta/tempesta_fw/sock.c:221!
[  853.500404] invalid opcode: 0000 [#1] PREEMPT SMP
[  853.500433] Modules linked in: tfw_sched_rr(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) e1000 ahci libahci 9p [last unloaded: tempesta_db]
[  853.500519] CPU: 1 PID: 14 Comm: ksoftirqd/1 Tainted: G           O    4.1.24-tfw #150
[  853.500553] task: ffff88015acf95f0 ti: ffff88015ad14000 task.ti: ffff88015ad14000
[  853.500580] RIP: 0010:[<ffffffffa00dd060>]  [<ffffffffa00dd060>] ss_send+0x160/0x1a0 [tempesta_fw]
[  853.500615] RSP: 0018:ffff88015ad17788  EFLAGS: 00010246
[  853.500632] RAX: 0000000080000101 RBX: ffff880150d42020 RCX: 0000000000000102
[  853.500658] RDX: 0000000000000000 RSI: ffff880150d42050 RDI: 0000000000000000
[  853.500685] RBP: ffff88015ad177b8 R08: 0000000000000003 R09: 0000000000000005
[  853.500706] R10: 0000002f0000001a R11: ffffea00054ec080 R12: ffff880159cebbe0
[  853.500727] R13: ffff880159cebc18 R14: 0000000000000007 R15: ffff880150d42020
[  853.500754] FS:  0000000000000000(0000) GS:ffff88017fc40000(0000) knlGS:0000000000000000
[  853.500794] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  853.500815] CR2: 00007f6523e91978 CR3: 00000001537d7000 CR4: 00000000001406a0
[  853.500855] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  853.500885] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  853.500920] Stack:
[  853.500935]  0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  853.500975]  ffff880150d42020 ffff880159cebbe0 ffff88015ad177c8 ffffffffa00c0684
[  853.501012]  ffff88015ad17808 ffffffffa00c28f7 ffff880100000001 ffff880150d420b8
[  853.501058] Call Trace:
[  853.501083]  [<ffffffffa00c0684>] tfw_connection_send+0x14/0x20 [tempesta_fw]
[  853.501120]  [<ffffffffa00c28f7>] tfw_http_req_cache_cb+0x227/0x2e0 [tempesta_fw]
[  853.501158]  [<ffffffffa00bdd30>] tfw_cache_process+0x140/0x200 [tempesta_fw]
[  853.501194]  [<ffffffff8100b059>] ? read_tsc+0x9/0x10
[  853.501220]  [<ffffffff8108c4f9>] ? __getnstimeofday64+0x49/0xd0
[  853.501251]  [<ffffffffa00c3046>] tfw_http_msg_process+0x3d6/0x500 [tempesta_fw]
[  853.501295]  [<ffffffffa00dad93>] ? tfw_pool_alloc_pages+0x63/0xd0 [tempesta_fw]
[  853.501328]  [<ffffffffa00c0dff>] __gfsm_fsm_exec+0x5f/0xa0 [tempesta_fw]
[  853.501361]  [<ffffffffa00c115f>] tfw_gfsm_dispatch+0xf/0x20 [tempesta_fw]
[  853.501393]  [<ffffffffa00c06d5>] tfw_connection_recv+0x45/0xa0 [tempesta_fw]
[  853.501423]  [<ffffffffa00dca00>] ss_tcp_process_data+0x180/0x3f0 [tempesta_fw]
[  853.501455]  [<ffffffffa00dcd80>] ss_tcp_data_ready+0x60/0xa0 [tempesta_fw]
[  853.501490]  [<ffffffff8139fc26>] tcp_data_queue+0x526/0xd40
[  853.501520]  [<ffffffff813a3341>] tcp_rcv_established+0x661/0x780
[  853.501548]  [<ffffffff813ad964>] tcp_v4_do_rcv+0xb4/0x3c0
[  853.501576]  [<ffffffff813ae97e>] tcp_v4_rcv+0x51e/0x990
[  853.501604]  [<ffffffffa00b08cf>] ? tdb_htrie_lookup+0x3f/0x60 [tempesta_db]
[  853.501651]  [<ffffffffa00b18a9>] ? tdb_rec_get+0x29/0x60 [tempesta_db]
[  853.501682]  [<ffffffff81388b8a>] ip_local_deliver_finish+0x7a/0x120
[  853.501713]  [<ffffffff813890ca>] ip_local_deliver+0x5a/0xb0
[  853.501732]  [<ffffffff813ae426>] ? tcp_v4_early_demux+0x106/0x140
[  853.501761]  [<ffffffff81388eee>] ip_rcv_finish+0x2be/0x310
[  853.501785]  [<ffffffff8138943f>] ip_rcv+0x31f/0x410
[  853.501808]  [<ffffffff81388c30>] ? ip_local_deliver_finish+0x120/0x120
[  853.502556]  [<ffffffff8135c350>] __netif_receive_skb_core+0x550/0x7c0
[  853.503256]  [<ffffffff8135c617>] __netif_receive_skb+0x57/0x80
[  853.503256]  [<ffffffff8135d30a>] process_backlog+0xba/0x170
[  853.503256]  [<ffffffff8135ca79>] net_rx_action+0x129/0x2e0
[  853.503256]  [<ffffffff810472c7>] __do_softirq+0x127/0x230
[  853.503256]  [<ffffffff8105fcb0>] ? smpboot_thread_fn+0x30/0x290
[  853.503256]  [<ffffffff810473eb>] run_ksoftirqd+0x1b/0x60
[  853.503256]  [<ffffffff8105fee8>] smpboot_thread_fn+0x268/0x290
[  853.503256]  [<ffffffff8105fc80>] ? sort_range+0x20/0x20
[  853.503256]  [<ffffffff8105d18d>] kthread+0xdd/0xf0
[  853.503256]  [<ffffffff81420606>] ? dev_mc_net_exit+0x6/0x20
[  853.503256]  [<ffffffff8105d0b0>] ? kthread_stop+0x60/0x60
[  853.503256]  [<ffffffff81428392>] ret_from_fork+0x42/0x70
[  853.503256]  [<ffffffff8105d0b0>] ? kthread_stop+0x60/0x60
[  853.503256] Code: 00 00 00 48 89 55 d8 eb bf 66 90 48 83 c4 20 89 d8 5b 41 5c 5d c3 0f 1f 44 00 00 e8 cb 2d 29 e1 85 c0 75 11 bb f4 ff ff ff eb b2 <0f> 0b 66 0f 1f 44 00 00 0f 0b 48 c7 c7 f0 5c 0e a0 31 c0 bb f4
[  853.503256] RIP  [<ffffffffa00dd060>] ss_send+0x160/0x1a0 [tempesta_fw]
[  853.503256]  RSP <ffff88015ad17788>
~~~

### PR DESCRIPTION
**Pull request by milabs**

### CODE REVIEW

File: tempesta_fw/connection.h [hunk 1]
```diff
@@ -177,7 +177,9 @@ tfw_connection_put(TfwConnection *conn)
 static inline void
 tfw_connection_put_to_death(TfwConnection *conn)
 {
-	atomic_add(TFW_CONN_DEATHCNT, &conn->refcnt);
+	/* Do not put dead connections to death state */
+	if (tfw_connection_nfo(conn))
```
Comment (krizhanovsky) [inline tempesta_fw/connection.h]: What about `refcnt = 0`? It seems it's invalid case, so it has sense to add BUG_ON() for it.

Comment (keshonok) [inline tempesta_fw/connection.h]: As far as I understand, initially `refcnt` is zero. Currently it's not assigned a value until a connection is established at least once.

File: tempesta_fw/connection.h [hunk 2]
```diff
@@ -164,10 +164,9 @@ static inline bool
...
 	int rc;
-
-	if (unlikely(!conn))
-		return false;
-
+	rc = atomic_read(&conn->refcnt);
+	if (unlikely(!rc || rc == TFW_CONN_DEATHCNT))
+		return true;
 	rc = atomic_dec_return(&conn->refcnt);
 	if (unlikely(!rc || rc == TFW_CONN_DEATHCNT))
```
Comment (keshonok) [inline tempesta_fw/connection.h]: With the latest changes, I don't think `refcnt` ever reaches zero. The last reference is held by the connection itself, and at that time `TFW_CONN_DEATHCNT` is set already.

File: tempesta_fw/connection.h [hunk 3]
```diff
@@ -164,10 +164,9 @@ static inline bool
 tfw_connection_put(TfwConnection *conn)
 {
 	int rc;
-
-	if (unlikely(!conn))
-		return false;
-
+	rc = atomic_read(&conn->refcnt);
+	if (unlikely(!rc || rc == TFW_CONN_DEATHCNT))
+		return true;
```
Comment (keshonok) [inline tempesta_fw/connection.h]: As far as I can see, with the latest changes `refcnt` may equal zero only once, when Tempesta starts. When a connection is established at least once, `refcnt` is either a positive value meaning the connection is active, or `TFW_CONN_DEATHCNT`. Yet, `refcnt` is checked for zero for the whole run time of Tempesta which appears unnecessary and excessive.

Further, the only goal of this code appears to be protection against a failover procedure that occurs without establishing a connection first. Yet it will be executed on each and every meaningful connection `put` which also appears to be unnecessary and excessive.  With that in mind, I believe that compensating a `put` in `tfw_sock_srv_do_failover()` in case of this kind of a failover (a failover in a failover state) is a lesser evil.

```C
if (tfw_connection_nfo(conn)) {
        tfw_connection_put_to_death(conn);
        tfw_connection_drop(conn);
        TFW_INC_STAT_BH(serv.conn_disconnects);
} else {
        tfw_connection_get(conn);
}

Comment (krizhanovsky) [inline tempesta_fw/connection.h]: What if exactly at this point somebody `put()`s the connection? So first `rc` check fail and we're decrementing zero refcounter.

**Comment by keshonok** [comment]
Looks good to me.

**Comment by krizhanovsky** [comment]
Good to merge
