### PR TITLE
Fix #782: release a server connection resources on shutdown

### LINKED ISSUE #782: Kernel BUG at tempesta_fw/sock_srv.c:520 while running regression.test_reboot.RebootUnderLoadTest on QEMU
Simply running all tests (`./run_tests.py`) with `tests_config.ini` copied from the sample on QEMU triggers a chain of two BUGs:
- one `kernel BUG at /root/tempesta/tempesta_fw/sock_srv.c:520!` and
- consequently a `BUG tfw_srv_conn_cache (Tainted: G      D    O   ): Objects remaining in tfw_srv_conn_cache on __kmem_cache_shutdown()`.

This semi-reliably happens while running `regression.test_reboot.RebootUnderLoadTest`.

Configuration:
- QEMU, 4C SMP on 4C8T CPU
- both the client, the servers and Tempesta on the same host
- intelfx/tempesta@4f010fef4356a6f4e35dca03d5d270d8dd1a6b38 (branch [`crash/sock_srv.c-520`](https://github.com/intelfx/tempesta/tree/crash/sock_srv.c-520))

Log excerpt (http://ix.io/yOS):
```
[23398.445468] [tdb] Start Tempesta DB
[23398.451660] [tempesta] Initializing Tempesta FW kernel module...
[23398.455965] [tempesta] Registering new scheduler: hash
[23398.458404] [tempesta] Registering new scheduler: http
[23398.460842] [tempesta] Registering new scheduler: ratio
[23401.937333] [tempesta] Starting all modules...
[23401.944078] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff8e7161800000
[23401.945307] [tempesta] Open listen socket on: 0.0.0.0
[23401.946025] [tempesta] modules are started
[23412.007301] [tempesta] Stopping all modules...
[23412.020273] [tdb] Close table 'filter0.tdb'
[23412.021137] ------------[ cut here ]------------
[23412.021884] kernel BUG at /root/tempesta/tempesta_fw/sock_srv.c:520!
[23412.022709] invalid opcode: 0000 [#1] SMP
[23412.023357] Modules linked in: tfw_sched_ratio(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) tempesta_tls(O) tcp_diag inet_diag xt_tcpudp iptable_filter fuse crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul ppdev glue_helper ablk_helper parport_pc bochs_drm snd_pcm ttm cryptd drm_kms_helper sg snd_timer drm parport joydev snd evdev soundcore serio_raw pcspkr button ip_tables x_tables autofs4 ext4 crc16 jbd2 fscrypto mbcache sr_mod sd_mod cdrom ata_generic ata_piix libata i2c_piix4 crc32c_intel psmouse scsi_mod e1000 floppy [last unloaded: tempesta_tls]
[23412.029684] CPU: 0 PID: 4396 Comm: sysctl Tainted: G           O    4.9.35+ #1
[23412.030606] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-20170228_101828-anatol 04/01/2014
[23412.031729] task: ffff8e71708e0e80 task.stack: ffffb179c0ae8000
[23412.032579] RIP: 0010:[<ffffffffc0699914>]  [<ffffffffc0699914>] tfw_sock_srv_del_conns+0x114/0x120 [tempesta_fw]
[23412.033773] RSP: 0018:ffffb179c0aebcf8  EFLAGS: 00010202
[23412.034614] RAX: 0000000000000001 RBX: ffff8e71718692d8 RCX: dead000000000200
[23412.035575] RDX: ffff8e7171869350 RSI: ffffd179bfc02aa0 RDI: ffff8e7169a37f80
[23412.036543] RBP: ffff8e71718692a0 R08: ffff8e71718692d8 R09: ffffffffc06998cf
[23412.037518] R10: ffffd42701d3e440 R11: 0000000000000000 R12: ffff8e7169a37f80
[23412.038494] R13: ffff8e7169a37f70 R14: ffff8e7175cb0000 R15: ffffb179c0aebf20
[23412.039474] FS:  00007fa1640ef880(0000) GS:ffff8e717fc00000(0000) knlGS:0000000000000000
[23412.040520] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[23412.041667] CR2: 00007fa1637ecd00 CR3: 0000000076be3000 CR4: 00000000001406f0
[23412.042730] Stack:
[23412.043410]  ffff8e7169a37f70 ffff8e7174f91310 ffffffffc0699800 ffff8e7174f91300
[23412.044498]  0000562658d632e0 ffffffffc0695fbd 00000000c0ad4098 ffffffffc06adfd0
[23412.045596]  ffffffffc06adfd0 ffffb179c0aebe20 ffffffffc06ad640 ffffffffc0699a12
[23412.046729] Call Trace:
[23412.047469]  [<ffffffffc0699800>] ? tfw_cfg_handle_ratio_predyn_opts+0x160/0x160 [tempesta_fw]
[23412.048635]  [<ffffffffc0695fbd>] ? tfw_sg_for_each_srv+0x5d/0xa0 [tempesta_fw]
[23412.049687]  [<ffffffffc0699a12>] ? tfw_clean_srv_groups+0xf2/0x100 [tempesta_fw]
[23412.050748]  [<ffffffffc0679db4>] ? tfw_cfg_stop+0x74/0xb0 [tempesta_fw]
[23412.051754]  [<ffffffffc0694a12>] ? handle_sysctl_state_io+0x1a2/0x1d0 [tempesta_fw]
[23412.052843]  [<ffffffffab20b82e>] ? mutex_lock+0xe/0x30
[23412.053763]  [<ffffffffc06948af>] ? handle_sysctl_state_io+0x3f/0x1d0 [tempesta_fw]
[23412.054850]  [<ffffffffaae825d3>] ? proc_sys_call_handler+0xe3/0x100
[23412.055860]  [<ffffffffaae07173>] ? __vfs_write+0x33/0x160
[23412.056810]  [<ffffffffaae08440>] ? vfs_write+0xb0/0x190
[23412.057750]  [<ffffffffaae09832>] ? SyS_write+0x52/0xc0
[23412.058680]  [<ffffffffab20e2bb>] ? entry_SYSCALL_64_fastpath+0x1e/0xad
[23412.059699] Code: 8b 56 38 4c 89 f5 49 89 c6 48 39 d3 0f 85 45 ff ff ff 0f 0b 5b 31 c0 5d 41 5c 41 5d 41 5e c3 0f 0b 0f 0b 0f 0b 0f 0b 0f 0b 0f 0b <0f> 0b 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 55 53 48 83
[23412.062713] RIP  [<ffffffffc0699914>] tfw_sock_srv_del_conns+0x114/0x120 [tempesta_fw]
[23412.064147]  RSP <ffffb179c0aebcf8>
[23412.066186] ---[ end trace 854990c91b3161af ]---
[23412.083227] [tempesta] Un-registering scheduler: hash
[23412.109398] [tempesta] Un-registering scheduler: http
[23412.160724] [tempesta] Un-registering scheduler: ratio
[23412.202969] [tempesta] exiting...
[23412.203917] =============================================================================
[23412.205106] BUG tfw_srv_conn_cache (Tainted: G      D    O   ): Objects remaining in tfw_srv_conn_cache on __kmem_cache_shutdown()
[23412.207230] -----------------------------------------------------------------------------
[23412.207230]
[23412.209125] INFO: Slab 0xffffd42701c61a40 objects=18 used=1 fp=0xffff8e71718697e0 flags=0xffffc000000080
[23412.210391] CPU: 2 PID: 4409 Comm: rmmod Tainted: G    B D    O    4.9.35+ #1
[23412.211505] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-20170228_101828-anatol 04/01/2014
[23412.212815]  0000000000000000 ffffffffaaf2e9f4 ffffd42701c61a40 ffffb179c08c3db8
[23412.213957]  ffffffffaade19a0 240c467700000020 ffffb179c08c3dc8 ffffb179c08c3d78
[23412.215104]  656a624faacfddd3 616d657220737463 6e6920676e696e69 7672735f77667420
[23412.216236] Call Trace:
[23412.217004]  [<ffffffffaaf2e9f4>] ? dump_stack+0x5c/0x78
[23412.217941]  [<ffffffffaade19a0>] ? slab_err+0xb0/0xe0
[23412.218860]  [<ffffffffaade6c79>] ? __kmalloc+0x159/0x1d0
[23412.219791]  [<ffffffffaade7f2f>] ? __kmem_cache_shutdown+0x14f/0x330
[23412.220849]  [<ffffffffaade7f4e>] ? __kmem_cache_shutdown+0x16e/0x330
[23412.222065]  [<ffffffffaada9379>] ? shutdown_cache+0x19/0x60
[23412.223041]  [<ffffffffaada9b5f>] ? kmem_cache_destroy+0x1df/0x210
[23412.224026]  [<ffffffffc0694a70>] ? tfw_exit+0x30/0x60 [tempesta_fw]
[23412.225007]  [<ffffffffaad014ac>] ? SyS_delete_module+0x18c/0x260
[23412.225965]  [<ffffffffaac0326c>] ? exit_to_usermode_loop+0x8c/0xb0
[23412.226928]  [<ffffffffab20e2bb>] ? entry_SYSCALL_64_fastpath+0x1e/0xad
[23412.227909] INFO: Object 0xffff8e71718692a0 @offset=672
[23412.228849] kmem_cache_destroy tfw_srv_conn_cache: Slab cache still has objects
[23412.229975] CPU: 2 PID: 4409 Comm: rmmod Tainted: G    B D    O    4.9.35+ #1
[23412.230999] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-20170228_101828-anatol 04/01/2014
[23412.232239]  0000000000000000 ffffffffaaf2e9f4 ffff8e7175268b40 0000000000000000
[23412.233321]  ffffffffaada9b7d 00ff8e71752681a8 ffffb179c08c3e70 ffffb179c08c3e70
[23412.234420]  ffffb179c08c3e80 ffffb179c08c3e80 240c4677ecd309e0 000000000000000a
[23412.235499] Call Trace:
[23412.236222]  [<ffffffffaaf2e9f4>] ? dump_stack+0x5c/0x78
[23412.237123]  [<ffffffffaada9b7d>] ? kmem_cache_destroy+0x1fd/0x210
[23412.238081]  [<ffffffffc0694a70>] ? tfw_exit+0x30/0x60 [tempesta_fw]
[23412.239040]  [<ffffffffaad014ac>] ? SyS_delete_module+0x18c/0x260
[23412.239983]  [<ffffffffaac0326c>] ? exit_to_usermode_loop+0x8c/0xb0
[23412.240938]  [<ffffffffab20e2bb>] ? entry_SYSCALL_64_fastpath+0x1e/0xad
```

### PR DESCRIPTION
**Pull request by dkirjanov**
make sure the resources of a connection closed by a backend
right before the shutdown are released.

Signed-off-by: Denis Kirjanov <dk@tempesta-tech.com>

### CODE REVIEW

File: tempesta_fw/sock_srv.c [hunk 1]
```diff
@@ -413,6 +413,8 @@ tfw_sock_srv_disconnect(TfwConn *conn)
 	 */
 	if (atomic_read(&conn->refcnt) != TFW_CONN_DEATHCNT)
 		ret = ss_close_sync(sk, true);
+	else if (atomic_read(&conn->refcnt) == TFW_CONN_DEATHCNT)
```
Comment (ikoveshnikov) [inline tempesta_fw/sock_srv.c]: I don't see the reason in second `atomic_read()` operation here. Why not just  simple `else`?

**Comment by krizhanovsky** [comment]
@keshonok please add the comment as you've discussed

**Comment by krizhanovsky** [comment]
@keshonok please add the comment as you've discussed and double check with @ikoveshnikov, who reproduced the issue, that #782 is no longer appear. It's also worth to run full cycle of our functional tests.

**Comment by ikoveshnikov** [comment]
I can confirm that the issue is not reproduced with the patch applied. I also run the full cycle of the functional tests and everything is still fine. The patch can be merged as soon as the comment is added to the patch.
