### PR TITLE
Fix #651

### LINKED ISSUE #651: kernel crash in __pskb_copy_fclone()
This occurs on current master at b2f706a. The configuration is the simplest: the back end server runs in the same virtual machine with Tempesta. The back end server is Apache and it's configured with a copy of tempesta-tech.com web site as a virtual host. All other Apache configuration options are default.
```
server 127.0.0.1:8080;
cache 0;
```

Default configuration options for Apache mean that the server closes connections every 100 requests. As far as I can see that plays a role in the kernel crash.

The crash occurs from time to time when Tempesta is stressed with a large stream of concurrent requests from the host system. It doesn't occur every time but it happens often enough. The following command is used:
```
wrk -t 128 -c 4096 -d 60s http://192.168.10.230/
```
The crash doesn't seem to occur when Tempesta is stressed with Apache's `ab` tool.

Below is the stack trace of the crash.

```
[50264.709671] general protection fault: 0000 [#1] SMP
[50264.710627] Modules linked in: tfw_sched_rr(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) tempesta_tls(PO) ppdev 9pnet_virtio aesni_intel aes_x86_64 glue_helper lrw gf128mul ablk_helper cryptd 9pnet microcode virtio_balloon i2c_piix4 i2c_core pcspkr parport_pc parport acpi_cpufreq ip_tables ata_generic pata_acpi crc32c_intel virtio_pci e1000 virtio_ring serio_raw virtio ata_piix floppy ipv6 autofs4 [last unloaded: tempesta_tls]
[50264.710627] CPU: 0 PID: 3 Comm: ksoftirqd/0 Tainted: P           O    4.1.27-ab+ #1
[50264.710627] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS Bochs 01/01/2011
[50264.710627] task: ffff88011af9a090 ti: ffff88011afa0000 task.ti: ffff88011afa0000
[50264.710627] RIP: 0010:[<ffffffff81520567>]  [<ffffffff81520567>] __pskb_copy_fclone+0x1b7/0x230
[50264.710627] RSP: 0018:ffff88011afa3728  EFLAGS: 00010212
[50264.710627] RAX: 0800000000000000 RBX: ffff88000209dc00 RCX: 6b6b6b6bd6d6d6d6
[50264.710627] RDX: ffff88008fd6a0c0 RSI: ffff8800ba854230 RDI: ffff8800ba8542a8
[50264.710627] RBP: ffff88011afa3748 R08: 0000000000000000 R09: ffffea00028d7910
[50264.710627] R10: 000000180000004e R11: 0000000000000000 R12: ffff8800ba854000
[50264.710627] R13: 0000000000000001 R14: ffffea00028d7910 R15: 0000000000000000
[50264.710627] FS:  0000000000000000(0000) GS:ffff88013fc00000(0000) knlGS:0000000000000000
[50264.710627] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[50264.710627] CR2: 000055f2a2bbf000 CR3: 00000000913dc000 CR4: 00000000001406f0
[50264.710627] Stack:
[50264.710627]  ffff88000209dc00 0000000000000002 ffff88008fd1cb40 000000000000000c
[50264.710627]  ffff88011afa3798 ffffffffa143dbd1 ffff88008fd1cb40 0000000000000000
[50264.710627]  0000000000000000 0000000000000002 ffff8800ba4bce90 ffff880091060020
[50264.710627] Call Trace:
[50264.710627]  [<ffffffffa143dbd1>] ss_send+0xc1/0x1b0 [tempesta_fw]
[50264.710627]  [<ffffffffa142b6ec>] tfw_http_conn_send+0x1c/0x20 [tempesta_fw]
[50264.710627]  [<ffffffffa142a5d4>] tfw_connection_send+0x24/0x30 [tempesta_fw]
[50264.710627]  [<ffffffffa142c5df>] tfw_http_req_cache_cb+0x1df/0x280 [tempesta_fw]
[50264.710627]  [<ffffffffa142c400>] ? tfw_http_send_404+0xc0/0xc0 [tempesta_fw]
[50264.710627]  [<ffffffffa14274c9>] tfw_cache_process+0x129/0x2c0 [tempesta_fw]
[50264.710627]  [<ffffffff810b794d>] ? trace_hardirqs_on+0xd/0x10
[50264.710627]  [<ffffffff810e9134>] ? __getnstimeofday64+0x94/0x150
[50264.710627]  [<ffffffff810e91fe>] ? getnstimeofday64+0xe/0x30
[50264.710627]  [<ffffffffa142cbf7>] tfw_http_msg_process+0x367/0x5f0 [tempesta_fw]
[50264.710627]  [<ffffffffa142ae22>] __gfsm_fsm_exec+0x62/0xa0 [tempesta_fw]
[50264.710627]  [<ffffffffa142b064>] tfw_gfsm_dispatch+0x14/0x20 [tempesta_fw]
[50264.710627]  [<ffffffffa142a5fd>] tfw_connection_recv+0x1d/0x20 [tempesta_fw]
[50264.710627]  [<ffffffffa143de47>] ss_tcp_process_data+0x187/0x3a0 [tempesta_fw]
[50264.710627]  [<ffffffffa143e0c8>] ss_tcp_data_ready+0x68/0xb0 [tempesta_fw]
[50264.710627]  [<ffffffff8159a34a>] tcp_rcv_established+0x3ea/0x740
[50264.710627]  [<ffffffff815a5943>] tcp_v4_do_rcv+0x103/0x430
[50264.710627]  [<ffffffff815a7055>] tcp_v4_rcv+0xb25/0xc40
[50264.710627]  [<ffffffff8157d2bc>] ? ip_local_deliver_finish+0x4c/0x3f0
[50264.710627]  [<ffffffff8157d3af>] ip_local_deliver_finish+0x13f/0x3f0
[50264.710627]  [<ffffffff8157d2bc>] ? ip_local_deliver_finish+0x4c/0x3f0
[50264.710627]  [<ffffffff8157d8da>] ip_local_deliver+0x9a/0xb0
[50264.710627]  [<ffffffff815a64ac>] ? tcp_v4_early_demux+0x10c/0x190
[50264.710627]  [<ffffffff8157ce18>] ip_rcv_finish+0x168/0x5c0
[50264.710627]  [<ffffffff8157dbdf>] ip_rcv+0x2ef/0x420
[50264.710627]  [<ffffffff8157ccb0>] ? inet_del_offload+0x40/0x40
[50264.710627]  [<ffffffff815324e0>] __netif_receive_skb_core+0x320/0xd00
[50264.710627]  [<ffffffff81532edd>] __netif_receive_skb+0x1d/0x60
[50264.710627]  [<ffffffff81532f9e>] process_backlog+0x7e/0x240
[50264.710627]  [<ffffffff81533003>] ? process_backlog+0xe3/0x240
[50264.710627]  [<ffffffff81534d5b>] net_rx_action+0x15b/0x520
[50264.710627]  [<ffffffff810d95ca>] ? rcu_process_callbacks+0x58a/0xa80
[50264.710627]  [<ffffffff81064d35>] __do_softirq+0xd5/0x640
[50264.710627]  [<ffffffff810652bf>] run_ksoftirqd+0x1f/0x70
[50264.710627]  [<ffffffff81087fb9>] smpboot_thread_fn+0x129/0x1f0
[50264.710627]  [<ffffffff81087e90>] ? sort_range+0x30/0x30
[50264.710627]  [<ffffffff8108408f>] kthread+0xef/0x110
[50264.710627]  [<ffffffff81083fa0>] ? kthread_create_on_node+0x210/0x210
[50264.710627]  [<ffffffff8162eb52>] ret_from_fork+0x42/0x70
[50264.710627]  [<ffffffff81083fa0>] ? kthread_create_on_node+0x210/0x210
[50264.710627] Code: 00 00 48 03 93 e0 00 00 00 4c 8b 34 02 49 8b 06 f6 c4 80 75 46 f0 41 ff 46 1c 8b 8b dc 00 00 00 41 83 c5 01 48 03 8b e0 00 00 00 <0f> b6 01 44 39 e8 7f 99 44 89 e8 41 8b 94 24 dc 00 00 00 49 8b
[50264.710627] RIP  [<ffffffff81520567>] __pskb_copy_fclone+0x1b7/0x230
[50264.710627]  RSP <ffff88011afa3728>
```

### PR DESCRIPTION
**Pull request by krizhanovsky**

### CODE REVIEW

File: tempesta_fw/http.h [hunk 1]
```diff
@@ -259,7 +258,10 @@ typedef struct {
  * Common HTTP message members.
  *
  * @version		- HTTP version (1.0 and 1.1 are only supported);
- * @flags		- message related flags;
+ * @flags		- message related flags. The flags are used in
+ *			  concurrent read and writes, but concurrent writes
+ *			  aren't alowed. So use atomic operations if concurrent
+ *			  updates are possible;
```
Comment (keshonok) [inline tempesta_fw/http.h]: Atomic bitwise operations work on machine words even though they change just one specific bit. On x86_64 that's 64 bits or `unsigned long`. For that reason it might be safer if the `flags` member is of type `unsigned long`.

By the way, how about moving all flags operations to non-atomic __set_bit/__clear_bit/__flip_bit and the similar atomic set_bit/clear_bit/flip_bit where necessary? Would that be a cleaner solution?

File: tempesta_fw/sock.c [hunk 2]
```diff
@@ -230,8 +238,10 @@ ss_send(struct sock *sk, SsSkbList *skb_list, int flags)
 	 * This isn't reliable check, but rather just an optimization to
 	 * avoid expensive work queue operations.
 	 */
-	if (unlikely(!ss_sock_active(sk)))
-		return 0;
+	if (unlikely(!ss_sock_active(sk))) {
+		SS_DBG("Try to send on inactive socket %p\n", sk);
```
Comment (keshonok) [inline tempesta_fw/sock.c]: An attempt to send to...

Comment (krizhanovsky) [inline tempesta_fw/sock.c]: Fixed, thanks
